### ISSUE TITLE
Missing Title and breadcrumbs blocks on certain pages.

### ISSUE THREAD

**Issue by willsstrong** [ytgov/yukon-ca#117]
There is a bug in block settings where when the visibility settings for content types are set as negated, this has the unintended result of omitting the block from any page that is not a content type.  

e.g. top-level blog index page, top-level blog page (e.g. Digital information and services blog)

![block_config_page](https://user-images.githubusercontent.com/38888375/229193299-2d9e8481-01c4-4620-9d8b-2e433c611737.png)

This is manifested in our case as the title block and breadcrumbs block are appropriately omitted from homepage, landing page and landing page L2; but is also omitted from the Government of Yukon blogs page (a view page) as well as the blog listings for each blog type (taxonomy term pages).

![blogs_landing_page](https://user-images.githubusercontent.com/38888375/229193563-5b9e1347-de98-49ac-b6a3-daeea32128a1.png)

![blog-type_term_page](https://user-images.githubusercontent.com/38888375/229193747-c81d5b71-9f03-407f-8f49-3524725479e8.png)

### Proposed Solution

Use the [Block Visibility Conditions](https://www.drupal.org/project/block_visibility_conditions) to allow better control over setting conditions in which block are shown or hidden.

**Comment by leeomara** [comment]
This appears to be the commit that relates to setting up visibility (to prevent them from being displayed on those specific content types): https://github.com/ytgov/yukon-ca/commit/1bd16b512aaa4060ac0b61146a1243cd65f7a561

**Comment by leeomara** [comment]
@willsstrong If you reverse the logic of this block configuration, does this issue persist? E.g. if you check all except for "Homepage", "Landing page" and "Landing page level 2", does title return to View and Taxonomy pages?

**Comment by theteknocat** [comment]
@leeomara in our experience, the reverse as you suggest does NOT make it work either. This block visibility configuration means you either ONLY show it on nodes of those types or you only show it on nodes NOT of those types, but either way NEVER on any other types of pages that are not nodes.

**Comment by leeomara** [comment]
So what's I'm hearing is that block visibility by node type is not appropriate for the site at all then, regardless of if the condition is negated or not.

**Comment by leeomara** [comment]
Why not use CSS to make the title invisible on pages for those select content types? That would avoid the whole  "hiding the title here accidentally hides it there" mess.

**Comment by theteknocat** [comment]
@leeomara that's what we've done in our base site, actually. We did it that way because we still wanted a page title using the appropriate heading level for accessibility, but just not visible to the user.

**Comment by leeomara** [comment]
This doesn't seem to be an issue anymore. 

The following all have breadcrumbs visible.

- https://yukond10.cms-uat.yukon.ca/en/blogs
- https://yukond10.cms-uat.yukon.ca/en/blogs/digital-information-and-services
- https://yukond10.cms-uat.yukon.ca/en/news
- https://yukond10.cms-uat.yukon.ca/en/news/statement-minister-health-and-social-services-three-year-anniversary-supervised-consumption
