### ISSUE TITLE
Setup/onboarding experience

### ISSUE THREAD

**Issue by leeomara** [ytgov/yukon-ca#123]
When I tested getting this site set up locally, I ran into some issues. Here is a summary

# Overall approach

We want to make it easy and predicable for new developers to onboard to this project. The current documentation led to some false starts, and also my guessing at the wrong approach (e.g. using site-install instead of config import)

# Handling files for migration

It wasn't clear to me that I didn't need to copy site files to my machine in order to run the migration.

Files are pulled over the network. We should document that somewhere. E.g. in prerequisites?

# Incorrect stack definition 'ew-pantheon'

When trying to start Docksal, I ran into this error:

```
➜  yukon-ca-d10 git:(master) ✗ fin start
 ERROR:  Incorrect stack definition 'ew-pantheon'
         Stack file does not exist: /Users/leeo/.docksal/stacks/stack-ew-pantheon.yml
➜  yukon-ca-d10 git:(master) ✗ 
```

Oh, per https://github.com/ytgov/yukon-ca/blob/master/LocalSetup.md, it's at https://gitlab.ewdev.ca/universe/docksal

Maybe that's good enough?

# Large legacy DB

How should we better deal with this on Pantheon? Should we even bother?

Should we split the DB into regular/predictable chunks? How to align that with migrations?

Should we group migrations and DB exports to align with how we plan to manage the project (e.g. sections)?

# Building the theme

It uses Gulp, which Docksal knows about (somehow)

	fin gulp

Wow, does that ever go for a long time. Eventually (many minutes later), it bails with this error

```
  patterns/atoms/blockquote/scss/styles.scss 1:9  root stylesheet
    messageOriginal: Undefined variable.
   ╷
55 │     "primary": $primary-text-emphasis-dark,
   │                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
  node_modules/bootstrap/scss/_maps.scss 55:16    @import
  src/sass/_core.scss 37:9                        @import
  patterns/atoms/blockquote/scss/styles.scss 1:9  root stylesheet
    relativePath: node_modules/bootstrap/scss/_maps.scss

[22:21:44] 'default' errored after 3.37 s
```

So, why is that variable undefined?

Seems to be a problem with `./docroot/themes/custom/yukonca_glider/src/sass/_core.scss`, not with `_maps.scss`.

Add

```sass
$enable-dark-mode: false;
```

to `src/_variables.scss`. Then gulp runs.

# Config import site UUID

Config import will likely fail

set site ID `drush cset system.site uuid "41650bf6-b2e8-41ee-beae-5f2a13f23d66" --yes`

# Config import fails

Importing the config failed a number of times.

Tried installing the patch from BaseFieldOverride fails to take into account 

Maybe that Drupal config import error is this? BaseFieldOverride fails to take into account ContentEntityInterface::bundleFieldDefinitions() when invoking onFieldDefinitionUpdate()
  https://www.drupal.org/project/drupal/issues/2321071

Or maybe this? The "moderation_state" base field overrides cause install from existing config to fail
  https://www.drupal.org/project/drupal/issues/3129874

ContentEntityInterface::bundleFieldDefinitions() when invoking onFieldDefinitionUpdate() #39
  https://www.drupal.org/files/issues/2019-12-24/2321071-39.patch

after after 2 failures, config import completed.

**Comment by w3creatives** [comment]
Please close if this is done. Config import will have an error on the first import that can be ignored. Readme file has it documented.
