### ISSUE TITLE
[P-1] Homepage

### ISSUE THREAD

**Issue by ab-ew** [ytgov/yukon-ca#124]
All the activities related to the homepage development.

- [x] #126
- [x] #128
- [x] #127
- [x] #129
- [x] #130
- [x] #131
- [x] #132
- [ ] #133
- [x] #134
- [x] #135
- [x] #125

**Migration dependencies:**
- [ ] #155 
- [x] #136 
- [x] #137 
- [ ] Image Gallery Paragraph
- [ ] Department taxonomy terms
- [ ] Teams taxonomy terms

**Comment by leeomara** [comment]
I'm going to consider this done.
