### ISSUE TITLE
[P-4] Latest News labels always in English

### ISSUE THREAD

**Issue by ab-ew** [ytgov/yukon-ca#125]
**Description:**

The labels for the latest news block are always in English, this happens because the current block - view don't have the translation enable.

**Task:**

Enable latest views block translation.

**Deliverable:**

Working translation FR/EN on latest news block on the homepage.

![Screenshot_2023-09-14_at_3 08 41_PM](https://github.com/ytgov/yukon-ca/assets/93003/449c9acc-801f-4122-8178-ff67f6527014)

**Comment by ew-andrew-sus** [comment]
@w3creatives PR is merged to the 'develop' branch. Complete deployment steps if needed and check the task on [develop multidev env](https://develop-yukon-drupal-10.pantheonsite.io/) please.

**Comment by leeomara** [comment]
When I load the homepage on multidev (`develop`), at https://develop-yukon-drupal-10.pantheonsite.io/home, I don't see any "Latest news" section.

The French version of the page also does not have a "Latest news" section. https://develop-yukon-drupal-10.pantheonsite.io/fr/accueil

**Comment by w3creatives** [comment]
It was due to the root URL setting. The website homepage was set to /home and the "Latest news" section visible is enabled for the homepage only.  We have fixed this issue to be tested.

**Comment by leeomara** [comment]
As [reported last week](https://github.com/ytgov/yukon-ca/issues/127#issuecomment-1954482035), "Latest news" is missing from the French homepage.

https://develop-yukon-drupal-10.pantheonsite.io/fr/accueil

**Comment by leeomara** [comment]
This looks right in `dev`, at https://dev-yukon-drupal-10.pantheonsite.io/fr

**Comment by leeomara** [comment]
Now looks good on `test`.
