### ISSUE TITLE
[P-1] Featured content description missing

### ISSUE THREAD

**Issue by ab-ew** [ytgov/yukon-ca#127]
![Screenshot_2023-09-14_at_2 28 01_PM](https://github.com/ytgov/yukon-ca/assets/93003/f1272429-9acf-427d-b5f2-52c6157bc640)

**Comment by ew-andrew-sus** [comment]
@w3creatives PR is merged to the 'develop' branch. Complete deployment steps if needed and check the task on [develop multidev env](https://develop-yukon-drupal-10.pantheonsite.io/) please.

**Comment by leeomara** [comment]
@w3creatives when I try to test this, at https://develop-yukon-drupal-10.pantheonsite.io/ (which redirects to https://develop-yukon-drupal-10.pantheonsite.io/home), I see no "Featured content" section, so cannot verify this fix.

**Comment by leeomara** [comment]
A similar problem has come up before, for "Latest news", see https://github.com/ytgov/yukon-ca/issues/125#issuecomment-1915789228

**Comment by w3creatives** [comment]
Revision submitted because of the broken link in the description body.

**Comment by ew-andrew-sus** [comment]
@w3creatives PR is merged to the 'develop' branch. Complete deployment steps if needed and check the task on [develop multidev env](https://develop-yukon-drupal-10.pantheonsite.io/) please.

**Comment by leeomara** [comment]
Tested on `develop` and `dev`, working. E.g. https://dev-yukon-drupal-10.pantheonsite.io/

Not yet on `test`.

**Comment by leeomara** [comment]
Now looks good on `test`.
