### ISSUE TITLE
[P-3] Box icons and text larger

### ISSUE THREAD

**Issue by ab-ew** [ytgov/yukon-ca#128]
![Screenshot_2023-09-14_at_2 23 43_PM](https://github.com/ytgov/yukon-ca/assets/93003/f1ca5cf7-7d79-4378-b1b2-dd6ed468e2ef)

**Comment by ew-andrew-sus** [comment]
@w3creatives PR is merged to the 'develop' branch. Complete deployment steps if needed and check the task on [develop multidev env](https://develop-yukon-drupal-10.pantheonsite.io/) please.

**Comment by lgontard** [comment]
This is done on dev and test

**Comment by leeomara** [comment]
Now looks good on `test`.
