### ISSUE TITLE
[P-3] "Latest News" should be "Latest news"

### ISSUE THREAD

**Issue by ab-ew** [ytgov/yukon-ca#129]

**Comment by lgontard** [comment]
This is on the test site https://test-yukon-drupal-10.pantheonsite.io/

**Comment by w3creatives** [comment]
@ew-andrew-sus we do not see it on the [develop](https://develop-yukon-drupal-10.pantheonsite.io/) branch.  Changes in the commit seems to be correct.

**Comment by ew-andrew-sus** [comment]
@w3creatives Hm, according to the git history you reverted these changes. So create a new PR with the fix, please.
![image](https://github.com/ytgov/yukon-ca/assets/123640502/3bee76f6-0788-4f25-b2cc-b89ceaf75a53)

**Comment by leeomara** [comment]
Looks good at https://develop-yukon-drupal-10.pantheonsite.io/
![Screenshot 2024-02-07 at 8 59 55 AM](https://github.com/ytgov/yukon-ca/assets/93003/14bfa31c-2b5e-47fa-a86e-269dc864f16f)

**Comment by leeomara** [comment]
Now looks good on `test`.
