### ISSUE TITLE
[P-3] Duplicate second "Latest news" section

### ISSUE THREAD

**Issue by ab-ew** [ytgov/yukon-ca#130]
![Screenshot_2023-09-14_at_2 34 00_PM](https://github.com/ytgov/yukon-ca/assets/93003/81dbc6ac-3d8c-48c1-82df-fe9fdf45459c)

**Comment by ew-andrew-sus** [comment]
@w3creatives PR is merged to the 'develop' branch. Complete deployment steps if needed and check the task on [develop multidev env](https://develop-yukon-drupal-10.pantheonsite.io/) please.

**Comment by lgontard** [comment]
Tied to issue #129 Latest news section duplicated at the bottom of the homepage. 


![Image](https://github.com/ytgov/yukon-ca/assets/157647061/52fee5db-65e7-458c-861e-691e8452b024)

**Comment by lgontard** [comment]
The duplication is on the test site https://test-yukon-drupal-10.pantheonsite.io/

**Comment by leeomara** [comment]
Now looks good on `test`.
