### ISSUE TITLE
[P-3] News items are repeated

### ISSUE THREAD

**Issue by ab-ew** [ytgov/yukon-ca#131]
![Screenshot_2023-09-14_at_2 32 50_PM](https://github.com/ytgov/yukon-ca/assets/93003/a7bb533f-fdb1-4ec1-80e3-6ad0b41e7ab3)

**Comment by ew-andrew-sus** [comment]
@w3creatives PR is merged to the 'develop' branch. Complete deployment steps if needed and check the task on [develop multidev env](https://develop-yukon-drupal-10.pantheonsite.io/) please.

**Comment by leeomara** [comment]
I cannot find "Latest news" on the homepage at https://develop-yukon-drupal-10.pantheonsite.io/home. I cannot test this fix when the view is not being displayed.

**Comment by w3creatives** [comment]
It was due to the root URL setting. The website homepage was set to /home and the "Latest news" section visible is enabled for the homepage only.  We have fixed this issue to be tested.

**Comment by leeomara** [comment]
Reviewed the homepage, there are no duplicate items.

**Comment by leeomara** [comment]
Re-opening, to try correcting the workflow for this issue

**Comment by leeomara** [comment]
Reviewed the homepage on `dev`. There are no duplicate items.

**Comment by leeomara** [comment]
Now looks good on `test`.
