### ISSUE TITLE
[P-2] Featured content should have only single link

### ISSUE THREAD

**Issue by ab-ew** [ytgov/yukon-ca#132]
![Screenshot_2023-09-14_at_2 47 58_PM](https://github.com/ytgov/yukon-ca/assets/93003/dd369c7f-b388-4545-afba-6ff8861efe91)

**Comment by ew-andrew-sus** [comment]
@w3creatives PR is merged to the 'develop' branch. Complete deployment steps if needed and check the task on [develop multidev env](https://develop-yukon-drupal-10.pantheonsite.io/) please.

**Comment by lgontard** [comment]
On dev site https://develop-yukon-drupal-10.pantheonsite.io/ there is no link to feature content.
Also, the second featured content is a millimetre or two lower than the first one.

It's working on test site https://test-yukon-drupal-10.pantheonsite.io/ but the second featured content is a millimetre or two lower than the first one.

![Image](https://github.com/ytgov/yukon-ca/assets/157647061/0cd98447-1276-4b9a-b76a-a43f0ebec9a5)

**Comment by leeomara** [comment]
When looking at the admin interface for a Homepage node on `develop`, I no longer see the option for multiple links for each Featured Content image gallery.

I believe this issue is resolved.

![Screenshot 2024-02-01 at 9 32 31 AM](https://github.com/ytgov/yukon-ca/assets/93003/7c07aff1-0df2-4051-b585-c13c28ae083a)

**Comment by leeomara** [comment]
Re-opening, to try correcting the workflow for this issue

**Comment by leeomara** [comment]
When looking at the admin interface for a Homepage node on `dev`, I no longer see the option for multiple links for each Featured Content image gallery. I believe this issue is resolved.

**Comment by leeomara** [comment]
Now looks good on `test`.
