### ISSUE TITLE
[P-2] Clarify language for managing Featured content

### ISSUE THREAD

**Issue by ab-ew** [ytgov/yukon-ca#133]
The button “[Add image gallery] to _Featured Content_” should be “[Add Slide] to _Featured Content_”

**Comment by ew-andrew-sus** [comment]
@w3creatives PR is merged to the 'develop' branch. Complete deployment steps if needed and check the task on [develop multidev env](https://develop-yukon-drupal-10.pantheonsite.io/) please.

**Comment by leeomara** [comment]
Testing at https://develop-yukon-drupal-10.pantheonsite.io/node/47271/edit?destination=/admin/content, I still see the button labelled "[Add Image Gallery] to _Featured content"_


![Image](https://github.com/ytgov/yukon-ca/assets/93003/207211ba-b7a6-4643-aec3-a24ff055af52)

**Comment by leeomara** [comment]
I now see the button labelled "[Add Slide] to Featured content". 

![Screenshot 2024-01-30 at 4 37 34 PM](https://github.com/ytgov/yukon-ca/assets/93003/a7c02c32-399f-4469-a740-20e866263952)

**Comment by leeomara** [comment]
Re-opening, to try correcting the workflow for this issue

**Comment by leeomara** [comment]
Testing on `dev`, at https://dev-yukon-drupal-10.pantheonsite.io/node/add/homepage, I still see the button labelled "[Add Image Gallery] to Featured content"

**Comment by w3creatives** [comment]
This task got reverted and that was why submitted again.

**Comment by leeomara** [comment]
On `dev`, I now (correctly) see "[Add Slide] to Featured content".

**Comment by leeomara** [comment]
Testing on `test`, at https://test-yukon-drupal-10.pantheonsite.io/node/add/homepage, I still see the button labelled "[Add Image Gallery] to Featured content"

**Comment by leeomara** [comment]
On UAT I now (correctly) see "[Add Slide] to Featured content".
