### ISSUE TITLE
[P-2] Homepage edits should always make new revisions

### ISSUE THREAD

**Issue by ab-ew** [ytgov/yukon-ca#134]
![Screenshot_2023-09-14_at_3 02 09_PM](https://github.com/ytgov/yukon-ca/assets/93003/6820ef48-748c-437f-ae7b-698e9551f918)

**Comment by ew-andrew-sus** [comment]
@w3creatives PR is merged to the 'develop' branch. Complete deployment steps if needed and check the task on [develop multidev env](https://develop-yukon-drupal-10.pantheonsite.io/) please.

**Comment by leeomara** [comment]
Tested at https://develop-yukon-drupal-10.pantheonsite.io/node/47271/edit?destination=/admin/content, new revision is selected by default.

**Comment by leeomara** [comment]
Re-opening, to try correcting the workflow for this issue

**Comment by leeomara** [comment]
Tested on `dev`, at https://dev-yukon-drupal-10.pantheonsite.io/node/47271/edit, new revision is selected by default.

**Comment by leeomara** [comment]
Now looks good on `test`.
