### ISSUE TITLE
[P-4] French homepage shows English section content

### ISSUE THREAD

**Issue by ab-ew** [ytgov/yukon-ca#135]
While the section titles are French, the content (e.g. three links) are English.

![Screenshot_2023-09-14_at_3 05 15_PM](https://github.com/ytgov/yukon-ca/assets/93003/0eb56ebc-31c9-4214-bed9-7b242b4bc387)

**Comment by ew-andrew-sus** [comment]
@w3creatives It isn't clear why this task is assigned to us in the dashboard. Do you need any support/info here?

**Comment by w3creatives** [comment]
Missed to add comments. It is the Landing Page content that we believe will be fixed once we run the custom module we built for [#142](https://github.com/ytgov/yukon-ca/issues/142).

**Comment by leeomara** [comment]
This looks good at https://develop-yukon-drupal-10.pantheonsite.io/fr

![Screenshot 2024-02-07 at 9 02 32 AM](https://github.com/ytgov/yukon-ca/assets/93003/cef9981a-f4b3-4d92-b27a-d7a3c27ea7e9)

**Comment by leeomara** [comment]
Now looks good on `test`.
