### ISSUE TITLE
[P-2] Landing page

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#136]
All the activities related to the Landing page development.

- [x] #209
- [x] #210
- [x] #211

**Migration dependencies:**

- [ ] Icon Media Type
- [ ] Primary Content field Paragraph
- [ ] Secondary Content field Paragraph
- [ ]  Department taxonomy terms
- [ ] Teams taxonomy terms

**Comment by leeomara** [comment]
I'm good to class this closed.
