### ISSUE TITLE
[P-3] Landing page Level 2

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#137]
All the activities related to the Landing page Level 2  development.

- [x] #138
- [x] #139
- [x] #140
- [x] #141
- [x] #142
- [x] #143
- [x] #144
- [x] #145
- [x] #146

**Migration dependencies:**

- [ ] Icon Media Type
- [ ] Primary Content field Paragraph
- [ ] Secondary Content field Paragraph
- [ ] Department taxonomy terms
- [ ] Teams taxonomy terms

**Comment by leeomara** [comment]
I'm good to call this closed.
