### ISSUE TITLE
[P-3] Text and icon in header overlap aurora graphic

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#138]
**Description:**

This is the case on both pages ([Yukon.ca](http://yukon.ca/) D7 and Kellett D10), but more pronounced on the Kellet version. See attached screen grab. Text and icon should not overlap.

It does appear as it should on a mobile screen.
![screenshot](https://github.com/ytgov/yukon-ca/assets/123640502/d21aaf66-a363-4277-8fe9-7c85153fb8ae)

**Task:**

Fix styling according to D7

**Deliverable:**
Text and icon in header shouldn't overlap aurora graphic

**Comment by ew-andrew-sus** [comment]
@w3creatives PR is merged to the 'develop' branch. Complete deployment steps if needed and check the task on [develop multidev env](https://develop-yukon-drupal-10.pantheonsite.io/) please.

**Comment by leeomara** [comment]
Looks good. Tested at https://develop-yukon-drupal-10.pantheonsite.io/immigration/yukon-business-nominee-program

![Screenshot 2024-02-07 at 9 05 53 AM](https://github.com/ytgov/yukon-ca/assets/93003/38bca0ea-5493-43fb-b6b2-0c6476c3f021)

**Comment by leeomara** [comment]
Now looks good on `test`. https://test-yukon-drupal-10.pantheonsite.io/doing-business/yukon-nominee-program-foreign-workers
