### ISSUE TITLE
[P-3] Font contrast is off

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#139]
**Description:**
The font is not appearing as dark at it should, but it’s all there. The contrast on the headings is good. The horizontal rule is also lighter than it appears on [Yukon.ca](http://yukon.ca/) D7.
![screenshot_2](https://github.com/ytgov/yukon-ca/assets/123640502/b3ab8bda-da5a-460b-ad06-6a0357dbd013)

**Task:**
Make the font like in D7

**Deliverable:**
Font contrast should be the same as on D7

**Comment by leeomara** [comment]
Comparing the "Your government" page on [D7](https://yukon.ca/your-government) with [D10](https://develop-yukon-drupal-10.pantheonsite.io/your-government), the colour seems correct.

![Screenshot 2024-02-26 at 12 55 39 PM](https://github.com/ytgov/yukon-ca/assets/93003/c0b2832b-66f0-44f6-ac94-b44159d9b54c)

**Comment by leeomara** [comment]
Now looks good on `test`.

**Comment by leeomara** [comment]
Now looks good on `test`.
