### ISSUE TITLE
[P-1] List of pages not consistent

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#140]
**Description:**
On the Apply to immigrate to the Yukon page ([Yukon.ca](http://yukon.ca/) D7) there are only 4 pages under What are you looking for? On the D10 site there are 25 links and most appear to be the main categories of [Yukon.ca](http://yukon.ca/).
![screenshot_3](https://github.com/ytgov/yukon-ca/assets/123640502/41afa8a5-add5-4238-a9df-112fdbc6115f)
![screenshot_4](https://github.com/ytgov/yukon-ca/assets/123640502/7707ffdd-b49b-499b-994e-898a5343ffd5)

**Task:**
Fix migration logic to solve link count.

**Deliverable:**
The list of pages should be consistent

**Comment by ew-andrew-sus** [comment]
@w3creatives PR is merged to the 'develop' branch. Complete deployment steps if needed and check the task on [develop multidev env](https://develop-yukon-drupal-10.pantheonsite.io/) please.

**Comment by w3creatives** [comment]
@leeomara 

Please compare the two sites to see the output. The title "**What are looking for**" is missing because migration needs to be re-run.

**Test Site:**
https://test-yukon-drupal-10.pantheonsite.io/archives

**Develop Site:**
https://develop-yukon-drupal-10.pantheonsite.io/archives

**Comment by lgontard** [comment]
On dev site https://develop-yukon-drupal-10.pantheonsite.io/apply-immigrate-yukon the "What are you looking for" and the underline are missing above the list of pages.
On the test site, the English and French pages are listed, but the "What are you looking for" and the underline are missing


![Image](https://github.com/ytgov/yukon-ca/assets/157647061/7bc1de6b-6f30-44ec-937d-7e8e9379b9fa)


![Image](https://github.com/ytgov/yukon-ca/assets/157647061/959917cb-97ef-4729-80db-12c5112d069e)

**Comment by w3creatives** [comment]
Revision submitted to fix the order as per site's default language.

**Comment by ew-andrew-sus** [comment]
@w3creatives PR is merged to the 'develop' branch. Complete deployment steps if needed and check the task on [develop multidev env](https://develop-yukon-drupal-10.pantheonsite.io/) please.

**Comment by leeomara** [comment]
D10 now looks correct. Tested:

- https://develop-yukon-drupal-10.pantheonsite.io/immigration/apply-immigrate-yukon (vs. https://yukon.ca/en/immigration/apply-immigrate-yukon-0)
- https://develop-yukon-drupal-10.pantheonsite.io/arts-and-culture/archives (vs. https://yukon.ca/archives)

![Screenshot 2024-02-26 at 1 30 19 PM](https://github.com/ytgov/yukon-ca/assets/93003/06fb96a2-d8c8-48fa-a2d7-da2026c2b354)

**Comment by leeomara** [comment]
Now looks good on `test`.
