### ISSUE TITLE
[P-3] Top tasks boxes not sizing properly

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#141]
**Description:**
The boxes that house the top tasks resize in D10 if the page title wraps to a second line. They should not do this.
![screenshot_5](https://github.com/ytgov/yukon-ca/assets/123640502/83642b36-2c3f-47d3-9492-91f97c71357c)
![screenshot_6](https://github.com/ytgov/yukon-ca/assets/123640502/66c2fb5c-4764-492e-a330-ef4f251d1171)

**Task:**
Fix top task boxes size

**Deliverable:**
Top task boxes should have the same size as on D7

**Comment by ew-andrew-sus** [comment]
@w3creatives PR is merged to the 'develop' branch. Complete deployment steps if needed and check the task on [develop multidev env](https://develop-yukon-drupal-10.pantheonsite.io/) please.

**Comment by lgontard** [comment]
In test site, top task blocks not resizing properly https://test-yukon-drupal-10.pantheonsite.io/doing-business

In dev site, top task blocks resize properly https://develop-yukon-drupal-10.pantheonsite.io/doing-business

![Image](https://github.com/ytgov/yukon-ca/assets/157647061/20178c26-b329-4ee5-8d61-b1f8145122a8)


![Image](https://github.com/ytgov/yukon-ca/assets/157647061/dcb47379-3507-4f5e-81e7-c95f35ae88a5)

**Comment by lgontard** [comment]
Thanks for the clarification. I've edited my comment above and moved the card to the done column @ab-ew @leeomara @w3creatives @ew-andrew-sus

**Comment by leeomara** [comment]
Now looks good on `test`.
