### ISSUE TITLE
[P-1] French translation does not appear

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#142]
**Description:**
On the French pages, the page title and breadcrumbs are translates, but the main content is listing the English pages.
![image](https://github.com/ytgov/yukon-ca/assets/123640502/18990345-e6dc-424b-81dc-618f95f8a2fc)
![image](https://github.com/ytgov/yukon-ca/assets/123640502/c6ad73e8-4a6a-42cd-ac86-65c2b6948185)
![image](https://github.com/ytgov/yukon-ca/assets/123640502/c1779920-6e98-4272-8e2f-2efecf88344f)

**Task:**
Fix translation migration

**Deliverable:**
French translation should present

**Comment by ew-andrew-sus** [comment]
@w3creatives PR is merged to the 'develop' branch. Complete deployment steps if needed and check the task on [develop multidev env](https://develop-yukon-drupal-10.pantheonsite.io/) please.

**Comment by leeomara** [comment]
I still see "Top tasks" on this French page: https://develop-yukon-drupal-10.pantheonsite.io/fr/aeroport-international-erik-nielsen-de-whitehorse

The title above the list, which should show "Que cherchez-vous?" on this French page is absent. https://develop-yukon-drupal-10.pantheonsite.io/fr/emploi/emplois-en-education  Possibly related, that title is also missing on the English version.

![Screenshot 2024-02-07 at 9 14 38 AM](https://github.com/ytgov/yukon-ca/assets/93003/d1c9e0f8-80ed-4005-a825-3846e9e0363a)

![Screenshot 2024-02-07 at 9 11 42 AM](https://github.com/ytgov/yukon-ca/assets/93003/beb2a66d-34b8-4c1b-8ff0-f40785bdb822)

**Comment by ew-andrew-sus** [comment]
@w3creatives PR is merged to the 'develop' branch. Complete deployment steps if needed and check the task on [develop multidev env](https://develop-yukon-drupal-10.pantheonsite.io/) please.

**Comment by leeomara** [comment]
Both https://develop-yukon-drupal-10.pantheonsite.io/fr/aeroport-international-erik-nielsen-de-whitehorse and https://develop-yukon-drupal-10.pantheonsite.io/fr/emplois-education now look correct (note the URL for "Employs en éducation" has changed)

![Screenshot 2024-02-26 at 1 01 25 PM](https://github.com/ytgov/yukon-ca/assets/93003/3ec03c37-a4d6-4698-bd97-1bf07c38349f)

![Screenshot 2024-02-26 at 1 01 19 PM](https://github.com/ytgov/yukon-ca/assets/93003/190a2d04-b9cd-4642-92a7-1167219f0db7)

**Comment by leeomara** [comment]
Now looks good on `test`.

- https://test-yukon-drupal-10.pantheonsite.io/fr/transports/aeroport-international-erik-nielsen-de-whitehorse
- https://test-yukon-drupal-10.pantheonsite.io/fr/emplois-education
