### ISSUE TITLE
[P-2] English/French button missing

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#143]
Description:
In Drupal 7 there is an English and French button you can use to jump from the English to the French versions. This is not in Drupal 10. I made a note of it in case this is something FLSD had asked for to improve adding French translations.
![image](https://github.com/ytgov/yukon-ca/assets/123640502/31d20d9e-28db-44ce-a87f-fafee4b4635a)

Task:
Check how it was implemented in D7 and add the same buttons. Or check if it can be replaced by https://www.drupal.org/project/content_language_switcher

Deliverable:
English/French button should be available on the Content Edit page

**Comment by w3creatives** [comment]
We have addressed this issue in a custom module in combination with [Issue#145](https://github.com/ytgov/yukon-ca/issues/143).

**Comment by ew-andrew-sus** [comment]
@w3creatives PR is merged to the 'develop' branch. Complete deployment steps if needed and check the task on [develop multidev env](https://develop-yukon-drupal-10.pantheonsite.io/) please.

**Comment by ew-andrew-sus** [comment]
@w3creatives PR is merged to the 'develop' branch. Complete deployment steps if needed and check the task on [develop multidev env](https://develop-yukon-drupal-10.pantheonsite.io/) please.

**Comment by leeomara** [comment]
Looks good.

![Screenshot 2024-02-26 at 1 09 31 PM](https://github.com/ytgov/yukon-ca/assets/93003/c14ccad6-b090-487d-ad12-462962356acf)

**Comment by leeomara** [comment]
Now looks good on `test`.
