### ISSUE TITLE
[P-2] Opener description

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#144]
**Description:**
In D7 there is a field called Opener description that appears after Metadescription and before Dark SVG upload. This is not in D10.
![image](https://github.com/ytgov/yukon-ca/assets/123640502/da94acea-059b-470c-b588-7692d06c8ae6)

**Task:**
Add "Opener description" field

**Deliverable:**
"Opener description" field should be available on add/edit form

**Comment by ew-andrew-sus** [comment]
@w3creatives PR is merged to the 'develop' branch. Complete deployment steps if needed and check the task on [develop multidev env](https://develop-yukon-drupal-10.pantheonsite.io/) please.

**Comment by leeomara** [comment]
Confirmed that this field is now present.

e.g. https://develop-yukon-drupal-10.pantheonsite.io/node/9980/edit

![Image](https://github.com/ytgov/yukon-ca/assets/93003/16b6628f-c504-49f6-8e60-c944a32e72bc)

**Comment by leeomara** [comment]
Re-opening, to try correcting the workflow for this issue

**Comment by leeomara** [comment]
Tested in `dev`, at https://dev-yukon-drupal-10.pantheonsite.io/node/add/landing_page_level_2. This field is now present.

**Comment by leeomara** [comment]
Now looks good on `test`.
