### ISSUE TITLE
[P-3] Button colours are different

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#145]
**Description:**
In Drupal 7 the button colours stand out. They are all shades of grey in D10. I am not sure if this was out of the box, or custom. It was easier to see in the color version.
![image](https://github.com/ytgov/yukon-ca/assets/123640502/1a48736d-124d-4243-b7d9-4f1303409b70)

**Task:**
Change button colors

**Deliverable:**
Button colors should be the same as on D7

**Comment by w3creatives** [comment]
We have addressed this issue in a custom module in combination with [Issue#143](https://github.com/ytgov/yukon-ca/issues/143).  There is no existing module we could use and that was why;we built a new module to pack the custom features. We will keep using this module to add future modifications.

**Comment by ew-andrew-sus** [comment]
@w3creatives PR is merged to the 'develop' branch. Complete deployment steps if needed and check the task on [develop multidev env](https://develop-yukon-drupal-10.pantheonsite.io/) please.

**Comment by lgontard** [comment]
The buttons are showing up red and green

https://develop-yukon-drupal-10.pantheonsite.io/contact-turkiye-and-syria-support-desk

![Image](https://github.com/ytgov/yukon-ca/assets/157647061/569785c9-f674-4211-afe3-46d06440f194)

![Image](https://github.com/ytgov/yukon-ca/assets/157647061/4fd193ea-7e78-4b98-a1bc-0d4424af0238)

**Comment by leeomara** [comment]
Now looks good on `test`.
