### ISSUE TITLE
[P-2] Light and dark SVG uploads

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#146]
**Description:**
I tested uploading the files and the directories all look correct and I was able to upload. The only thing I wasn’t able to do was to Edit the file in D10. Other than that - it worked. And I am not sure why you would want to edit the file, but I thought I better capture it.
![image](https://github.com/ytgov/yukon-ca/assets/123640502/44d21775-b81a-4454-a5d9-48a11af96a92)
![image](https://github.com/ytgov/yukon-ca/assets/123640502/832e980c-b43d-4855-8ec7-8f2bc55f1716)

**Task:**
Add https://www.drupal.org/project/media_library_edit module and enable it

**Deliverable:**
Content Editor should be able to edit uploaded files

**Comment by ew-andrew-sus** [comment]
@w3creatives PR is merged to the 'develop' branch. Complete deployment steps if needed and check the task on [develop multidev env](https://develop-yukon-drupal-10.pantheonsite.io/) please.

**Comment by w3creatives** [comment]
@leeomara Please test the output on [this link](https://develop-yukon-drupal-10.pantheonsite.io/node/2194/edit?destination=/admin/content%3Ftitle%3D%26type%3Dlanding_page%26status%3DAll%26langcode%3DAll).

**Comment by w3creatives** [comment]
Original issue reported was linked to one content type only. But on D7 it was in use with two types of content.  Revision submitted to match the D7 functionality.

**Comment by ew-andrew-sus** [comment]
@w3creatives PR is merged to the 'develop' branch. Complete deployment steps if needed and check the task on [develop multidev env](https://develop-yukon-drupal-10.pantheonsite.io/) please.

**Comment by leeomara** [comment]
Now looks good on `test`.
