### ISSUE TITLE
[P-1] Title bar styling is missing

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#148]
Description:
URL: https://test-yukon-drupal-10.pantheonsite.io/outdoor-recreation-and-wildlife/yukon-wildlife/yukon-wildlife-species
The title bar styling is missing from the D10 version of the site. The area should be shaded in with the aurora to the right.
![image](https://github.com/ytgov/yukon-ca/assets/123640502/09efe239-13d6-440c-b1da-defa8960cc27)
![image](https://github.com/ytgov/yukon-ca/assets/123640502/89feada6-388a-49b1-ac15-4f21b5481eca)

Task:
Add title bar styling

Deliverable:
Title should be styled

**Comment by ew-andrew-sus** [comment]
@w3creatives PR is merged to the 'develop' branch. Complete deployment steps if needed and check the task on [develop multidev env](https://develop-yukon-drupal-10.pantheonsite.io/) please.

**Comment by leeomara** [comment]
Tested at https://develop-yukon-drupal-10.pantheonsite.io/outdoor-recreation-and-wildlife/yukon-wildlife/yukon-wildlife-species. Looks good there.

<img width="914" alt="Screen Shot 2024-02-12 at 12 48 39 PM" src="https://github.com/ytgov/yukon-ca/assets/93003/22ecd990-bf9d-4acc-a4e1-401d66388dcb">

**Comment by leeomara** [comment]
Now looks good on `test`.
