### ISSUE TITLE
[P-1] Topic Page description heading visible in D10

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#151]
**Description**:
URL: https://test-yukon-drupal-10.pantheonsite.io/outdoor-recreation-and-wildlife/yukon-wildlife/yukon-wildlife-species
In Drupal 10 the Topic page description heading appears and it should not. The content below it should appear - just not the heading. See Drupal 7 screen grab for how it should appear.
![image](https://github.com/ytgov/yukon-ca/assets/123640502/25a50e80-8df8-45ad-b061-bfb33df01afc)
![image](https://github.com/ytgov/yukon-ca/assets/123640502/746410e0-8414-43ec-823f-d37fde236b2c)

**Task:**
Hide "Topic page description" on page view

**Deliverable:**
"Topic page description" shouldn't be visible on page view

**Comment by ew-andrew-sus** [comment]
@w3creatives PR is merged to the 'develop' branch. Complete deployment steps if needed and check the task on [develop multidev env](https://develop-yukon-drupal-10.pantheonsite.io/) please.

**Comment by leeomara** [comment]
Tested at https://develop-yukon-drupal-10.pantheonsite.io/outdoor-recreation-and-wildlife/yukon-wildlife/yukon-wildlife-species

<img width="914" alt="Screen Shot 2024-02-12 at 12 48 39 PM" src="https://github.com/ytgov/yukon-ca/assets/93003/2ba66fd7-da8b-41bd-9455-0d6d52f75069">

**Comment by leeomara** [comment]
Now looks good on `test`.
