### ISSUE TITLE
[P-1] Yukon Editorial Team is viewable in D10

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#152]
**Description:**
URL: https://test-yukon-drupal-10.pantheonsite.io/outdoor-recreation-and-wildlife/yukon-wildlife/yukon-wildlife-species
The Yukon Editorial team field title is visible on the public site in D10. This should not be displayed to the public. This is a field you fill out in the Admin site that shouldn’t be visible.
![image](https://github.com/ytgov/yukon-ca/assets/123640502/58826f03-e285-4769-a85a-6b7b02b62c12)

**Task:**
Hide Yukon Editorial Team field

**Deliverable:**
"Yukon Editorial Team" field shouldn't be visible on the page view

**Comment by ew-andrew-sus** [comment]
@w3creatives PR is merged to the 'develop' branch. Complete deployment steps if needed and check the task on [develop multidev env](https://develop-yukon-drupal-10.pantheonsite.io/) please.

**Comment by leeomara** [comment]
This field is removed from D10. E.g. https://develop-yukon-drupal-10.pantheonsite.io/outdoor-recreation-and-wildlife/yukon-wildlife/yukon-wildlife-species

![Image](https://github.com/ytgov/yukon-ca/assets/93003/15fc3169-21b5-49dc-a7dd-596f3f8cffe1)

**Comment by leeomara** [comment]
Now looks good on `test`.
