### ISSUE TITLE
[P-1] Page formatting of Headings and Items is not correct in D10

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#153]
**Description:**
URL: https://test-yukon-drupal-10.pantheonsite.io/outdoor-recreation-and-wildlife/yukon-wildlife/yukon-wildlife-species
These are the formatting issues I observed. I’ve included screengrabs to highlight the differences. The Drupal 7 screen grab shows how the formatting should look.
The page formatting is off. The content is displayed in two columns for most of the sections on this type of page. It is displaying in one long list in Drupal 10.
There should be a border around the #1 section on these pages, but it is missing from Drupal 10
There should be a horizontal rule separating each of the topic sections and they do not appear in D10.
![image](https://github.com/ytgov/yukon-ca/assets/123640502/d5cfeec5-4da1-457c-9600-b4712cd488c8)
![image](https://github.com/ytgov/yukon-ca/assets/123640502/55063402-8c48-4f09-9e8b-003fd4518a99)

**Task:**
Fix page formatting according to D7 view

**Deliverable:**
Page formatting should be the same as on D7 site

**Comment by leeomara** [comment]
Tested on `develop` and `dev`, looks good. E.g. https://dev-yukon-drupal-10.pantheonsite.io/outdoor-recreation-and-wildlife/yukon-wildlife/yukon-wildlife-species

Not on `test` yet.

**Comment by leeomara** [comment]
Now looks good on `test`.
