### ISSUE TITLE
[P-1] Department field appears in D10

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#154]
**Description:**
URL: https://test-yukon-drupal-10.pantheonsite.io/outdoor-recreation-and-wildlife/yukon-wildlife/yukon-wildlife-species
The Department field is appearing in Drupal 10 and it should only appear in the Admin side.
![image](https://github.com/ytgov/yukon-ca/assets/123640502/a57a39c0-e7c6-4af2-812c-510a919a0131)

**Task:**
Hide "Department" field on page view.

**Deliverable:**
"Department" field shouldn't be visible on page view

**Comment by ew-andrew-sus** [comment]
@w3creatives PR is merged to the 'develop' branch. Complete deployment steps if needed and check the task on [develop multidev env](https://develop-yukon-drupal-10.pantheonsite.io/) please.

**Comment by leeomara** [comment]
Now looks good on `test`.
