### ISSUE TITLE
[P-2] Basic page missing main navigation (left)

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#156]
**Description:**
There is no left navigation

**Task:**
Add left navigation

**Deliverable:**
Left navigation should be on the page view

**Comment by ew-andrew-sus** [comment]
@w3creatives PR is merged to the 'develop' branch. Complete deployment steps if needed and check the task on [develop multidev env](https://develop-yukon-drupal-10.pantheonsite.io/) please.

**Comment by leeomara** [comment]
Tested in `develop` and `dev`, working there. E.g. https://dev-yukon-drupal-10.pantheonsite.io/outdoor-recreation-and-wildlife/camping/find-campground-or-recreation-site

Not present (yet) in `test`.

**Comment by leeomara** [comment]
Now looks good on `test`. https://test-yukon-drupal-10.pantheonsite.io/outdoor-recreation-and-wildlife/camping/find-campground-or-recreation-site
