### ISSUE TITLE
[P-2] Authorship and date should not be shown

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#157]
**Description:**
Authorship and date are visible on the page, but shouldn't

**Task:**
Hide Authorship and date 

**Deliverable:**
Authorship and date should not be shown

**Comment by ew-andrew-sus** [comment]
@w3creatives PR is merged to the 'develop' branch. Complete deployment steps if needed and check the task on [develop multidev env](https://develop-yukon-drupal-10.pantheonsite.io/) please.

**Comment by leeomara** [comment]
Tested at https://develop-yukon-drupal-10.pantheonsite.io/contact-government

<img width="1186" alt="Screen Shot 2024-02-12 at 12 52 49 PM" src="https://github.com/ytgov/yukon-ca/assets/93003/f90a3ca5-98c4-4901-943a-a38867760e28">

**Comment by w3creatives** [comment]
Please review this fix on this URL:

Test:
https://test-yukon-drupal-10.pantheonsite.io/evacuation-alert-village-keno-and-hecla-mine

Develop:
https://develop-yukon-drupal-10.pantheonsite.io/evacuation-alert-village-keno-and-hecla-mine

**Comment by leeomara** [comment]
Now looks good on `test`.
