### ISSUE TITLE
[P-3] No header aurora

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#158]
**Description:**
There is no header aurora on the page viiew

**Task:**
Add header aurora

**Deliverable:**
Header aurora should be in the page view

**Comment by ew-andrew-sus** [comment]
@w3creatives PR is merged to the 'develop' branch. Complete deployment steps if needed and check the task on [develop multidev env](https://develop-yukon-drupal-10.pantheonsite.io/) please.

**Comment by leeomara** [comment]
Tested in develop, looks good. E.g. https://develop-yukon-drupal-10.pantheonsite.io/doing-business/employer-responsibilities/find-minimum-wage-yukon

**Comment by leeomara** [comment]
Now looks good on `test`. https://test-yukon-drupal-10.pantheonsite.io/doing-business/employer-responsibilities/find-minimum-wage-yukon
