### ISSUE TITLE
[P-2] "Full width: off"

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#159]
**Description:**
E.g. https://test-yukon-drupal-10.pantheonsite.io/immigrate-yukon\
near the bottom.

**Task:**
Hide "Full width: off" field

**Deliverable:**
"Full width: off" field shouldn't be visible on the page view

**Comment by ew-andrew-sus** [comment]
@w3creatives PR is merged to the 'develop' branch. Complete deployment steps if needed and check the task on [develop multidev env](https://develop-yukon-drupal-10.pantheonsite.io/) please.

**Comment by leeomara** [comment]
Now looks good on `test`.
