### ISSUE TITLE
[P-3] Bottom aurora missing

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#160]
**Description:**
There is no Bottom aurora  

**Task:**
Add Bottom aurora 

**Deliverable:**
Bottom aurora should be on the page like in D7

**Comment by ew-andrew-sus** [comment]
@w3creatives  Check PR comment please

**Comment by ew-andrew-sus** [comment]
@w3creatives PR is merged to the 'develop' branch. Complete deployment steps if needed and check the task on [develop multidev env](https://develop-yukon-drupal-10.pantheonsite.io/) please.

**Comment by leeomara** [comment]
Tested at https://develop-yukon-drupal-10.pantheonsite.io/immigrate-yukon

<img width="1010" alt="Screen Shot 2024-02-12 at 1 01 26 PM" src="https://github.com/ytgov/yukon-ca/assets/93003/4c477506-c2c5-4972-b6c9-35b726d4259b">

**Comment by leeomara** [comment]
Now looks good on `test`. https://test-yukon-drupal-10.pantheonsite.io/immigrate-yukon
