### ISSUE TITLE
[P-2] Reorder Basic page fields in admin

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#161]
**Description:**
Move “Primary Image” beneath Body input.

Put “Related tasks” and “Primary image” inside collapsable groups.

**Task:**
Fix Basic page fields order

**Deliverable:**
Basic page fields order should be the same as on D7

**Comment by ew-andrew-sus** [comment]
@w3creatives PR is merged to the 'develop' branch. Complete deployment steps if needed and check the task on [develop multidev env](https://develop-yukon-drupal-10.pantheonsite.io/) please.

**Comment by leeomara** [comment]
Tested at https://develop-yukon-drupal-10.pantheonsite.io/node/add/basic_page

<img width="773" alt="Screen Shot 2024-02-12 at 12 56 01 PM" src="https://github.com/ytgov/yukon-ca/assets/93003/f9bedbbf-1a68-4486-8497-15e5c4a3afe6">

**Comment by leeomara** [comment]
Now looks good on `test`.
