### ISSUE TITLE
[P-1] Many "related task" links are broken

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#163]
**Description:**
D10 https://test-yukon-drupal-10.pantheonsite.io/find-campground-or-recreation-site

Most of the “Related tasks” links are to node/NNN, leading to “Page not found” errors.

e.g. “Travel safely in the Yukon wilderness” links to https://test-yukon-drupal-10.pantheonsite.io/node/2034, meanwhile, there does appear to be a node for the link target (https://test-yukon-drupal-10.pantheonsite.io/rules-and-safety-campgrounds-and-recreation-sites, node 36574)

**Task:**
Fix migration to solve broken "related task" links

**Deliverable:**
There shouldn't be any broken "related task" links

**Comment by ew-andrew-sus** [comment]
@w3creatives PR is merged to the 'develop' branch. Complete deployment steps if needed and check the task on [develop multidev env](https://develop-yukon-drupal-10.pantheonsite.io/) please.

**Comment by leeomara** [comment]
Tested in `develop` and `dev`..

e.g. https://dev-yukon-drupal-10.pantheonsite.io/outdoor-recreation-and-wildlife/camping/find-campground-or-recreation-site

Still broken in `test`.

**Comment by leeomara** [comment]
Now looks good on `test`.
