### ISSUE TITLE
[P-2] Authorship and date should not be shown

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#165]
**Description:**
![image](https://github.com/ytgov/yukon-ca/assets/123640502/48bd078a-d872-4eaa-9fe9-46aa3c296554)

**Task:**
Hide Authorship and date

**Deliverable:**
Authorship and date should not be shown

**Comment by ew-andrew-sus** [comment]
@w3creatives PR is merged to the 'develop' branch. Complete deployment steps if needed and check the task on [develop multidev env](https://develop-yukon-drupal-10.pantheonsite.io/) please.

**Comment by leeomara** [comment]
Looks good at https://dev-yukon-drupal-10.pantheonsite.io/en/immigrate-yukon

**Comment by leeomara** [comment]
This is an example of a thing we now want to partially reverse. There's an issue somewhere about adding back the "date modified".

**Comment by leeomara** [comment]
This has been fixed for multistep pages.
