### ISSUE TITLE
[P-2] Breadcrumb is incomplete

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#166]
**Description:**
D10: Home > Find Yukon-specific income tax measures
https://test-yukon-drupal-10.pantheonsite.io/yukon-income-tax
D7: Home > Doing business > Taxation > Find Yukon-specific income tax measures
https://yukon.ca/en/yukon-income-tax
![image](https://github.com/ytgov/yukon-ca/assets/123640502/b42c9389-93db-4acf-aff7-8ac7edf662bc)

**Task:**
Improve Breadcrumb logic to have the same structure as in D7

**Deliverable:**
Breadcrumbs should be like on D7

**Comment by w3creatives** [comment]
Test URL:

https://dev-yukon-drupal-10.pantheonsite.io/en/yukon-income-tax

**Comment by leeomara** [comment]
This looks good in dev, e.g. 

- https://dev-yukon-drupal-10.pantheonsite.io/en/yukon-income-tax
- https://dev-yukon-drupal-10.pantheonsite.io/en/housing-and-property/funding-and-loans/apply-housing-flood-recovery-grant-and-loan
- https://dev-yukon-drupal-10.pantheonsite.io/en/housing-and-property/funding-and-loans/yukon-flood-recovery-program
- https://dev-yukon-drupal-10.pantheonsite.io/en/driving-and-transportation/driver-licensing/get-drivers-licence

**Comment by leeomara** [comment]
Testing in UAT, these 3 work:
- https://yukond10.cms-uat.yukon.ca/en/yukon-income-tax
- https://yukond10.cms-uat.yukon.ca/en/housing-and-property/funding-and-loans/apply-housing-flood-recovery-grant-and-loan
- https://yukond10.cms-uat.yukon.ca/en/driving-and-transportation/driver-licensing/get-drivers-licence

This one, https://yukond10.cms-uat.yukon.ca/node/21841 should be Yukon flood recovery program, but is 404. I believe that's a different issue.
