### ISSUE TITLE
[P-4] English labels on French page

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#167]
**Description:**
D10 https://test-yukon-drupal-10.pantheonsite.io/fr/yukon-impot-revenu
D7 https://yukon.ca/fr/yukon-impot-revenu

Contact
Related
..
Should be

Renseignements
Renseignements connexes
![image](https://github.com/ytgov/yukon-ca/assets/123640502/c739b824-28a4-4f9b-9e38-674b62284aa8)

**Task:**
Add translations

**Deliverable:**
On French language should be French labels

**Comment by ew-andrew-sus** [comment]
@w3creatives PR is merged to the 'develop' branch. Complete deployment steps if needed and check the task on [develop multidev env](https://develop-yukon-drupal-10.pantheonsite.io/) please.

**Comment by w3creatives** [comment]
Test URL:

https://dev-yukon-drupal-10.pantheonsite.io/fr/yukon-impot-revenu

**Comment by leeomara** [comment]
Yep, this looks good on `develop`. Not yet on `test`.

**Comment by leeomara** [comment]
- ✅ Looks good on W3 test server. e.g. https://yukon-new-d10.w3creatives.com/docroot/fr/yukon-impot-revenu
- ❌ "Related" shows in English on YG UAT and dev server. e.g. https://yukond10.cms-uat.yukon.ca/fr/yukon-impot-revenu, https://yukond10.cms-dev.ynet.gov.yk.ca/fr/yukon-impot-revenu

**Comment by leeomara** [comment]
Looks good on UAT.
