### ISSUE TITLE
[P-1] Email address not turned into a link

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#168]
**Description:**
D10:
> Email: fininfo@yukon.ca
https://test-yukon-drupal-10.pantheonsite.io/yukon-income-tax#nav-personal-and-corporate-income-tax
D7:
> Email: [fininfo@yukon.ca](mailto:fininfo@yukon.ca)
https://yukon.ca/en/yukon-income-tax#corporate-income-tax

**Task:**
Fix migration to handle the correct email address migration

**Deliverable:**
Email address should be a link as on D7

**Comment by ew-andrew-sus** [comment]
@w3creatives PR is merged to the 'develop' branch. Complete deployment steps if needed and check the task on [develop multidev env](https://develop-yukon-drupal-10.pantheonsite.io/) please.

**Comment by w3creatives** [comment]
Test URL:

https://dev-yukon-drupal-10.pantheonsite.io/en/yukon-income-tax

**Comment by leeomara** [comment]
Looks good on `dev`.

**Comment by leeomara** [comment]
Related to #185.

**Comment by leeomara** [comment]
Looks good on UAT.
