### ISSUE TITLE
[P-2] Reorder Multi-step fields in admin

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#169]
**Description:**
Reorder to better match public display.

Can we move “Language”, “Social sharing” into the sidebar?

**Task:**
Reorder fields like in D7

**Deliverable:**
Fields should be in the same order as on D7

**Comment by ew-andrew-sus** [comment]
@w3creatives PR is merged to the 'develop' branch. Complete deployment steps if needed and check the task on [develop multidev env](https://develop-yukon-drupal-10.pantheonsite.io/) please.

**Comment by w3creatives** [comment]
Test URL:

https://dev-yukon-drupal-10.pantheonsite.io/en/node/46736/edit

**Comment by leeomara** [comment]
Looks good on `dev`.

**Comment by w3creatives** [comment]
Please re-test and close if possible.
