### ISSUE TITLE
[P-7] News

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#171]
All the activities related to the News development.

- [x] #172
- [x] #173
- [x] #174
- [x] #175
- [x] #176
- [x] #177
- [x] #178
- [x] #179
- [x] #180
- [x] #181
- [x] #182
- [x] #183
- [x] #184
- [x] #185
- [x] #186
- [x] #187
- [x] #188

**Migration dependencies:**

- [ ] Category taxonomy terms
- [ ] Department taxonomy terms
- [ ] News Type taxonomy terms
- [ ] Teams taxonomy terms
- [ ] Images Media Type
- [ ] Chart Paragraph
- [ ] Quick Facts field Paragraph
- [ ] Quotes field Paragraph

**Comment by leeomara** [comment]
These are done.
