### ISSUE TITLE
[P-2] "Category" filter missing

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#172]
**Description:**
URL: https://test-yukon-drupal-10.pantheonsite.io/news

The “Category” options/filter/drop down is missing from D10.
![image](https://github.com/ytgov/yukon-ca/assets/123640502/aa034f05-2f24-460e-9a8c-b4199a0ce765)
![image](https://github.com/ytgov/yukon-ca/assets/123640502/203d5b1e-2fec-4023-8f29-afcdbbe27bf4)

**Task:**
Add a category filter

**Deliverable:**
There should be a category filter on the News page

**Comment by ew-andrew-sus** [comment]
@w3creatives PR is merged to the 'develop' branch. Complete deployment steps if needed and check the task on [develop multidev env](https://develop-yukon-drupal-10.pantheonsite.io/) please.

**Comment by w3creatives** [comment]
Test URL: 

https://dev-yukon-drupal-10.pantheonsite.io/en/news

**Comment by leeomara** [comment]
This looks right on `dev`.

**Comment by leeomara** [comment]
Testing in UAT, at https://yukond10.cms-uat.yukon.ca/en/news, unfortunately the entire sidebar is missing.

**Comment by leeomara** [comment]
This now looks good in UAT. e.g. https://yukond10.cms-uat.yukon.ca/en/news
