### ISSUE TITLE
[P-2] Date filter missing month

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#173]
**Description:**
URL: https://test-yukon-drupal-10.pantheonsite.io/news

The date filter in Drupal 7 allows the user to select the month and year using drop down menus. In Drupal 10, the drop downs are no longer there (not a bad thing), but I only seem to be able to select a year. I tried to type in the date “January 4, 2020” but as soon as I went to type in the comma, it seems like it applied the filter because I got a “No news items found. Try removing or changing a filter.” message.

I am fine with the filtering my year using the new interface, but ECO would need to make the call on that as I am not familiar with how people use this page. To me this is a much cleaner approach than the drop downs.

I’ve included a screen grab of the D10 interface below.

**Task:**
Add month filter

**Deliverable:**
There should be month filter as well on the News page

**Comment by ew-andrew-sus** [comment]
@w3creatives PR is merged to the 'develop' branch. Complete deployment steps if needed and check the task on [develop multidev env](https://develop-yukon-drupal-10.pantheonsite.io/) please.

**Comment by w3creatives** [comment]
Test URL:

https://dev-yukon-drupal-10.pantheonsite.io/en/news

**Comment by leeomara** [comment]
On UAT, the entire sidebar is missing. That's a different issue, but it prevents this one from being evaluated.

**Comment by leeomara** [comment]
This looks good and work on UAT.
