### ISSUE TITLE
[P-2] Filters function differently Apply button?

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#174]
**Description:**
URL: https://test-yukon-drupal-10.pantheonsite.io/news

In Drupal 7, when a person selects a filter, the list of news releases automatically filters. In Drupal 10, it also appears to work this way, but there is also an “Apply” button below the list of filters. (Side note - the button is not styled following our branding)

If Drupal 10 filters as the user manipulates the filter - we do not need that “Apply” button.

**Task:**
Remove Apply button and add auto submit

**Deliverable:**
Filter form should have auto submit without Apply button

**Comment by w3creatives** [comment]
Test URL:

https://dev-yukon-drupal-10.pantheonsite.io/en/news

**Comment by leeomara** [comment]
This looks right on `dev`.

**Comment by leeomara** [comment]
Tested on W3 server

> Fixed, apply button no longer appears under filters, lists filter automatically when you select one.

**Comment by leeomara** [comment]
Looks good on UAT.
