### ISSUE TITLE
[P-2] Department filter options appear different in D10

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#175]
**Description:**
The items in the Department drop down list appear different in Drupal 10.

The “Department” heading appears in the drop down (it should not)
![image](https://github.com/ytgov/yukon-ca/assets/123640502/6ade457e-afd2-4dca-a41c-6894f30ce77c)
![image](https://github.com/ytgov/yukon-ca/assets/123640502/391b1695-1b0b-4b86-8f0a-bc1b00a5546f)

**Task:**
Remove "Department" option

**Deliverable:**
"Department" shouldn't be among the options

**Comment by ew-andrew-sus** [comment]
@w3creatives PR is merged to the 'develop' branch. Complete deployment steps if needed and check the task on [develop multidev env](https://develop-yukon-drupal-10.pantheonsite.io/) please.

**Comment by w3creatives** [comment]
Test URL:

https://dev-yukon-drupal-10.pantheonsite.io/en/news

**Comment by leeomara** [comment]
Looks good in `dev`.

**Comment by leeomara** [comment]
And now it's gone/missing from `dev`. One to re-test on YG UAT I guess.

**Comment by leeomara** [comment]
Looks good on UAT.
