### ISSUE TITLE
[P-2] RSS subscribe missing

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#176]
**Description:**
URL: https://test-yukon-drupal-10.pantheonsite.io/news
There is some extra text appearing on the Drupal 10 site that appears to be pulling from the Admin side.
![image](https://github.com/ytgov/yukon-ca/assets/123640502/7927445a-7499-4bd6-b2c5-9e0986ed1114)
![image](https://github.com/ytgov/yukon-ca/assets/123640502/736a5e95-d925-4797-bd77-a29c073cd10b)

**Task:**
Hide "Full width" field from displaying

**Deliverable:**
"Full width" shouldn't be visible on News page

**Comment by w3creatives** [comment]
We recommend to manually update the RSS page (Use an RSS feed to receive news releases) URL alias to /rss.
