### ISSUE TITLE
[P-2] Pagination formatting is a bit different

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#177]
**Description:**
URL: https://test-yukon-drupal-10.pantheonsite.io/news

The pagination formatting is just a bit different in D10, but I think it looks better.

My only note would be to check with ECO on whether or not the “n” should be in upper or lower case.
![image](https://github.com/ytgov/yukon-ca/assets/123640502/c30cddb5-0b48-4f12-94a0-cb264f56d240)
![image](https://github.com/ytgov/yukon-ca/assets/123640502/737d02c1-3185-4fd1-84a8-df2668fa1078)

**Task:**
Fix pagination styles

**Deliverable:**
Pagination formatting should be the same as on D7

**Comment by ew-andrew-sus** [comment]
@w3creatives PR is merged to the 'develop' branch. Complete deployment steps if needed and check the task on [develop multidev env](https://develop-yukon-drupal-10.pantheonsite.io/) please.

**Comment by w3creatives** [comment]
Test URL:

https://dev-yukon-drupal-10.pantheonsite.io/en/news

**Comment by leeomara** [comment]
This is an example of an issue that I feel we should have evaluated and decided not to change.
