### ISSUE TITLE
[P-3] French news shows English dates

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#178]
**Description:**
URL: https://test-yukon-drupal-10.pantheonsite.io/news
In D10, the dates that appear under the news release title on the listing pages should appear in French, but they do not.
![image](https://github.com/ytgov/yukon-ca/assets/123640502/3811c471-f60b-4082-91e4-39638b2396f1)
![image](https://github.com/ytgov/yukon-ca/assets/123640502/f436b33a-4a6f-436a-8eea-ea037192d7b4)

**Task:**
Translate dates

**Deliverable:**
Dates should be on French in case of FR language is selected

**Comment by ew-andrew-sus** [comment]
@w3creatives PR is merged to the 'develop' branch. Complete deployment steps if needed and check the task on [develop multidev env](https://develop-yukon-drupal-10.pantheonsite.io/) please.

**Comment by w3creatives** [comment]
Test URL:

https://dev-yukon-drupal-10.pantheonsite.io/fr/communiques-de-presse

**Comment by leeomara** [comment]
Looks right on `dev` now.

![Image](https://github.com/ytgov/yukon-ca/assets/93003/e5b6f698-99be-4dec-ad1f-ebef7a9d45bb)

**Comment by leeomara** [comment]
- ✅ This looks good on W3 test server
- ❌ Dates on French news pages (per post, and top-level) are English on the UAT server. e.g. https://yukond10.cms-uat.yukon.ca/fr/communiques-de-presse

**Comment by leeomara** [comment]
❌ Re-testing on W3 Creatives test server shows *some* months are translated, but others are not. Same on YG UAT.

E.g. these are translated: Mai, Juin, Juillet, Août. These are not: February, March, April, September, October, November, December

**Comment by w3creatives** [comment]
Month translations have been done.

Please pull the latest code to deploy UAT env.

**Comment by leeomara** [comment]
Closing this in favour of #645.
