### ISSUE TITLE
[P-3] Missing translations for News filters

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#179]
**Description:**
URL: https://test-yukon-drupal-10.pantheonsite.io/fr/communiques-de-presse

The filter headings do not appear to be translated in Drupal 7 or 10 (started broken) AND
The default text that appears in the Department filter has not been translated. (new with migration) Side note - it should not say “Please”
![image](https://github.com/ytgov/yukon-ca/assets/123640502/223147be-0d11-4c0d-82b9-567050c4ca58)
![image](https://github.com/ytgov/yukon-ca/assets/123640502/3586ab08-1d29-45d0-86c7-bb989d4946c8)

**Task:**
Translate filter field labels

**Deliverable:**
Field labels should be translated to French

**Comment by ew-andrew-sus** [comment]
@w3creatives PR is merged to the 'develop' branch. Complete deployment steps if needed and check the task on [develop multidev env](https://develop-yukon-drupal-10.pantheonsite.io/) please.

**Comment by w3creatives** [comment]
Test URL:

https://dev-yukon-drupal-10.pantheonsite.io/fr/communiques-de-presse

**Comment by leeomara** [comment]
This looks great on `dev`.

**Comment by leeomara** [comment]
- ✅ Filter text looks good on W3 test server
- 🟠 on UAT in French e.g. https://yukond10.cms-uat.yukon.ca/fr/communiques-de-presse
    - ✅ Field labels look right
    - ❌ "Any" option should be "Tout" in French, but is "Any", also "Year" and "Month" are in  English

**Comment by leeomara** [comment]
Note from CL: 

> #179 is fixed, although in the department drop down menu, Yukon Development Corporation is in English on the French side (should be "Société de développement du Yukon") and in the Type d'actualité drop down menu, Arts and events is in English on the French side, (it should be "Arts et activités"). I checked and it was the same in D7.

**Comment by leeomara** [comment]
Looks good in UAT.
