### ISSUE TITLE
[P-2] Aurora graphic should not be on singular news pages

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#180]
**Description:**
URL: https://test-yukon-drupal-10.pantheonsite.io/news/family-mediation-pilot-project-granted-extension
The aurora graphic appears on the top, right of the singular news pages in D10 and it should not. I’ve included a screen grab for D7 so you can see what the pages should look like.
![image](https://github.com/ytgov/yukon-ca/assets/123640502/170e4eeb-7099-47db-9344-e16e70a2d078)
![image](https://github.com/ytgov/yukon-ca/assets/123640502/a612549d-04b0-4986-9637-79464996c503)

**Task:**
Remove Aurora graphic from singular news pages

**Deliverable:**
Aurora graphic should not be on singular news pages

**Comment by ew-andrew-sus** [comment]
@w3creatives PR is merged to the 'develop' branch. Complete deployment steps if needed and check the task on [develop multidev env](https://develop-yukon-drupal-10.pantheonsite.io/) please.

**Comment by w3creatives** [comment]
Test URL:

https://dev-yukon-drupal-10.pantheonsite.io/en/news/family-mediation-pilot-project-granted-extension

**Comment by leeomara** [comment]
Looks good on `dev` site.

![Image](https://github.com/ytgov/yukon-ca/assets/93003/354c018c-5774-46ee-b4ca-2941cbcb21d4)

**Comment by leeomara** [comment]
Looks good on UAT. 

E.g. https://yukond10.cms-uat.yukon.ca/en/news/statement-minister-health-and-social-services-three-year-anniversary-supervised-consumption
