### ISSUE TITLE
[P-2] "Published" date format is different (singular pages)

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#181]
**Description:**
URL: https://test-yukon-drupal-10.pantheonsite.io/news/government-yukon-expands-services-pharmacists-include-prescribing
The formatting of the publish date is different in Drupal 10. It better meets our Style Guide so I think it can stay as-is, but we should check with ECO.
![image](https://github.com/ytgov/yukon-ca/assets/123640502/b6999e55-eedf-45fb-92f2-9113dc2e99c7)
![image](https://github.com/ytgov/yukon-ca/assets/123640502/d64049cb-0792-49ee-95eb-892f8c847acc)

**Task:**
Fix date format

**Deliverable:**
Date format Should be the same as on D7

**Comment by ew-andrew-sus** [comment]
@w3creatives PR is merged to the 'develop' branch. Complete deployment steps if needed and check the task on [develop multidev env](https://develop-yukon-drupal-10.pantheonsite.io/) please.

**Comment by w3creatives** [comment]
Test URL:

https://dev-yukon-drupal-10.pantheonsite.io/en/news/family-mediation-pilot-project-granted-extension

**Comment by leeomara** [comment]
I don't want to change this anymore, so we're going to close this.
