### ISSUE TITLE
[P-2] Related information heading missing colon (singular pages)

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#182]
**Description:**
URL: https://test-yukon-drupal-10.pantheonsite.io/news/government-yukon-expands-services-pharmacists-include-prescribing
The field label/heading for “Related information:” in Drupal 10 is missing the colon that should appear after the number symbol.
Also - the text for the hyperlinks is bold in D7.
![image](https://github.com/ytgov/yukon-ca/assets/123640502/4140abe8-5ea6-4d84-b2d6-4e518834f128)
![image](https://github.com/ytgov/yukon-ca/assets/123640502/433e8659-ece8-4ce4-8a3b-d35251091478)

**Task:**
Add a colon to "Related information" filed label

**Deliverable:**
"Related information" field label should be with the colon

**Comment by ew-andrew-sus** [comment]
@w3creatives PR is merged to the 'develop' branch. Complete deployment steps if needed and check the task on [develop multidev env](https://develop-yukon-drupal-10.pantheonsite.io/) please.

**Comment by w3creatives** [comment]
Test URL:

https://dev-yukon-drupal-10.pantheonsite.io/en/news/government-yukon-expands-services-pharmacists-include-prescribing

**Comment by leeomara** [comment]
Looks fine on `dev`

**Comment by w3creatives** [comment]
Please test:

https://yukon-new-d10.w3creatives.com/docroot/en/news/government-yukon-expands-services-pharmacists-include-prescribing
