### ISSUE TITLE
[P-2] News release number heading missing colon (singular pages)

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#183]
**Description:**
URL: https://test-yukon-drupal-10.pantheonsite.io/news/government-yukon-expands-services-pharmacists-include-prescribing
The field label/heading for “News release #:” in Drupal 10 is missing the colon that should appear after the number symbol.
![image](https://github.com/ytgov/yukon-ca/assets/123640502/dde97619-efac-4831-9f30-833d1625d90b)
![image](https://github.com/ytgov/yukon-ca/assets/123640502/09b90188-2e58-4e81-9f0a-024b1aabf3a5)

**Task:**
Add a colon to "News release #" field label
 
**Deliverable:**
"News release #" field label should be with a colon

**Comment by w3creatives** [comment]
Test URL:

https://dev-yukon-drupal-10.pantheonsite.io/en/news/government-yukon-expands-services-pharmacists-include-prescribing

**Comment by leeomara** [comment]
This looks good on `dev`.

**Comment by w3creatives** [comment]
Please test:

https://yukon-new-d10.w3creatives.com/docroot/en/news/government-yukon-expands-services-pharmacists-include-prescribing

**Comment by leeomara** [comment]
Looks good on UAT.
