### ISSUE TITLE
[P-2] News images formatted wrong

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#184]
**Description:**
D10 https://test-yukon-drupal-10.pantheonsite.io/news/statement-minister-responsible-women-and-gender-equity-directorate-jeanie-mclean-annual
D7 [Statement from the Minister Responsible for the Women and Gender Equity Directorate Jeanie McLean on the annual meeting of the Federal, Provincial and Territorial Ministers Responsible for the Status of Women](https://yukon.ca/en/news/statement-minister-responsible-women-and-gender-equity-directorate-jeanie-mclean-annual-meeting)
Should not list the field label “Primary image”

Image should be righ-aligned with the body copy flowing around it.
![image](https://github.com/ytgov/yukon-ca/assets/123640502/d6f5570c-4a32-4bd9-acee-5d703350d973)

**Task:**
Fix image styling

**Deliverable:**
Image styling should be the same as on D7

**Comment by ew-andrew-sus** [comment]
@w3creatives PR is merged to the 'develop' branch. Complete deployment steps if needed and check the task on [develop multidev env](https://develop-yukon-drupal-10.pantheonsite.io/) please.

**Comment by w3creatives** [comment]
Test URL:

https://dev-yukon-drupal-10.pantheonsite.io/en/news/statement-minister-responsible-women-and-gender-equity-directorate-jeanie-mclean-annual

**Comment by leeomara** [comment]
Looks good on `dev`.

**Comment by w3creatives** [comment]
Please test again:

https://yukon-new-d10.w3creatives.com/docroot/en/news/statement-minister-responsible-women-and-gender-equity-directorate-jeanie-mclean-annual

**Comment by leeomara** [comment]
Looks good on UAT.
