### ISSUE TITLE
[P-2] Media contact formating

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#185]
**Description:**
Title should be “Media contact”, not “Contact”.
Email addresses should be links.
D10 https://test-yukon-drupal-10.pantheonsite.io/news/statement-minister-responsible-women-and-gender-equity-directorate-jeanie-mclean-annual
![image](https://github.com/ytgov/yukon-ca/assets/123640502/9cdb6631-481f-4285-9fb7-f203812adae7)

**Task:**
Show email as links

**Deliverable:**
Email addresses should be links

**Comment by ew-andrew-sus** [comment]
@w3creatives PR is merged to the 'develop' branch. Complete deployment steps if needed and check the task on [develop multidev env](https://develop-yukon-drupal-10.pantheonsite.io/) please.

**Comment by w3creatives** [comment]
Test URL:

https://dev-yukon-drupal-10.pantheonsite.io/en/news/family-mediation-pilot-project-granted-extension

**Comment by leeomara** [comment]
Looks good in `dev`.

![Image](https://github.com/ytgov/yukon-ca/assets/93003/c9694620-ab3e-4d8c-a115-fbe8f51764af)

**Comment by leeomara** [comment]
This looks good on W3 test server.

**Comment by w3creatives** [comment]
Please test it on UAT and close if possible.

**Comment by leeomara** [comment]
Looks good on UAT (HG).
