### ISSUE TITLE
[P-1] News should support multiple Quick facts

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#186]
**Description:**
D7: https://yukon.ca/en/news/government-yukon-invests-new-positions-and-student-supports-strengthen-learning-and-wellbeing
D10: https://test-yukon-drupal-10.pantheonsite.io/news/government-yukon-invests-new-positions-and-student-supports-strengthen-learning-and-wellbeing
_Another example_
D7 [https://yukon.ca/en/node/21916/edit](https://yukon.ca/en/node/21916/edit?destination=admin/content%3Ftype%3Dnews%26status%3DAll%26page%3D2) Forty-one additional campsites now open at the Congdon Creek Campground

**Task:**
Fix Quick facts field migrations

**Deliverable:**
Quick facts field results should be the same as on D7

**Comment by ew-andrew-sus** [comment]
@w3creatives PR is merged to the 'develop' branch. Complete deployment steps if needed and check the task on [develop multidev env](https://develop-yukon-drupal-10.pantheonsite.io/) please.

**Comment by leeomara** [comment]
Multiple Quick facts now show up in `develop`.

e.g. https://develop-yukon-drupal-10.pantheonsite.io/en/news/government-yukon-invests-new-positions-and-student-supports-strengthen-learning-and-wellbeing

The styling doesn't look good. There should probably be more whitespace between items.

![Image](https://github.com/ytgov/yukon-ca/assets/93003/65be7ea9-0830-48ab-80e9-751c472e78cb)

**Comment by leeomara** [comment]
I can now create multiple Quick Fact entries on `dev` (e.g. for a new News item), but the existing/migrated news don't yet have their additional Quick Facts.

Need to re-run the migration there.

**Comment by leeomara** [comment]
News supports multiple quick facts. Looks good on UAT.
