### ISSUE TITLE
[P-1] Related information links are wrong

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#187]
**Description:**
They are like node/123, with references from the original D7 site node ID.
e.g. https://test-yukon-drupal-10.pantheonsite.io/news/forty-one-additional-campsites-now-open-congdon-creek-campground
“Get a campground permit” link is to [/node/203](https://test-yukon-drupal-10.pantheonsite.io/node/203)

**Task:**
Fix Related information links migrations

**Deliverable:**
Related information links should lead to not broken pages

**Comment by w3creatives** [comment]
This issue can be fixed by running migration updates.

**Comment by w3creatives** [comment]
Test URL:

https://dev-yukon-drupal-10.pantheonsite.io/en/news/forty-one-additional-campsites-now-open-congdon-creek-campground

**Comment by leeomara** [comment]
These links now look good on `dev`.

**Comment by leeomara** [comment]
This appears fixed on UAT.
