### ISSUE TITLE
[P-3] French news shows English labels

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#188]
**Description:**
“Published” (in date line)
Quick facts
Contact [ed: should be “Media contact”]
News release #
Related information
Those should be French on French news pages.

**Task:**
Translate labels

**Deliverable:**
There shouldn't be not translated labels on French language

**Comment by ew-andrew-sus** [comment]
@w3creatives PR is merged to the 'develop' branch. Complete deployment steps if needed and check the task on [develop multidev env](https://develop-yukon-drupal-10.pantheonsite.io/) please.

**Comment by w3creatives** [comment]
Test URL:

https://dev-yukon-drupal-10.pantheonsite.io/en/news/family-mediation-pilot-project-granted-extension

**Comment by leeomara** [comment]
On `dev`, the labels are all French now (excellent), though some of the colon are doubled?

Possibly an unintended consequence of
- https://github.com/ytgov/yukon-ca/issues/183
- https://github.com/ytgov/yukon-ca/issues/182

![Image](https://github.com/ytgov/yukon-ca/assets/93003/d83d70f8-87c5-4a8a-ac75-40dedbae075f)

**Comment by leeomara** [comment]
- ✅ nearly all text labels are now French, on UAT
- ❌ “Published” (in date line) is always English (on W3 and UAT). E.g. https://yukond10.cms-uat.yukon.ca/fr/news/prolongation-du-projet-pilote-de-mediation-familiale
- 🟠 Colons beside "Numéro du communiqué: :" and "Articles connexes::" are doubled.  Possibly an unintended consequence of #183 or #182

**Comment by leeomara** [comment]
This looks good on W3 Creatives server.

**Comment by leeomara** [comment]
❌ “Published” (in date line) is always English (on W3 and UAT)

**Comment by w3creatives** [comment]
Please review:

https://yukon-new-d10.w3creatives.com/docroot/fr/news/prolongation-du-projet-pilote-de-mediation-familiale

**Comment by leeomara** [comment]
- ✅ "Publié" looks good on W3 server

Colons issue moved over to new issue (priority:low) for tracking separately from translation.

**Comment by leeomara** [comment]
Looks good on UAT.
