### ISSUE TITLE
[P-3] Documents top-level filter label is French

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#190]
**Description:**
In English, the filter section title should be
_Filter by_
Instead the section label is
_Filtrer par_
https://test-yukon-drupal-10.pantheonsite.io/documents
![image](https://github.com/ytgov/yukon-ca/assets/123640502/3f4bdc73-73eb-45ad-a142-4c5facd1531a)

**Task:**
Translate "Filter by"

**Deliverable:**
"Filter by" should be "Filtrer par" on French language

**Comment by leeomara** [comment]
This looks good on UAT.
