### ISSUE TITLE
[P-2] Documents search is much more restrictive

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#191]
**Description:**
Is this because D10 is not using Search API or not scanning document content?
Compare a search of “evaluation” in the “Education department.
D7: 27 results https://yukon.ca/en/documents?field_department_term_tid_i18n=26&keys=evaluation
D10: 6 results https://test-yukon-drupal-10.pantheonsite.io/documents?combine=evaluation&field_department_term_target_id=5

**Task:**
Fix documents search

**Deliverable:**
D10 search should show the same results as D7

RM: https://rm.ewdev.ca/issues/64784

**Comment by adrianrylski** [comment]
This is ready for testing: 

**Link to test:**
D7
- EN: https://yukon.ca/en/documents?field_department_term_tid_i18n=26&keys=evaluation
- FR: https://yukon.ca/fr/documents?field_department_term_tid_i18n=26&keys=evaluation
D10
- EN: https://dev-64782-yukon-drupal-10.pantheonsite.io/en/documents?query=evaluation&department=367
- FR: https://dev-64782-yukon-drupal-10.pantheonsite.io/fr/documents?query=evaluation&department=367

@leeomara please note that implementations are different (D7 does not use Solr) Please provide initial feedback and we will continue working on this feature

**Comment by leeomara** [comment]
These results looks totally reasonable to me.

**Comment by leeomara** [comment]
This looks good on UAT.
