### ISSUE TITLE
[P-1] No way to download Document file

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#192]
**Description:**
Beneath the “Document description”, there should be a link to “Download”
Compare:
D7 https://yukon.ca/en/questionnaire-teacher-evaluation
D10 https://test-yukon-drupal-10.pantheonsite.io/questionnaire-teacher-evaluation
![image](https://github.com/ytgov/yukon-ca/assets/123640502/bb679a9a-6376-4147-bc32-17d816611af0)

**Task:**
Fix documents migration

**Deliverable:**
There should be a download link to download "Document file"

**Comment by leeomara** [comment]
This looks good on UAT.
