### ISSUE TITLE
[P-2] Document size type and page count layout jumbled

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#193]
**Description:**
_Should be_
Size: 72.92 KB
File Type: PDF
Number of pages: 2

_But is instead_
Size File Type Number of pages 2

D7: https://yukon.ca/en/questionnaire-teacher-evaluation
D10: https://test-yukon-drupal-10.pantheonsite.io/questionnaire-teacher-evaluation
![image](https://github.com/ytgov/yukon-ca/assets/123640502/b57eafd8-65a1-469c-973b-fb222bd7bd80)

**Task:**
Style Document size type and page count

**Deliverable:**
Document size type and page count should be the same as on D7

**Comment by leeomara** [comment]
This looks good on UAT.
