### ISSUE TITLE
[P-2] Document size and type values are missing

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#194]
**Description:**
_Should be_
Size: 72.92 KB
File Type: PDF

_But is instead_
Size File Type

D7: https://yukon.ca/en/questionnaire-teacher-evaluation
D10: https://test-yukon-drupal-10.pantheonsite.io/questionnaire-teacher-evaluation
![image](https://github.com/ytgov/yukon-ca/assets/123640502/3d4a56de-6781-477f-9fc5-8a5037e34804)

**Task:**
Add Document size and type values

**Deliverable:**
Size and type values should be visible like on D7

**Comment by leeomara** [comment]
This looks good on UAT.
