### ISSUE TITLE
[P-3] French documents have English labels

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#195]
**Description:**
_Should be:_
Nom
Catégorie
Dernière mise à jour
Taille
Type de fichier
Nombre de pages
Description

Example:
D7: https://yukon.ca/fr/yukon-wildland-fire-activity-report
D10: https://test-yukon-drupal-10.pantheonsite.io/fr/bulletin-dinformation-sur-les-feux-de-foret
![image](https://github.com/ytgov/yukon-ca/assets/123640502/7ac1b9f2-a924-47d2-8134-eb921282dba2)

**Task:**
Translate labels

**Deliverable:**
There shouldn't be untranslated labels on French language

**Comment by leeomara** [comment]
- ✅ Looks good on W3 test server
- ❌ Still wrong on UAT and YG dev.

**Comment by leeomara** [comment]
Looks good on UAT.
