### ISSUE TITLE
[P-2] "Documents for non-Yukon-Branded Campaigns" should not have Yukon.ca style

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#197]
**Description:**
Documents that have the “Document for non-Yukon-branded campaigns” checkbox should not have the Yukon branding applied. E.g. the [Yukon.ca](http://yukon.ca/) logo in the top should not be visible.

Example: Yukon Recycling Summit agenda
D7: https://yukon.ca/en/yukon-recycling-summit-agenda
D10: https://test-yukon-drupal-10.pantheonsite.io/yukon-recycling-summit-agenda

**Task:**
Do not apply Yukon branding for Documents that have the “Document for non-Yukon-branded campaigns” checkbox

**Deliverable:**
Documents that have the “Document for non-Yukon-branded campaigns” checkbox should not have the Yukon branding applied.

Example of this on Yukon.ca https://yukon.ca/en/sart-mission-and-principles

**Comment by leeomara** [comment]
This is still a problem on W3 test server, YG UAT and dev

**Comment by leeomara** [comment]
We are not entirely clear on what the current D7 behaviour is.

**Comment by leeomara** [comment]
Not fixed. YG wordmark still shows up at top of page.

**Comment by w3creatives** [comment]
Please review again.
