### ISSUE TITLE
[P-12] Campaign Page

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#198]
All the activities related to the homepage development.

- [x] #199
- [x] #200
- [x] #201
- [x] #202
- [x] #203
- [x] #204
- [x] #205
- [x] #206
- [x] #207
- [x] #208

**Migration dependencies:**

- [ ] Images Media Type
- [ ] Department taxonomy terms
- [ ] Teams taxonomy terms
- [ ] Text Paragraph
- [ ] Text Unformatted Paragraph
- [ ] Text and Image Paragraph
- [ ] Video Paragraph
- [ ] Video and Text Paragraph
- [ ] Call to action Paragraph
- [ ] Quote Paragraph
- [ ] Chart Paragraph
- [ ] Social network Paragraph
- [ ] Navigation jump point Paragraph

**Comment by leeomara** [comment]
All of these issues are done.
