### ISSUE TITLE
[P-3] Campaign pages not themed

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#199]
**Description:**
Campaign pages should be heavily styled. The current test site is just stock Drupal field: value.

D10 https://test-yukon-drupal-10.pantheonsite.io/fox-lake-local-area-planning
D7 https://yukon.ca/fox-lake-local-area-planning
Example from D7 attached.
![image](https://github.com/ytgov/yukon-ca/assets/123640502/1fb2519f-91c3-46a4-a876-72d97ee5ab01)

**Task:**
Add styling for Campaign pages

**Deliverable:**
Campaign pages styling should be the same as on D7

**Comment by leeomara** [comment]
Other than #618, this looks good.
