### ISSUE TITLE
[P-1] French and English mixed

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#200]
**Description:**
Migrated campaign pages mix French and English content.
https://test-yukon-drupal-10.pantheonsite.io/fox-lake-local-area-planning

Note that the French page also has this issue, though the title is French
https://test-yukon-drupal-10.pantheonsite.io/fr/plan-damenagement-local-pour-la-region-du-lac-fox

**Task:**
Fix migration language issue.

**Deliverable:**
There shouldn't be French and English mixed content

**Comment by leeomara** [comment]
This looks good on UAT.

**Comment by leeomara** [comment]
The call-to-action block has English content on the French page

> The planning area is 525 square kilometres in size and is located approximately 40 kilometres north of Whitehorse. It begins at kilometre 226 of the Klondike Highway and extends to kilometre 266, just north of Little Fox Lake.

https://yukon-new-d10.w3creatives.com/docroot/fr/plan-damenagement-local-pour-la-region-du-lac-fox

**Comment by w3creatives** [comment]
Please check aagin and close if its done.

**Comment by leeomara** [comment]
That particular call-to-action block is also wrong in D7.

https://yukon.ca/fr/plan-damenagement-local-pour-la-region-du-lac-fox

![Screenshot 2024-10-29 at 8 44 31 AM](https://github.com/user-attachments/assets/bfbe82f0-15ad-4832-9dea-6dbe0358e9b5)
