### ISSUE TITLE
[P-1] Links in Campaign page broken (look like UUID)

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#201]
**Description:**
E.g https://test-yukon-drupal-10.pantheonsite.io/west-dawson-and-sunnydale-area-development-regulations
Link text “Description du règlement de zonage” links to /83f85702-b3be-4813-91ed-d638d737c1af]
Some of the other links work, but many do not.

**Task:**
Fix broken migration links

**Deliverable:**
There shouldn't be broken links with UUID

**Comment by leeomara** [comment]
Retesting using the `master` branch (at cb497b634), those links are updated, but they now look like this:

```html
<a href="Migration: yukon_migrate_text UUID: 83f85702-b3be-4813-91ed-d638d737c1af RowNid:  
RowType:   SourceNid: 12769 DestNid not found">Description du règlement de zonage</a>
```

I'm not sure this is an improvement.

**Comment by leeomara** [comment]
❌ This remains an issue on W3 server, UAT and dev.

On those, the links under "Download related documents " are now:
- "Zoning outline"  `https://node/12769`
- "Options for managing visitor use of bed and breakfasts and guest cabins" => `https://node/12771`
- "Meeting summary" `https://node/12768`

On D7 those links work. e.g. https://yukon.ca/west-dawson-and-sunnydale-area-development-regulations

**Comment by w3creatives** [comment]
Please review:

https://yukon-new-d10.w3creatives.com/docroot/en/west-dawson-and-sunnydale-area-development-regulations

**Comment by leeomara** [comment]
The "related documents" links now all work on W3 server.

**Comment by leeomara** [comment]
Looks good on UAT.
