### ISSUE TITLE
[P-1] "Display copyright notice" migrated wrong

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#202]
**Description:**
Expected this field unchecked, but was checked.
[x] Display copyright notice (all languages)
[https://test-yukon-drupal-10.pantheonsite.io/node/32982/edit](https://test-yukon-drupal-10.pantheonsite.io/node/32982/edit?destination=/admin/content%3Ftitle%3Dassault%26type%3Dcampaign_page%26status%3DAll%26langcode%3DAll)

**Task:**
Fix migration for "Display copyright notice (all languages)"

**Deliverable:**
Field "Display copyright notice (all languages)" should have the same value as on D7

**Comment by w3creatives** [comment]
Please review:

https://yukon-new-d10.w3creatives.com/docroot/en/node/12298/edit

**Comment by leeomara** [comment]
This field on UAT now matches prod.
