### ISSUE TITLE
[P-1] CSS class on links lost

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#203]
**Description:**
Might be related to migration, or to the text format.

Example, expected:
`<a class="button-primary btn btn-primary" href="https://www.google.com/" style="color:#fff;" ...`
Actual:
`<a href="https://www.google.com/">Quittez rapidement le site</a>`

D10 https://test-yukon-drupal-10.pantheonsite.io/node/32982/edit

**Task:**
Improve migration logic to fix removing classes for links

**Deliverable:**
Links should have the same styles as on D7

**Comment by w3creatives** [comment]
Please review

https://yukon-new-d10.w3creatives.com/docroot/fr/sartyukon/accueil

**Comment by leeomara** [comment]
Looks good on W3 server (SG)

**Comment by leeomara** [comment]
Looks good on UAT.
