### ISSUE TITLE
[P-1] Embedded video missing

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#204]
**Description:**
D10: https://test-yukon-drupal-10.pantheonsite.io/sartyukon/home
D7: https://yukon.ca/fr/sartyukon/accueil
![image](https://github.com/ytgov/yukon-ca/assets/123640502/30492ad5-9298-4059-9d04-d1072cb48f7d)

**Task:**
Fix migration to support embedded videos

**Deliverable:**
Embedded video should be migrated as well

Jira: https://ygdevops.atlassian.net/browse/DMTPD3-30 "cannot embed video"

**Comment by leeomara** [comment]
Related to https://github.com/ytgov/yukon-ca/issues/371

**Comment by leeomara** [comment]
This looks good on UAT.
