### ISSUE TITLE
[P-1] Some Child Campaign Pages missing

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#205]
**Description:**

SART should have ([D7](https://yukon.ca/fr/sartyukon/accueil))
Accueil
Obtenir de l’aide
Vous vous demandez quoi faire?
Signalements
Aide aux jeunes victimes de violences sexuelles
Fournisseurs de services

In [D10](https://test-yukon-drupal-10.pantheonsite.io/sartyukon/home), it has only:
Get support

**Task:**
Fix migration to solve missing child Campaign Pages

**Deliverable:**
Child Campaign Pages should be the same as on D7

**Comment by leeomara** [comment]
- ✅ child pages data is migrated (links from "home" visible in admin, content exists, children have Parent Campaign Page value set)
- ❌ navigation within campaign site is missing

**Comment by lgontard** [comment]
Adding link https://yukon-new-d10.w3creatives.com/docroot/en/sartyukon/home

**Comment by w3creatives** [comment]
Please review:

https://yukon-new-d10.w3creatives.com/docroot/en/sartyukon/home

**Comment by w3creatives** [comment]
Please review:

https://yukon-new-d10.w3creatives.com/docroot/en/sartyukon/home

**Comment by lgontard** [comment]
@lee @w3creatives This appears to be working as it should now.

**Comment by leeomara** [comment]
Looks good in UAT.
