### ISSUE TITLE
[P-2] Site crash loading Campaign page

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#206]
**Description:**
D10: https://test-yukon-drupal-10.pantheonsite.io/exploring-yukon-history
D7: https://yukon.ca/en/exploring-yukon-history
Another crashing page:

D10: https://test-yukon-drupal-10.pantheonsite.io/creative-and-cultural-industries-strategy
D7 equivalent: https://yukon.ca/en/creative-and-cultural-industries-strategy

**Task:**
Fix the error

**Deliverable:**
The site shouldn't crash on opening Campaign page

**Comment by leeomara** [comment]
This looks good on UAT.
