### ISSUE TITLE
[P-1] "Display section title" cannot be required when radio

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#207]
**Description:**
For some Campaign paragraph type, the “Display section title” widget is a radio button (see other Trello card).
Some have this field as “required”, making it impossible to select “no, I don’t want to show the title”.
E.g. Text and image paragraph type.
![image](https://github.com/ytgov/yukon-ca/assets/123640502/3af1dcce-71d3-414b-994e-5d90d7c733d7)

**Task:**
Made "Display section title" not required

**Deliverable:**
"Display section title" shouldn't  be required

**Comment by w3creatives** [comment]
Please review:

https://yukon-new-d10.w3creatives.com/docroot/en/node/12298/edit

**Comment by leeomara** [comment]
This looks good on UAT.
