### ISSUE TITLE
[P-1] Campaign intro "Source credit" empty

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#208]
**Description:**
Campaign intro "Source credit" empty

**Task:**
Fix migration "Source credit"

**Deliverable:**
Campaign intro "Source credit" shouldn't be empty

**Comment by leeomara** [comment]
- ✅ content appears migrated correctly. e.g. /en/node/16587/edit
- ❌ no source credit (i) visible on public view.

<img width="403" alt="Screen Shot 2024-10-08 at 9 06 40 PM" src="https://github.com/user-attachments/assets/75af9010-4dc2-4b76-acbe-c8ba40f1e1e7">

**Comment by w3creatives** [comment]
Please review this link:

https://yukon-new-d10.w3creatives.com/docroot/en/node/16587/

**Comment by leeomara** [comment]
Looks good on W3 server

**Comment by leeomara** [comment]
Looks good on UAT.
