### ISSUE TITLE
[P-2] Missing horizontal bar

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#210]
**Description:**
The horizontal bar/divider is missing beneath secondary content title.
_Steps to recreate_
Visit any land page that has secondary content. e.g. https://test-yukon-drupal-10.pantheonsite.io/immigration "Apply to immigrate to Yukon"

_URL/links:_
- D10: https://test-yukon-drupal-10.pantheonsite.io/immigration
- D7: https://yukon.ca/en/immigration

**Task:**
Add divider to Secondary Content title

**Deliverable:**
The secondary Content title should have a divider

**_TASK IS BLOCKED BY_** #209

**Comment by ew-andrew-sus** [comment]
@w3creatives PR is merged to the 'develop' branch. Complete deployment steps if needed and check the task on [develop multidev env](https://develop-yukon-drupal-10.pantheonsite.io/) please.

**Comment by ew-andrew-sus** [comment]
@w3creatives PR is merged to the 'develop' branch. Complete deployment steps if needed and check the task on [develop multidev env](https://develop-yukon-drupal-10.pantheonsite.io/) please.

**Comment by leeomara** [comment]
@w3creatives I'm not seeing secondary content (e.g. at https://develop-yukon-drupal-10.pantheonsite.io/immigration compared with https://yukon.ca/en/immigration. I suspect this is because of #209

**Comment by w3creatives** [comment]
@leeomara Content got fixed after re-running the migration.  But title translation to French needs to be done. We will open a new issue for that.

**Comment by leeomara** [comment]
I now see the horizontal rules beneath the secondary content titles. E.g. at https://develop-yukon-drupal-10.pantheonsite.io/immigration

![Screenshot 2024-02-20 at 8 41 08 AM](https://github.com/ytgov/yukon-ca/assets/93003/54a4aa41-7049-4d08-af07-c0589765ed37)

**Comment by leeomara** [comment]
Now looks good on `test`.
