### ISSUE TITLE
[P-2] Page title vertical alignment

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#211]
**Description:**
The vertical spacing of the page title is uneven. The word "Employment" should be vertically entered within the grey bar, as the icon is.
_Steps to recreate_
Visit a landing page. e.g. https://test-yukon-drupal-10.pantheonsite.io/employment
_URL/links:_
D10 URL: https://test-yukon-drupal-10.pantheonsite.io/employment
D7 URL: https://yukon.ca/en/employment
![image](https://github.com/ytgov/yukon-ca/assets/123640502/0de5aeb6-fb40-4046-9a51-8007ee14cdb6)

**Task:**
Add a section with needed styling

**Deliverable:**
There should be styled word "Employment"

**Comment by ew-andrew-sus** [comment]
@w3creatives PR is merged to the 'develop' branch. Complete deployment steps if needed and check the task on [develop multidev env](https://develop-yukon-drupal-10.pantheonsite.io/) please.

**Comment by leeomara** [comment]
Tested at https://develop-yukon-drupal-10.pantheonsite.io/employment this looks good.

![Screenshot 2024-02-02 at 2 00 14 PM](https://github.com/ytgov/yukon-ca/assets/93003/16d6a279-60a7-4971-9fb9-5812768e7f21)

**Comment by leeomara** [comment]
Now looks good on `test`. https://test-yukon-drupal-10.pantheonsite.io/employment
