### ISSUE TITLE
[P-13] Public Engagements

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#212]
All the activities related to the homepage development.
- [x] #213
- [x] #214
- [x] #215 
- [x] #216 
- [x] #217
- [x] #218 
- [x] #384 

**Migration dependencies:**
- [ ] Engagement Categories taxonomy terms
- [ ] Teams taxonomy terms
- [ ] Department taxonomy terms

**Comment by leeomara** [comment]
All of these are done.
