### ISSUE TITLE
[P-4] Individual engagement page not themed

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#214]
**Description:**
No status header. e.g.
This engagement is now closed.
It ran from 2020-01-06 to 2020-02-16.
Check below for where to find results.
Depending on engagement status, different fields should be displayed, in different order.
Sidebar should include “Other public engagements”

**Task:**
Add styling to Individual engagement page

**Deliverable:**
The individual engagement page should be themed as D7 page

**Comment by leeomara** [comment]
This looks good on UAT.
