### ISSUE TITLE
[P-5] French Engagement page shows English labels

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#217]
**Description:**
French Engagement page shows English labels

**Task:**
Add French translation as on D7

**Deliverable:**
There shouldn't be English labels on French page

**Comment by leeomara** [comment]
- ✅ W3 test site shows all headers in French
- 🟠 UAT site shows "What was this engagement about?" in English

**Comment by leeomara** [comment]
UAT now shows French labels everywhere.
