### ISSUE TITLE
[P-3] Engagement start and end dates should be date only (no time)

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#218]
**Description:**
 Engagement start and end dates have time, but should have only date

**Task:**
Remove time for Engagement start and end dates

**Deliverable:**
Engagement start and end dates should be date only (no time)

**Comment by leeomara** [comment]
The "Start date" and "End date" fields both still collect a time part.

<img width="798" alt="Screen Shot 2024-10-08 at 9 20 57 PM" src="https://github.com/user-attachments/assets/34815813-1c52-4f17-8d01-42ced3817b59">

**Comment by w3creatives** [comment]
Please review:

https://yukon-new-d10.w3creatives.com/docroot/en/node/24470/edit

**Comment by leeomara** [comment]
Looks good on UAT.
