### ISSUE TITLE
[P-14] Event

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#219]
All the activities related to the Event development.

- [x] #220 
- [x] #221 
- [x] #222 
- [x] #223 
- [x] #224 
- [x] #225 
- [x] #226 
- [x] #227 
- [x] #228 
- [x] #229 
- [x] #230 

**Migration dependencies:**

- [ ] Teams taxonomy terms
- [ ] Department taxonomy terms
- [ ] Community taxonomy terms
- [ ] Category taxonomy terms
- [ ] Places Nodes
- [ ] Images Media Type

**Comment by leeomara** [comment]
All of these are done.
