### ISSUE TITLE
[P-1] Top-level events missing top section

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#220]
**Description:**
Reviewed at https://test-yukon-drupal-10.pantheonsite.io/en/arts-and-culture/events
Missing intro.
Instead shows:
The page you requested does not exist.

**Task:**
Fix top section

**Deliverable:**
Top section should be the same as on D7

**Comment by leeomara** [comment]
@lgontard Do you know if we're supposed to have both https://yukon.ca/en/arts-and-culture/events and https://yukon.ca/en/events ?

**Comment by lgontard** [comment]
The Events appear as a subheader on the Arts and culture Landing page. It's the only search that's listed on a LP. It's a cleaner URL without the Landing page and I don't think we need https://yukon.ca/en/arts-and-culture/events

**Comment by w3creatives** [comment]
Both URLs exists.  We should not delete the unwanted one and instead create a redirect.  Do you want to create a Drupal based redirect?

**Comment by leeomara** [comment]
Let's stay away from Drupal redirects for the time being. YG will create a redirect at the load balancer, to send users from `/en/arts-and-culture/events` to `/en/events`.

**Comment by leeomara** [comment]
I've created the redirect from `/en/arts-and-culture/events` to `/en/events

**Comment by leeomara** [comment]
Looks good on UAT (CL).
