### ISSUE TITLE
[P-2] Top-level events page events not styled

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#221]
**Description:**
Parts are missing, formatting is poor/not done.

Compare: https://test-yukon-drupal-10.pantheonsite.io/en/arts-and-culture/events (D10) with https://yukon.ca/en/arts-and-culture/events (D7)

Event titles should be large
should be space between each event
icons are missing
dates are formatted poorly

**Task:**
Add styling to Events page

**Deliverable:**
Events page should be styled the same as on D7

**Comment by leeomara** [comment]
Styled top-level Events page looks good on UAT.
