### ISSUE TITLE
[P-2] Events page filter functionality

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#222]
**Description:**
Starting from https://test-yukon-drupal-10.pantheonsite.io/en/arts-and-culture/events

Choose a filter, hit apply. Should limit which events are displayed to match filter. Instead, sends user to the homepage.

**Task:**
Fix filter behavior

**Deliverable:**
On clicking the apply button events should be filtered

**Comment by leeomara** [comment]
- ✅ using the filter does filter content and doesn't take you to the homepage
- ❌ "Department" filter lists Editorial team, not department

**Comment by w3creatives** [comment]
This is fixed. Please check again.

**Comment by leeomara** [comment]
This looks good on W3 Creatives server.

Let me know when code for this lands that I can evaluate on UAT.

**Comment by w3creatives** [comment]
Please review:

https://yukon.ca/en/arts-and-culture/events
https://yukon-new-d10.w3creatives.com/docroot/en/arts-and-culture/events

You can ignore the media content on D10.

**Comment by leeomara** [comment]
Looks good on UAT.
