### ISSUE TITLE
[P-1] Top-level events page doesn't exist in French

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#223]
**Description:**
Top-level events page doesn't exist in French

**Task:**
Fix migration to have migrated top-level events page in French

**Deliverable:**
Top-level events page should exist in French as well

**Comment by leeomara** [comment]
- ✅ Top-level Events page exists in French
- ❌ Content on French top-level page is a mix of English and French

<img width="438" alt="Screen Shot 2024-10-08 at 9 31 02 PM" src="https://github.com/user-attachments/assets/b95d05ca-0799-42c6-9da9-6c88e56c2bf2">

**Comment by w3creatives** [comment]
This is linked to - #658

**Comment by leeomara** [comment]
Looks good in UAT.
