### ISSUE TITLE
[P-2] Event details formatted poorly

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#225]
**Description:**
Labels do not align with values.
Date values displayed incorrectly.
Contact info should be linked.

D10: https://test-yukon-drupal-10.pantheonsite.io/events/sake-children-workshop-march-2024
D7: https://yukon.ca/en/events/sake-children-workshop-march-2024?date=2024-03-12

_Date formatting should look like:_
Date: March 12, 2024
Time: 5:30 pm to 8:30 pm
_Not_
March 12, 2024 5:30 pm toMarch 12, 2024 8:30 pm
Date
![image](https://github.com/ytgov/yukon-ca/assets/123640502/83517555-7767-47ee-96ac-3e37f81ce1c6)

**Task:**
Fix Event details formatting

**Deliverable:**
Event details formatting should be the same as on D7 site

**Comment by w3creatives** [comment]
Please login to W3 test server and review these links:

https://yukon-new-d10.w3creatives.com/docroot/en/node/3374 
https://yukon-new-d7.w3creatives.com/fr/events/diaporama-sur-les-immeubles-militaires-datant-de-la-seconde-guerre-mondiale

**Comment by leeomara** [comment]
Looks good on UAT (SG).
