### ISSUE TITLE
[P-2] Event "website" link should display as a button

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#226]
**Description:**
The website text, e.g. “A healthier tomorrow starts today” should be styled like a button, not a text link.

D10 https://test-yukon-drupal-10.pantheonsite.io/events/pacing-your-way-wellness-prioritizing-energy-management-1
D7 https://yukon.ca/en/events/pacing-your-way-wellness-prioritizing-energy-management-1?date=2023-09-13

**Task:**
Fix link styling

**Deliverable:**
The website text, e.g. “A healthier tomorrow starts today” should be styled like a button

**Comment by w3creatives** [comment]
Please check:

https://yukon-new-d10.w3creatives.com/docroot/en/events/pacing-your-way-wellness-prioritizing-energy-management-1?date=2023-09-13

**Comment by leeomara** [comment]
Looks good in UAT.
