### ISSUE TITLE
[P-1] Event contact email missing

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#227]
**Description:**
D10 https://test-yukon-drupal-10.pantheonsite.io/node/33844/edit
Communication skills after separation or divorce workshop September 2023
D7 https://yukon.ca/en/events/pacing-your-way-wellness-prioritizing-energy-management-1?date=2023-09-13
The contact, “Chronic Conditions Support Program (CCSP)”, should be a link to email [ccsp@yukon.ca](mailto:ccsp@yukon.ca). In D10, the email value is empty.

**Task:**
Fix email migration for "Contact email" field

**Deliverable:**
"Contact email" field should be migrated

**Comment by leeomara** [comment]
This works right on UAT.
