### ISSUE TITLE
[P-1] Unpublished Events imported as Published

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#228]
**Description:**
Pacing your Way to Wellness: Prioritizing Energy Management

D10 3 published
D7 1 published, 2 unpublished

**Task:**
Fix Event publish field migration issue

**Deliverable:**
The publish field should be migrated and Events statuses on D7 and D10 should be the same

**Comment by leeomara** [comment]
This is still an issue, on W3 test site, as well as YG UAT and dev.

**Comment by w3creatives** [comment]
This is fixed:

https://yukon-new-d10.w3creatives.com/docroot/en/events/carmacks-rocks-geology-open-house

**Comment by leeomara** [comment]
This now looks good on UAT.

Archived content is imported with the (single/last) revision as Archived (unpublished).
