### ISSUE TITLE
[P-3] Event dates display English on French page

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#229]
**Description:**
e.g. https://test-yukon-drupal-10.pantheonsite.io/fr/events/suivre-son-rythme-vers-le-bien-etre-prioriser-la-gestion-de-lenergie-0

_Looks like:_
September 13, 2023 12:00 pm to1:00 pm
Date:

_Should look like:_
Date: 13 septembre 2023
Heure: 12 h à 13 h

**Task:**
Add dates translations

**Deliverable:**
Dates should be translated on French page

**Comment by leeomara** [comment]
This is still an issue.

This possibly relates to #465

**Comment by leeomara** [comment]
❌ tested on W3 Creatives test site.

**Comment by w3creatives** [comment]
Review link:

https://yukon-new-d10.w3creatives.com/docroot/fr/events/suivre-son-rythme-vers-le-bien-etre-prioriser-la-gestion-de-lenergie-0

**Comment by leeomara** [comment]
Looks good on W3 server.

**Comment by leeomara** [comment]
Looks good on UAT.
