### ISSUE TITLE
[P-3] Event labels not translated

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#230]
**Description:**
e.g. https://yukon-new-d10.w3creatives.com/docroot/fr/events/suivre-son-rythme-vers-le-bien-etre-prioriser-la-gestion-de-lenergie-0

All labels should be french. Here is a sample of ones that are not translated:

“Location” should be “Lieu”
“Cost” should be “Coût”
“Contact” should be “Renseignements”

**Task:**
Translate labels to French

**Deliverable:**
All labels should be translated on French page

**Comment by leeomara** [comment]
This is still an issue.

**Comment by leeomara** [comment]
Testing on W3 Creatives site:

- ❌ “Location” should be “Lieu”
- ❌ “Cost” should be “Coût”
- ❌ “Contact” should be “Renseignements”

**Comment by w3creatives** [comment]
This is fixed.  Please login on see the screenshot below:

![Suivre-son-rythme-vers-le-bien-être-prioriser-la-gestion-de-l’énergie-Yukon-ca-10-18-2024_11_34_AM](https://github.com/user-attachments/assets/5f1516f2-cbe5-4871-901e-935353adb0b1)

**Comment by leeomara** [comment]
Looks good in UAT.
