### ISSUE TITLE
[P-15] Places

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#231]
All the activities related to the Places development.

- [x] #232
- [x] #233 
- [x] #234 
- [x] #235
- [x] #236 
- [x] #237 
- [x] #238
- [x] #239 
- [x] #240 
- [ ] #241 
- [x] #242 
- [x] #243 
- [x] #244 
- [x] #245 
- [x] #246 
- [ ] #247 
- [x] #382 
- [x] #383 

**Migration dependencies:**

- [x] Teams taxonomy terms
- [x] Department taxonomy terms
- [x] Community taxonomy terms
- [x] Region taxonomy terms
- [x] Contact Person field Paragraph
- [x] Holiday Hours field Paragraph
- [x] Community Facilities field Paragraph
- [x] Education Facilities field Paragraph
- [x] Health Facilities field Paragraph
- [x] Transactional Facilities field Paragraph
- [x] Date Range Text Paragraph
- [x] Opening Times field Paragraph

**Comment by lgontard** [comment]
> All the activities related to the Places development.
> 
> * [x]  [[P-1] French Places page is missing/broken #232](https://github.com/ytgov/yukon-ca/issues/232)
> * [x]  [[P-1] Places shows authored by / authored date #233](https://github.com/ytgov/yukon-ca/issues/233)
> * [x]  [[P-2] Places page "Social sharing" and "Full width" fields show "on" value #234](https://github.com/ytgov/yukon-ca/issues/234)
> * [x]  [[P-2] "All" label for Community filter should be "Any" #235](https://github.com/ytgov/yukon-ca/issues/235)
> * [x]  [[P-2] Places filters are not shareable #236](https://github.com/ytgov/yukon-ca/issues/236)
> * [x]  [[P-2] French Places format time incorrectly #237](https://github.com/ytgov/yukon-ca/issues/237)
> * [x]  [[P-2] Multiple opening times formatted poorly #238](https://github.com/ytgov/yukon-ca/issues/238)
> * [x]  [[P-2] Places school grades formatted incorrectly #239](https://github.com/ytgov/yukon-ca/issues/239)
> * [x]  [[P-2] Places school contacts formatted incorrectly #240](https://github.com/ytgov/yukon-ca/issues/240)
> * [ ]  [[P-2] Sanitary facility place field in wrong order #241](https://github.com/ytgov/yukon-ca/issues/241)
> * [x]  [[P-2] Health facility place field in wrong order #242](https://github.com/ytgov/yukon-ca/issues/242)
> * [x]  [[P-2] Community facility place field in wrong order #243](https://github.com/ytgov/yukon-ca/issues/243)
> * [x]  [[P-2] Transactional facility place field in wrong order #244](https://github.com/ytgov/yukon-ca/issues/244)
> * [x]  [[P-1] Places "Open 24 hours" #245](https://github.com/ytgov/yukon-ca/issues/245)
> * [x]  [[P-2] Place information should display in left column #246](https://github.com/ytgov/yukon-ca/issues/246)
> * [x]  [[P-1] Facilities listings are missing #247](https://github.com/ytgov/yukon-ca/issues/247)
> * [x]  [[P-2] Places configuration #382](https://github.com/ytgov/yukon-ca/issues/382)
> * [x]  [[P-2] Places Views #383](https://github.com/ytgov/yukon-ca/issues/383)
> 
> **Migration dependencies:**
> 
> * [x]  Teams taxonomy terms
> * [x]  Department taxonomy terms
> * [x]  Community taxonomy terms
> * [x]  Region taxonomy terms
> * [x]  Contact Person field Paragraph
> * [x]  Holiday Hours field Paragraph
> * [x]  Community Facilities field Paragraph
> * [x]  Education Facilities field Paragraph
> * [x]  Health Facilities field Paragraph
> * [x]  Transactional Facilities field Paragraph
> * [x]  Date Range Text Paragraph
> * [x]  Opening Times field Paragraph

This works in YG UAT
