### ISSUE TITLE
[P-1] French Places page is missing/broken

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#232]
**Description:**
Should be at [https://test-yukon-drupal-10.pantheonsite.io/fr/places](https://yukon.ca/fr/places), but is (apparently) at https://test-yukon-drupal-10.pantheonsite.io/fr/etablissements-installations-et-bureaux

_Missing:_
Sidebar showing filters
Places listing

_What is there:_
Title
intro
![image](https://github.com/ytgov/yukon-ca/assets/123640502/c5ccf907-4547-4b43-897d-c929b0f1e7aa)

**Task:**
Fix migrations for Places(check why the Places listing is missing) and add Filter on the left sidebar

**Deliverable:**
On French Places page should be a sidebar with a filter and Places listing

**Comment by leeomara** [comment]
❌ Places listing not showing up at all

**Comment by leeomara** [comment]
Looks good on UAT.
