### ISSUE TITLE
[P-1] Places shows authored by / authored date

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#233]
**Description:**
Top level Places page shows “Submitted by” line

Submitted by Anonymous (not verified) on Fri, 11/06/2020 - 13:59

https://test-yukon-drupal-10.pantheonsite.io/places or https://test-yukon-drupal-10.pantheonsite.io/places-2

Compare with https://yukon.ca/en/places/
![image](https://github.com/ytgov/yukon-ca/assets/123640502/fcb29ec0-22d2-4775-9dfe-9a7ccf4b34af)

**Task:**
Check why Places page is available on https://test-yukon-drupal-10.pantheonsite.io/places-2 instead of https://test-yukon-drupal-10.pantheonsite.io/places and fix. Remove “Submitted by” section from displaying.

**Deliverable:**
Places page should be available on https://test-yukon-drupal-10.pantheonsite.io/places  and there shouldn't be “Submitted by” info on page view

**Comment by leeomara** [comment]
Closing this, as we now *want* to show when a record was recently updated.
