### ISSUE TITLE
[P-2] Places page "Social sharing" and "Full width" fields show "on" value

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#234]
**Description:**
The top-level Places page shows
On
Full width
Off
above “Places listing”
![image](https://github.com/ytgov/yukon-ca/assets/123640502/826ec2fd-c8ae-4c3b-b1f0-32ec569a4d1e)

**Task:**
Hide "Full width" field from displaying

**Deliverable:**
"Full width" field shouldn't be displayed on Places page

**Comment by w3creatives** [comment]
This is fixed:

https://yukon-new-d10.w3creatives.com/docroot/en/places

**Comment by leeomara** [comment]
Looks good in UAT.
