### ISSUE TITLE
[P-2] Places filters are not shareable

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#236]
**Description:**
![image](https://github.com/ytgov/yukon-ca/assets/123640502/67dd5b7c-1bc2-4229-b95d-7c443fae88c7)

**Task:**
Fix filter logic

**Deliverable:**
 Places filters should be shareable

**Comment by w3creatives** [comment]
https://yukon.ca/en/places?field_community_facility_type_tid_i18n=49&field_community_tid_i18n=130

https://yukon-new-d10.w3creatives.com/docroot/en/places?field_community_facility_type_target_id=167&field_community_target_id=150

**Comment by leeomara** [comment]
Looks good on UAT.
