### ISSUE TITLE
[P-2] Multiple opening times formatted poorly

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#238]
**Description:**
![image](https://github.com/ytgov/yukon-ca/assets/123640502/1184bf34-56df-477a-9255-55a137fc76e7)

**Task:**
Fix multiple opening times format

**Deliverable:**
Multiple opening times should format should be the same as on D7

**Comment by w3creatives** [comment]
Review link:

https://yukon-new-d10.w3creatives.com/docroot/en/places/beaver-creek-health-centre

**Comment by leeomara** [comment]
Looks good on UAT.
