### ISSUE TITLE
[P-2] Places school grades formatted incorrectly

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#239]
**Description:**

Grades should be:
**Grades**
K to 12

On D10, currently they are:
**From**
K
**To**
12

E.g. Aurora Virtual School

D10: https://test-yukon-drupal-10.pantheonsite.io/places/aurora-virtual-school
D7: https://yukon.ca/en/places/aurora-virtual-school

**Task:**
Fix school grades format

**Deliverable:**
School grades format should be the same as on D7 site

**Comment by w3creatives** [comment]
Please review:

https://yukon.ca/en/places/aurora-virtual-school
https://yukon-new-d10.w3creatives.com/docroot/en/places/aurora-virtual-school

**Comment by leeomara** [comment]
Looks good in UAT.
