### ISSUE TITLE
[P-2] Places school contacts formatted incorrectly

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#240]
**Description:**
Contacts should be:
**Contact**
**Superintendent:** [Office of the Superintendents](http:/#)
867-667-5068
**Team leader:** [Mark Connell](http:/#)
867-456-6777

On D10, currently they are like:

**Principal**
Principal Name
**Team leader**
Mark Connell
**Telephone**
867-456-6777
**Superintendent**
Bureau des surintendants
**Telephone**
867-667-5068
**Email**
[mark.connell@yukon.ca](mailto:mark.connell@yukon.ca)
**Email**
[publicschools@yukon.ca](mailto:publicschools@yukon.ca)

E.g. Aurora Virtual School

D10: https://test-yukon-drupal-10.pantheonsite.io/places/aurora-virtual-school
D7: https://yukon.ca/en/places/aurora-virtual-school

**Task:**
FIx school contacts format

**Deliverable:**
School contacts format should be the same as on D7

**Comment by w3creatives** [comment]
This issue was linked with #544

**Comment by w3creatives** [comment]
Please review:

https://yukon.ca/en/places/aurora-virtual-school
https://yukon-new-d10.w3creatives.com/docroot/en/places/aurora-virtual-school

**Comment by leeomara** [comment]
Looks good on W3 server.

**Comment by leeomara** [comment]
- ✅ Looks good in English
- ❌ In French, it shows "Direction: Principal Name"

**Comment by w3creatives** [comment]
Please review: https://yukon-new-d10.w3creatives.com/docroot/fr/places/ecole-chief-zzeh-gittlit

**Comment by leeomara** [comment]
Looks good on UAT.
