### ISSUE TITLE
[P-2] Sanitary facility place field in wrong order

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#241]
**Description:**
_Compare:_
D7: https://yukon.ca/en/places/agriculture-branch
D10: https://test-yukon-drupal-10.pantheonsite.io/places/agriculture-branch

_Should be:_
Address
Main telephone
Services
Accessibility
Transactional facially type
Opening times
Contact

**Task:**
FIx Sanitary facility place field order

**Deliverable:**
Sanitary facility place field order should be the same as on D7

**Comment by w3creatives** [comment]
Almost there. But It is created by paragraph, so we can't update the position. 

https://yukon-new-d10.w3creatives.com/docroot/places/agriculture-branch

**Comment by leeomara** [comment]
Accessibility and transactional facility type need to be swapped. Is this possible?

**Comment by leeomara** [comment]
- ✅ This looks good on W3 test server (e.g. https://yukon-new-d10.w3creatives.com/docroot/en/node/10968)
- ❌ This is missing the Paragraph (and hence Services and Transactional facility type)

Maybe this is a migration process issue?

Tested on a number of different places

- `en/places/motor-vehicles-services-old-crow`
- `en/places/motor-vehicles-services-mayo`

It looks like paragraphs of the type "Transactional facilities" did not migrate correctly?

**Comment by lgontard** [comment]
Transactional facilities migrated now. This is resolved on YG UAT
