### ISSUE TITLE
[P-2] Health facility place field in wrong order

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#242]
**Description:**
_Compare:_
D7: https://yukon.ca/en/places/mount-lorne-solid-waste-facility
D10: https://test-yukon-drupal-10.pantheonsite.io/places/mount-lorne-solid-waste-facility

_Should be:_
Address
Main telephone
Accessibility
Services
Opening times

**Task:**
FIx Health facility place field order.

**Deliverable:**
Health facility place field order should be the same as on D7 site

**Comment by w3creatives** [comment]
Please review:

https://yukon.ca/places/mount-lorne-solid-waste-facility
https://yukon-new-d10.w3creatives.com/docroot/places/mount-lorne-solid-waste-facility

**Comment by leeomara** [comment]
Looks good on W3 test server.

**Comment by leeomara** [comment]
Looks good on UAT.
