### ISSUE TITLE
[P-1] Places "Open 24 hours"

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#245]
**Description:**
Places where the opening details check the “Open 24 hours” box should display with

Open 24 hours

Example: Dawson hospital:
D7 https://yukon.ca/en/places/dawson-city-community-hospital
D10: https://test-yukon-drupal-10.pantheonsite.io/places/dawson-city-community-hospital

**Task:**
Fix "Open 24 hours" migration

**Deliverable:**
"Open 24 hours" field value should be migrated and visible on the page

**Comment by leeomara** [comment]
❌ "Open 24 hours" not showing on W3 Creatives test site.

**Comment by w3creatives** [comment]
Review link:

https://yukon-new-d10.w3creatives.com/docroot/en/places/department-environment-main-office

**Comment by leeomara** [comment]
Looks good on UAT (LG).
