### ISSUE TITLE
[P-2] Place information should display in left column

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#246]
**Description:**
_Compare:_
D7: https://yukon.ca/en/places/yukon-archives-hours-and-location
D10: http://yukon-ca-d10.sp8.kellett.ca/places/yukon-archives-hours-and-location
The “Place information” content should display beneath the map, to the left of Address, service and hours.

Currently in D10 it displays full-width, beneath Opening times.

_When linearized, the order should be_
title
map
“Place information”
Address
contact, etc.

**Task:**
Fix displaying place information in left column

**Deliverable:**
Place information should display in left column

**Comment by w3creatives** [comment]
Review link:

https://yukon-new-d10.w3creatives.com/docroot/en/places/department-environment-main-office

**Comment by leeomara** [comment]
This looks good on UAT (EF).
