### ISSUE TITLE
[P-1] Facilities listings are missing

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#247]
**Description:**
A number of pages, such as “Find a school”, make use of a view that lists Places of certain types.

D7: https://yukon.ca/en/education-and-schools/kindergarten-grade-12/find-school

In D7, this block is facilities_listing_blocks, it has 18 displays (pages/blocks).

Some other pages that include these views (all D7):

https://yukon.ca/en/driving-and-transportation/airports-and-aerodromes/find-airport-or-aerodrome
https://yukon.ca/en/health-and-wellness/find-hospital-or-health-centre
https://yukon.ca/en/long-term-care-homes
https://yukon.ca/en/arts-and-culture/museums-and-public-collections/public-art-locations
https://yukon.ca/en/driving-and-transportation/travel-yukon/find-visitor-information-centre

**Task:**
FIx Facilities listing migration

**Deliverable:**
Facilities listings should exist on D10 like on D7

**Comment by w3creatives** [comment]
Most of the things were missing for this functionality:

1) We have created a new taxonomy "School Board Type"
2) Added Migration for School Board type - yukon_migrate_school_board_type
3) Created a School board type field in the education facilities paragraph.
4) Update the migration of the - yukon_migrate_education_facilities
5) Created a view as a block for that and assigned the same to the pages.

Links: 
1) https://yukon-new-d10.w3creatives.com/docroot/en/driving-and-transportation/airports-and-aerodromes/find-airport-or-aerodrome
2) https://yukon-new-d10.w3creatives.com/docroot/en/health-and-wellness/care-services/find-hospital-or-health-centre
3) https://yukon-new-d10.w3creatives.com/docroot/en/health-and-wellness/care-services/continuing-care-facilities
4) https://yukon-new-d10.w3creatives.com/docroot/en/arts-and-culture/museums-and-public-collections/public-art-locations
5) https://yukon-new-d10.w3creatives.com/docroot/en/driving-and-transportation/travel-yukon/find-visitor-information-centre

6) https://yukon-new-d10.w3creatives.com/docroot/en/education-and-schools/plan-elementary-and-high-school/find-school

Find an airport or aerodrome | Yukon.ca
https://yukon-new-d10.w3creatives.com/docroot/en/driving-and-transportation/airports-and-aerodromes/find-airport-or-aerodrome

Find a hospital or health centre | Yukon.ca
[https://yukon-new-d10.w3creatives.com
No answer
11:19 AM](https://yukon-new-d10.w3creatives.com/docroot/en/health-and-wellness/care-services/find-hospital-or-health-centre)

**Comment by leeomara** [comment]
I see this working correctly on W3 Creatives test server.

On UAT, no places are listed. 

e.g. All 3 school board types list "No results found". The School board taxonomy is there, as are terms. Places migration seems good, as I can find specific schools. However, the view is not finding them.

![Screenshot 2024-10-15 at 1 56 44 PM](https://github.com/user-attachments/assets/51b581cd-2e20-4d05-8c60-33a7a5a9b06f)

Same with Find an airport or aerodrome, Find a hospital or health centre, Long-term care homes, Public art locations, Find a visitor information centre. All show "No results found."

**Comment by w3creatives** [comment]
This should be working. We need to re-run the migration on UAT.

**Comment by leeomara** [comment]
This appears related to the similar issue with campgrounds (#257 and #261), where the term filters don't align.

For example, the view `facilities_listing_blocks`, which has a display for "Yukon Education" (`block_19`), the two term-based filters have the wrong terms listed:

- (field_places_record_type: Paragraph) Paragraph: Education facility type (= Solid waste)
- (field_places_record_type: Paragraph) Paragraph: School board type (or Unknown)

Those should be:

- (field_places_record_type: Paragraph) Paragraph: Education facility type (= **School**)
- (field_places_record_type: Paragraph) Paragraph: School board type (= **Yukon Education**)

Related issues:
- #257
- #261

**Comment by leeomara** [comment]
| D7 display (`facilities_listing_blocks`) | D10 version (`facilities_listing_blocks`) |
|------------|-------------|
| Hospital | ✅ |
| Continuing care | ✅ |
| Community care | ✅ |
| Cemetery | ? |
| Crematorium | ? |
| College | ✅ |
| Commission scolaire francophone du Yukon (CSFY) | ✅ |
| Airport | ✅ |
| Archive | ✅ |
| Community centre | ✅ |
| Library | ✅ |
| Public art | ✅ |
| Tourism info centre | ✅ |
| Hazardous waste | ✅ |
| Recycling | ✅ |
| Solid waste | ✅ |
| Visitor information centres | ✅ |
| Interpretive centres | ✅ |
| First Nation School Board (FNSB) | ✅ |
| Yukon Education | ✅|

D10 also has "School"

**Comment by leeomara** [comment]
Every single of the D10 Facilities displays in UAT have issues with term filters.

**Comment by w3creatives** [comment]
We have updated the migration process and now we will match TID as well during the import. This will save us from any future issues linked to taxonomies.  Please check and let us know if any modifications are required. Migration re-run is required.

**Comment by leeomara** [comment]
@w3creatives That's great news. Let me know when the code for this fix ships, so I can re-run the migrations and test.

**Comment by w3creatives** [comment]
Please consider the latest PR:

https://github.com/ytgov/yukon-ca/pull/670

**Comment by leeomara** [comment]
This is much improved, but not quite there yet.

- ✅ The following are working as expected:
  - Hospital  
  - Continuing care  
  - Community care  
  - College  
  - Commission scolaire francophone du Yukon (CSFY)  
  - Airport  
  - Public art  
  - Visitor information centres  
  - First Nation School Board (FNSB)  
  - Yukon Education 
  - School 

- ❌ The following don't list content, and have filters that don't make sense
  - Archive 
  - Community centre
  - Library
  - Tourism info centre
  - Hazardous waste
  - Recycling
  - Solid waste
  - Interpretive centres

E.g. Archive has a filter

> (field_places_record_type: Paragraph) Paragraph: Community facility type (= **Takhini Hot Spring Road**)

**Comment by w3creatives** [comment]
Please review:

https://yukon-new-d10.w3creatives.com/docroot/en/admin/structure/views/view/facilities_listing_blocks/edit/block_8

**Comment by lgontard** [comment]
@leeomara Can you look at this one?

**Comment by leeomara** [comment]
These look good in dev.
