### ISSUE TITLE
[P-3] Campground and rec site fields and labels formatted poorly

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#249]
**Description:**
Labels should align with values. “Site description” should have a colon.

This is a problem for the fields at the top, as well as for “Location” fields.

Under “Location”, the download button should be beneath the “Map download” label.

“Serviced dates” look like “Thu, 05/04/2023 - 12:00 to October 2, 2023”, should look like “May 4 to October 2, 2023“
![image](https://github.com/ytgov/yukon-ca/assets/123640502/fb1b3b71-61f4-4f32-973f-a14acbad3f6f)
![image](https://github.com/ytgov/yukon-ca/assets/123640502/762d9fb1-d00c-41c3-bcfe-4ae1f69543f4)

**Task:**
Fix  fields and labels format

**Deliverable:**
Fields and labels format should looks like in D7

**Comment by w3creatives** [comment]
Please review:

https://yukon-new-d10.w3creatives.com/docroot/en/outdoor-recreation-and-wildlife/camping/site/frances-lake-campground
https://yukon.ca/en/outdoor-recreation-and-wildlife/camping/site/frances-lake-campground

**Comment by leeomara** [comment]
This looks good in UAT.
