### ISSUE TITLE
[P-3] Location value should be not be linked

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#250]
**Description:**
Location value should be not be linked

**Task:**
Fix Location value displaying

**Deliverable:**
Location value should look like on D7

**Comment by w3creatives** [comment]
Please review:

https://yukon-new-d10.w3creatives.com/docroot/en/outdoor-recreation-and-wildlife/camping/site/wolf-creek-campground

**Comment by leeomara** [comment]
Looks good on UAT.
