### ISSUE TITLE
[P-3] Map download value should be title

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#251]
**Description:**
Currently it appears to be a filename

D10: env-wolf-creek-campground.pdf

D7: Carte du terrain de camping de Wolf Creek

https://test-yukon-drupal-10.pantheonsite.io/outdoor-recreation-and-wildlife/camping/site/wolf-creek-campground

**Task:**
FIx Map download value displaying format

**Deliverable:**
Map download value should be title

**Comment by w3creatives** [comment]
Link to review:

https://yukon-new-d10.w3creatives.com/docroot/fr/plein-air-faune-et-flore/camping/site/camping-wolf-creek

**Comment by leeomara** [comment]
Looks good on UAT.
