### ISSUE TITLE
[P-2] Breadcrumb structure differs

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#252]
**Description:**
[D7](https://yukon.ca/en/outdoor-recreation-and-wildlife/camping/site/wolf-creek): Home / Outdoor recreation and wildlife / Camping / Find a campground or recreation site / Wolf Creek Campground
[D10](https://test-yukon-drupal-10.pantheonsite.io/outdoor-recreation-and-wildlife/camping/site/wolf-creek-campground): Home > Outdoor recreation and wildlife > Camping > Wolf Creek Campground
Missing “Find a campground or recreation site”

**Task:**
Configure breadcrumb structure

**Deliverable:**
Breadcrumb structure should be the same as on D7

**Comment by w3creatives** [comment]
This has been updated site wide.

**Comment by leeomara** [comment]
(mostly) resolved. Only remaining difference on the last breadcrumb missing "campground" from the final page:
 
[D10](https://yukon-new-d10.w3creatives.com/docroot/en/outdoor-recreation-and-wildlife/camping/site/aishihik-lake-campground): Home/Outdoor recreation and wildlife/Camping/Find a campground or recreation site/Aishihik Lake

vs the D7 site:

[D7](https://yukon.ca/en/outdoor-recreation-and-wildlife/camping/site/aishihik-lake): Home/Outdoor recreation and wildlife/Camping/Find a campground or recreation site/Aishihik Lake **Campground**

**Comment by w3creatives** [comment]
Review link:

https://yukon-new-d10.w3creatives.com/docroot/en/outdoor-recreation-and-wildlife/camping/site/wolf-creek-campground

**Comment by leeomara** [comment]
Looks good on UAT (EF)
