### ISSUE TITLE
[P-1] Link in campground description is UUID

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#253]
**Description:**
[On D10](https://test-yukon-drupal-10.pantheonsite.io/outdoor-recreation-and-wildlife/camping/site/wolf-creek-campground,) the text “Download the map, trail and accessibility descriptions” links to https://test-yukon-drupal-10.pantheonsite.io/outdoor-recreation-and-wildlife/camping/site/2579253b-94bc-4dab-a22e-673e202a81cd]

[On D7](https://yukon.ca/en/outdoor-recreation-and-wildlife/camping/site/wolf-creek) the same text links to https://yukon.ca/en/wolf-creek-trails (a Document page)

**Task:**
FIx migration Link in campground description

**Deliverable:**
Shouldn't be broken links in campground description

**Comment by leeomara** [comment]
Testing the `master` branch on cb497b634 shows the UUID link in the description (which I can see after #544 is applied) has been replaced with a `node/NNN` style link

```html
<a href="/node/25880">Download the map, trail and accessibility descriptions. </a>
```
