### ISSUE TITLE
[P-1] Campground service "Blue bear-proof recycling bins" is missing

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#254]
**Description:**
D10: https://test-yukon-drupal-10.pantheonsite.io/outdoor-recreation-and-wildlife/camping/site/pine-lake-campground
D7: https://yukon.ca/en/outdoor-recreation-and-wildlife/camping/site/pine-lake
The service exists, but Campgrounds appear to always have “no” after migration.
![image](https://github.com/ytgov/yukon-ca/assets/123640502/a780b28f-6dea-4145-b73a-f485af65d6fc)

**Task:**
Fix migration to have "Blue bear-proof recycling bins" imported

**Deliverable:**
Campground service "Blue bear-proof recycling bins" should be present as on D7

**Comment by w3creatives** [comment]
This is done.

https://yukon-new-d10.w3creatives.com/docroot/en/outdoor-recreation-and-wildlife/camping/site/pine-lake

**Comment by leeomara** [comment]
This looks good on UAT.
