### ISSUE TITLE
[P-1] Campground service "Change room" missing icon

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#255]
**Description:**
D10: https://test-yukon-drupal-10.pantheonsite.io/outdoor-recreation-and-wildlife/camping/site/pine-lake-campground
D7: https://yukon.ca/en/outdoor-recreation-and-wildlife/camping/site/pine-lake
It looks like “Blue bear-proof recycling bins” is also missing it’s icon.

![image](https://github.com/ytgov/yukon-ca/assets/123640502/a2c022c6-84ea-4302-ac58-a596787f3073)

**Task:**
Fix migration for "Change room" service

**Deliverable:**
"Change room" should be migrated as well

**Comment by w3creatives** [comment]
Fixed.

https://yukon-new-d10.w3creatives.com/docroot/en/outdoor-recreation-and-wildlife/camping/site/pine-lake-campground
