### ISSUE TITLE
[P-3] Campground peak times chart has off-brand colours

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#256]
**Description:**
D10: https://test-yukon-drupal-10.pantheonsite.io/outdoor-recreation-and-wildlife/camping/site/pine-lake-campground

D7: https://yukon.ca/en/outdoor-recreation-and-wildlife/camping/site/pine-lake
![image](https://github.com/ytgov/yukon-ca/assets/123640502/8ab1c62c-a545-4f52-8f8b-e023a48e2a28)

**Task:**
Fix colors on Campground peak times chart

**Deliverable:**
Colors on Campground peak times chart should be the same as on D7

**Comment by w3creatives** [comment]
Done.

https://yukon.ca/en/outdoor-recreation-and-wildlife/camping/site/pine-lake
https://yukon-new-d10.w3creatives.com/docroot/en/outdoor-recreation-and-wildlife/camping/site/pine-lake

**Comment by leeomara** [comment]
This looks good in UAT.
