### ISSUE TITLE
[P-1] Find a campground page missing content and functionality

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#257]
**Description:**
D10 does not have:

list of campgrounds
campground filter
“Peak times” chart
“Contact”
Some of these are blocks in D7.

**Task:**
FIx migration of missing content

**Deliverable:**
Find a campground page should be the same as on D7

Related issues:
- https://github.com/ytgov/yukon-ca/issues/518
- https://github.com/ytgov/yukon-ca/issues/381
- https://github.com/ytgov/yukon-ca/issues/379
- https://github.com/ytgov/yukon-ca/issues/523

**Comment by leeomara** [comment]
This looks good on W3 test server.

As with #261, on UAT, under the heading "Campground and recreation sites" we see only

> Sorry, no results were found. Try eliminating one of the filters applied. 

- https://github.com/ytgov/yukon-ca/issues/261

**Comment by leeomara** [comment]
On UAT, one of the view _Filter criteria_ lists

> Content: Campground site type (= Geomatics-blog)

Why is Geomatics-blog in there? That's wrong. Yet our config sync reports no deviation/difference from what's in code.

On D7, that same filter has Recreation site (day use) and Road accessible campground as the selected terms (for front-contry). Changing D10 (UAT) to match produces the desired results.

How do we correct this in a reproducible way?

**Comment by leeomara** [comment]
The "Site type" filter likewise has a problem where it doesn't have any options listed as available.

**Comment by w3creatives** [comment]
We need additional information about this.

**Comment by leeomara** [comment]
When I edit the "Find a campground or recreation site (Content)" view  (at `en/admin/structure/views/view/find_a_campground_or_recreation_site/edit/block_campgrounds`), the setting for the filter "Content: Campground site type" is set as ` = Geomatics-blog`. The correct value should be `= Road accessible campground`. The display "Backcountry campgrounds" is similarly wrong.

![Screenshot 2024-10-29 at 3 19 44 PM](https://github.com/user-attachments/assets/aab41ce5-9269-418a-a4fe-d3fd78c108de)

The term reference doesn't appear to survive the migration process.

**Comment by leeomara** [comment]
If we need to manually adjust those values, that's not the end of the world, but I'm concerned there are other view/term references that are similarly wrong that we don't know about.

**Comment by w3creatives** [comment]
We have updated the migration process and now we will match TID as well during the import. This will save us from any future issues linked to taxonomies.  Please check and let us know if any modifications are required. Migration re-run is required.

Linked with:

- #247 
- #261

**Comment by leeomara** [comment]
This looks good on UAT.
