### ISSUE TITLE
[P-2] "Site description (app)" field should be plain text

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#259]
**Description:**
"Site description (app)" field has wrong text format

**Task:**
FIx "Site description (app)" field format

**Deliverable:**
"Site description (app)" field should be plain text

**Comment by w3creatives** [comment]
Please check:

https://yukon.ca/en/outdoor-recreation-and-wildlife/camping/site/frances-lake-campground
http://dev-yukon-drupal-10.pantheonsite.io/en/outdoor-recreation-and-wildlife/camping/site/frances-lake-campground
https://yukon-new-d10.w3creatives.com/docroot/en/outdoor-recreation-and-wildlife/camping/site/frances-lake-campground

**Comment by leeomara** [comment]
Looks good on W3 test server.

**Comment by w3creatives** [comment]
Please check editing the Campground page on the YG server. 

W3 server seems to be short on some resource. This can be something that we need to figure out or consider for production launch.

**Comment by leeomara** [comment]
Looks good on UAT.
