### ISSUE TITLE
[P-2] Campground services should be only Yes/No

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#260]
**Description:**
Remove the “N/A” option from “Cook shelter” and “Hand pump or water tank provided” (none should have that option).

https://test-yukon-drupal-10.pantheonsite.io/node/36080/edit
![image](https://github.com/ytgov/yukon-ca/assets/123640502/f0cd69e6-0cbf-4ebd-9775-fbf96a609239)

**Task:**
Make “Cook shelter” and “Hand pump or water tank provided” required fields

**Deliverable:**
Campground services should be only Yes/No

**Comment by leeomara** [comment]
Bear-proof cache still shows an "N/A", but this is internal only and close enough. Looks good on UAT.
