### ISSUE TITLE
[P-1] Backcountry campgrounds page lists no campgrounds

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#261]
**Description:**
D10: https://test-yukon-drupal-10.pantheonsite.io/backcountry-campgrounds
D7: [https://yukon.ca/en/backcountry-campgrounds](https://yukon.ca/en/backcountry-campgrounds?region=78)
Yay, filters are there. Boo, no campgrounds listed.

**Task:**
Fix Backcountry campgrounds page lists migration

**Deliverable:**
Campground list should be displayed on  Backcountry campgrounds page like on D7 site

**Comment by w3creatives** [comment]
Fixed.

https://yukon-new-d10.w3creatives.com/docroot/en/backcountry-campgrounds

**Comment by leeomara** [comment]
In https://github.com/ytgov/yukon-ca/issues/257#issuecomment-2417275496 I figured out that the taxonomy or term references in the View were wrong in our UAT environment.

**Comment by w3creatives** [comment]
We need additional information about this.

**Comment by w3creatives** [comment]
We have updated the migration process and now we will match TID as well during the import. This will save us from any future issues linked to taxonomies.  Please check and let us know if any modifications are required. Migration re-run is required.

Linked with:

- #247 
- #257
