### ISSUE TITLE
[P-4] Campground labels not translated

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#266]
**Description:**
Campground labels are not translated

**Task:**
Translate Campground labels

**Deliverable:**
Campground labels should be translated

**Comment by w3creatives** [comment]
Done:

https://yukon-new-d10.w3creatives.com/docroot/fr/plein-air-faune-et-flore/camping/site/lieu-loisirs-kookatsoon-lake

**Comment by leeomara** [comment]
Looks good on UAT.
