### ISSUE TITLE
[P-4] Campground terms not translated

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#267]
**Description:**
e.g. “Southern Lakes”, “Klondike Highway”.

D10 https://test-yukon-drupal-10.pantheonsite.io/fr/plein-air-faune-et-flore/camping/site/lieu-loisirs-kookatsoon-lake

**Task:**
Translate Campground terms 

**Deliverable:**
Campground terms should be translated

**Comment by w3creatives** [comment]
Done:

https://yukon-new-d10.w3creatives.com/docroot/fr/plein-air-faune-et-flore/camping/site/lieu-loisirs-kookatsoon-lake

**Comment by leeomara** [comment]
Looks good on UAT.
