### ISSUE TITLE
[P-4] Campground dates not formatted for French

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#268]
**Description:**
D10 https://test-yukon-drupal-10.pantheonsite.io/fr/plein-air-faune-et-flore/camping/site/lieu-loisirs-kookatsoon-lake
D7 https://yukon.ca/fr/plein-air-faune-et-flore/camping/site/lieu-loisirs-kookatsoon-lake

_Should be like:_
Avec services : Du 12 mai au 2 octobre 2023
Barrières : 12 maià 2 octobre 2023

_Not like_
Serviced Fri, 05/12/2023 - 12:00 to October 2, 2023
Gate Open May 12, 2023 to October 2, 2023

**Task:**
Fix dates format for French

**Deliverable:**
Campground dates should be formatted for French as on D7 site

**Comment by leeomara** [comment]
Looks good in UAT.
