### ISSUE TITLE
[P-2] French backcountry campsite page has no filters or sites

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#269]
**Description:**
D10 https://test-yukon-drupal-10.pantheonsite.io/fr/terrains-de-camping-darriere-pays

D7 https://yukon.ca/fr/plein-air-faune-et-flore/camping/trouver-un-terrain-de-camping-ou-une-aire-de-recreation

**Task:**
Add filter to French backcountry campsite page

**Deliverable:**
Filters should be on French backcountry campsite page like on D7 site

**Comment by leeomara** [comment]
- ✅ Filter is visible on UAT
- ❌ No campsites are listed in UAT (not in English, nor in French)

**Comment by leeomara** [comment]
Suspect the missing campsites in French is the same as https://github.com/ytgov/yukon-ca/issues/257#issuecomment-2417275496

**Comment by leeomara** [comment]
Filters are now visible, though many are English non the French page

https://yukon-new-d10.w3creatives.com/docroot/fr/plein-air-faune-et-flore/camping/terrains-de-camping-darriere-pays

![Screenshot 2024-10-18 at 2 16 32 PM](https://github.com/user-attachments/assets/12101aee-bf68-4dbe-ac85-5fee27263f3d)

**Comment by leeomara** [comment]
Listing of campgrounds also has mix of English on the French page

e.g.
![Screenshot 2024-10-18 at 2 19 40 PM](https://github.com/user-attachments/assets/6a7e3c3a-ad71-478e-89ea-ecd9536358d2)

**Comment by w3creatives** [comment]
Please review everything here:

https://yukon-new-d10.w3creatives.com/docroot/fr/plein-air-faune-et-flore/camping/terrains-de-camping-darriere-pays

Certain checkboxes under filter do not have the translations working on production as well.

**Comment by leeomara** [comment]
Looks good on UAT.

**Comment by leeomara** [comment]
Opened a new issue for the English filters on French page, #671.
