### ISSUE TITLE
[P-2] Top-level page omits links from description

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#272]
**Description:**
Yukon Green Infrastructure Program, has text “about the program” that should be a link.
page: https://test-yukon-drupal-10.pantheonsite.io/blogs
![image](https://github.com/ytgov/yukon-ca/assets/123640502/3cf594d1-fff5-4d4d-9265-4e38d6424243)

**Task:**
Fix views configs to support links in the description

**Deliverable:**
Top-level page should support links in the description

**Comment by w3creatives** [comment]
All hyperlinks are working as required now.

https://yukon.ca/en/blogs
https://yukon-new-d10.w3creatives.com/docroot/en/blogs

**Comment by leeomara** [comment]
Looks good on UAT (e.g. Wildfire bulletins) (LG).
