### ISSUE TITLE
[P-2] Blog posts missing comment policy

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#274]
**Description:**
There are no “Comments” section with a link to the commenting policy and privacy statement on Blog post page.

**Task:**
Add “Comments” section with a link to the commenting policy and privacy statement to blog post page

**Deliverable:**
Each blog post should include a “Comments” section with a link to the commenting policy and privacy statement.

**Comment by w3creatives** [comment]
You can review this link:

https://yukon-new-d10.w3creatives.com/docroot/en/digital-blog/high-visibility-prescribed-burning-planned-along-whitehorse-south-fuel-break-august-12

**Comment by leeomara** [comment]
Looks good on UAT.
