### ISSUE TITLE
[P-1] Meta description content missing

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#276]
**Description:**
Compare “Training to be digital in the public service”

[Yukon.ca](http://yukon.ca/): https://yukon.ca/en/digital-blog/how-be-digital-public-service-training-collaboration
Meta description: How to be digital in the public service training collaboration
D10: https://test-yukon-drupal-10.pantheonsite.io/digital-blog/how-be-digital-public-service-training-collaboration
Meta description: (blank)

**Task:**
Fix Meta description field migration

**Deliverable:**
Meta description field should be migrated as on D7 site

**Comment by w3creatives** [comment]
This is done on W3 server. Please check view-source:

https://yukon-new-d10.w3creatives.com/docroot/digital-blog/how-be-digital-public-service-training-collaboration

**Comment by leeomara** [comment]
I see the meta description value migrated in UAT.
