### ISSUE TITLE
[P-3] French page shows English sidebar

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#277]
**Description:**
Left sidebar is not translated
https://test-yukon-drupal-10.pantheonsite.io/fr/blogs/digital-information-and-services/travaux-en-cours-printemps-2023

**Task:**
Translate left sidebar

**Deliverable:**
Left sidebar should be translated

**Comment by w3creatives** [comment]
This is fixed:

https://yukon.ca/fr/blogue-renseignements-et-services-en-ligne/travaux-en-cours-printemps-2023
https://yukon-new-d10.w3creatives.com/docroot/fr/digital-blog/travaux-en-cours-printemps-2023

**Comment by leeomara** [comment]
Looks good in UAT.
