### ISSUE TITLE
[P-2] Blog editorial team allows only a single selection

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#278]
**Description:**
Blog editorial team allows only a single selection

**Task:**
Improve the Blog editorial team field to allow multiple selection

**Deliverable:**
Should be possible to select a few Blog editorial team items

**Comment by leeomara** [comment]
Confirmed this is still an issue on UAT

**Comment by w3creatives** [comment]
Please review: https://yukon-new-d10.w3creatives.com/docroot/en/node/add/blog

**Comment by leeomara** [comment]
✅ Looks good on W3 server

**Comment by w3creatives** [comment]
Assigning this issue to YG to be tested on the UAT environment.

**Comment by leeomara** [comment]
Looks good on UAT.
