### ISSUE TITLE
[P-1] "Government of Yukon blogs" terms not translated

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#281]
**Description:**
None of the terms in https://test-yukon-drupal-10.pantheonsite.io/admin/structure/taxonomy/manage/blog_type/overview are translated to French.

Their name and descriptions require translation. D7 has that content translated.

**Task:**
Improve migration to support translated terms

**Deliverable:**
"Government of Yukon blogs" should have translation

**Comment by leeomara** [comment]
Looks good on UAT.
