### ISSUE TITLE
[P-1] Admin feedback results views missing

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#284]
**Description:**
There are views that allow administrators to review and process site feedback.

D7: https://yukon.ca/en/en/admin/dashboard/feedback and https://yukon.ca/en/en/admin/dashboard/feedback/search
![image](https://github.com/ytgov/yukon-ca/assets/123640502/34adf511-d865-4502-b5b1-759de191874b)
![image](https://github.com/ytgov/yukon-ca/assets/123640502/33384efd-ba1e-47b1-8117-5da10c8e1467)

**Task:**
Add missing admin feedback results views

**Deliverable:**
Admin feedback results views should be available like on D7 site

**Comment by leeomara** [comment]
The view `feedback_results` is currently setup with no access restrictions. This needs to be locked down.

**Comment by w3creatives** [comment]
Please review:

https://yukon-new-d10.w3creatives.com/docroot/en/admin/dashboard/feedback

Minor design changes are there because of the D10 version.

**Comment by leeomara** [comment]
- ✅ The Feedback Results view exists and shows feedback
- ✅ The Feedback Results view now requires authentication (and admin role)
- ❌ Missing search Feedback results view
- 🟠 The display is more than "Minor design changes". 
  - The D7 version of Feedback Results has:
    - pagination
    - filtering
    - table (columns: date, page URL, helpful, feedback)
    - grouped by page
  - The D10 version is a list of entity view

**Comment by lgontard** [comment]
Submissions will show up; can use existing tool options

**Comment by w3creatives** [comment]
[This PR](https://github.com/ytgov/yukon-ca/pull/711) has resolved this issue.
