### ISSUE TITLE
[P-2] Feedback form is not translated

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#285]
**Description:**
_French page should show:_
Avez-vous trouvé cette page utile?

_Instead is:_
Was this page helpful?

_Example:_
https://test-yukon-drupal-10.pantheonsite.io/fr/emploi/trouvez-un-emploi-dans-la-fonction-publique/voir-les-offres-demploi

**Task:**
Translate Feedback form

**Deliverable:**
Feedback form should be translated like on D7 site

Jira: 
- https://ygdevops.atlassian.net/browse/DMTPD3-165
- https://ygdevops.atlassian.net/browse/DMTPD3-60

**Comment by w3creatives** [comment]
This is has been fixed on the W3 server:

https://yukon.ca/fr/emploi/trouvez-un-emploi-dans-la-fonction-publique/voir-les-offres-demploi
https://yukon-new-d10.w3creatives.com/docroot/fr/emploi/trouvez-un-emploi-dans-la-fonction-publique/voir-les-offres-demploi

**Comment by leeomara** [comment]
Looks good on W3 server.

**Comment by leeomara** [comment]
This is nearly there.

The confirmation message in French should b

> Merci d’avoir pris le temps de nous faire part de vos commentaires.

Not (as it currently is)

> Thanks for taking the time to send us your feedback.

![Screenshot 2024-10-15 at 2 45 30 PM](https://github.com/user-attachments/assets/5e9e661f-989d-4705-b3bb-f7f451c46bda)

**Comment by w3creatives** [comment]
Please review:

https://yukon-new-d10.w3creatives.com/docroot/fr/emploi/trouvez-un-emploi-dans-la-fonction-publique/voir-les-offres-demploi

**Comment by leeomara** [comment]
Looks good on UAT (MN).
