### ISSUE TITLE
[P-2] Margin is different when mobile

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#287]
**Description:**
Margin is different on mobile view

**Task:**
Fix mobile style

**Deliverable:**
Mobile style should be the same as on D7 side

**Comment by lgontard** [comment]
@leeomara I can't test this on mobile. Can you have a look?

**Comment by leeomara** [comment]
Looks good on an iPhone Xs, on W3 site and UAT.
