### ISSUE TITLE
Observation of Departments in Admin (not just for Topics pages)

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#291]
**Description:**
URL: https://test-yukon-drupal-10.pantheonsite.io/node/32547/edit

I just noticed something that will apply to all pages in Y[ukon.ca.](http://yukon.ca/)

In the Admin experience, there is a list of departments in the Department field. The list starts with “Arts” and “Arts and events” which are not departments.

When we first launched [Yukon.ca](http://yukon.ca/), “Arts and events” was a category title. After a year or so, we separated the two so we now have a category called “Arts and culture” which was repurposed from the original “Arts and events” category. And then “Events” was broken out on it’s own category.

All of this is to say that if this separation wasn’t done properly at that time, maybe now is a good time to make sure it is.

I’ve also included a screen grab from the main news page on [Yukon.ca](http://yukon.ca/) (D7) where you see these appear with the Department filters.
![image](https://github.com/ytgov/yukon-ca/assets/123640502/533c2721-3fd7-4161-9255-d56e3852d9b1)
![image](https://github.com/ytgov/yukon-ca/assets/123640502/9083c339-f183-4ae0-ba6a-251977cca21b)
![image](https://github.com/ytgov/yukon-ca/assets/123640502/218b4252-9f9d-4e9c-bf33-43415ca5bd30)

**Task:**
Remove “Arts” and “Arts and events”  from departments

**Deliverable:**
“Arts” and “Arts and events” shouldn't be in departments

**Comment by w3creatives** [comment]
This has been fixed on the W3 server:

https://yukon.ca/en/news
https://yukon-new-d10.w3creatives.com/docroot/en/news

**Comment by leeomara** [comment]
Looks good on UAT.
