### ISSUE TITLE
Admin content list

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#292]
**Description:**
The current site includes these columns and values:

- Title
-- Title
-- URL/path
- Type & Department
-- Content type
-- Department
- Published
-- Yes/No
-- “New” flag
- Updated
-- Updated date
-- content author
- Actions
-- Edit

The new site includes:

- Title
- Content type
- Author
- Status
- Updated
- Operations

Missing are:

- URL/path
- Department

There is a filter by Department option

Compare

[https://yukon.ca/en/admin/content](https://yukon.ca/en/admin/content?type=blog&status=All)
https://test-yukon-drupal-10.pantheonsite.io/admin/content

**Task:**
Add missing columns to Admin content page

**Deliverable:**
D10 Admin content page should be the same as D7 page

**Comment by adrianrylski** [comment]
@leeomara and @lgontard this issue is ready for your testing in multidev https://translation-yukon-drupal-10.pantheonsite.io/en/admin/content

**Comment by lgontard** [comment]
@adrianrylski All the columns are there. When I updated a page, the "updated" flag did not appear. (see screengrab from prod)

![Image](https://github.com/ytgov/yukon-ca/assets/157647061/f19faa19-a60b-47e5-a66a-cd4a5165643d)

**Comment by adrianrylski** [comment]
@lgontard @leeomara Flag was added. Ready for review

**Comment by leeomara** [comment]
I see the flag content now included, but they do not appear styled. Is that intentionally?

![Image](https://github.com/ytgov/yukon-ca/assets/93003/21bf99fe-4d2e-4dc5-a2e1-56cf9a8bf48f)

It looks like "new" is a `<span>` with a class of `marker`.

![Image](https://github.com/ytgov/yukon-ca/assets/93003/6971d07b-ae2f-4891-90f6-33b6d788a3e4)

**Comment by lgontard** [comment]
@adrianrylski This works and looks great. @leeomara

**Comment by leeomara** [comment]
Yes, this is good to go!

**Comment by leeomara** [comment]
This has landed and can be closed.
