### ISSUE TITLE
Search bar is missing

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#293]
**Description:**
In D10 the search bar is missing. See attachment.
![image](https://github.com/ytgov/yukon-ca/assets/123640502/9c323e23-2b31-42eb-9615-3440a812b71c)

**Task:**
Add search bar

**Deliverable:**
The search bar should be present on the page like in D7

Jira: https://ygdevops.atlassian.net/browse/DMTPD3-4

**Comment by leeomara** [comment]
Closing this in favour of this other issue: 
- https://github.com/ytgov/yukon-ca/issues/375

**Comment by leeomara** [comment]
Nevermind me futzing with closed statuses. Sorry about the noise.
