### ISSUE TITLE
Breadcrumb symbol is different

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#294]
**Description:**
The symbol in the breadcrumbs is different in D10. They appear as forward slashes in D7.
![image](https://github.com/ytgov/yukon-ca/assets/123640502/5fbe5560-e0f6-4d5e-afd6-d0da7bbd74d4)
![image](https://github.com/ytgov/yukon-ca/assets/123640502/c447492f-f687-4474-81fd-64f2dab06dca)

**Task:**
Fix breadcrumb symbol

**Deliverable:**
Breadcrumb symbol on D10 should be the same as on D7

**Comment by leeomara** [comment]
Looks good on UAT.
