### ISSUE TITLE
Remove Promotion options (promoted to front page, Sticky at top of lists)

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#295]
**Description:**
In Drupal 10 there is a section called Promotion options and under that you can select Promoted to front page and Sticky at top of lists. I could not see these anywhere in D7.
![image](https://github.com/ytgov/yukon-ca/assets/123640502/0f76c36c-c2f5-4702-878e-294ebf2eb2c8)

**Task:**
Remove Promotion options 

**Deliverable:**
There shouldn't be Promotion options like in D7

Jira: https://ygdevops.atlassian.net/browse/DMTPD3-67
RM: https://rm.ewdev.ca/issues/64800?next_issue_id=65152

**Comment by adrianrylski** [comment]
Ready for testing on Pantheon Multidev https://admin-yukon-drupal-10.pantheonsite.io/

Shield credentials: ew/ewdev

**Comment by leeomara** [comment]
Looks good on admin-yukon-drupal-10.

**Comment by w3creatives** [comment]
Done by EW. Please close if completed.

**Comment by leeomara** [comment]
This is done. Only News keeps the "Promoted to homepage" option, which is used to determine which news items to feature on the homepage.
