### ISSUE TITLE
Scheduled publishing missing from D10

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#296]
**Description:**
The option to schedule a publishing job is at the bottom of the page in D7, but I couldn’t see it in D10.
![image](https://github.com/ytgov/yukon-ca/assets/123640502/67ecfd0c-485c-414a-9ad9-3bcf327f7671)

**Task:**
Add scheduled publishing feature

**Deliverable:**
Scheduled publishing feature should be available like in D7

**Comment by adrianrylski** [comment]
@leeomara As this will be part of Workflow migration, can I merge this ticket with #508 and close this one? Thx

**Comment by w3creatives** [comment]
Done by EW. Please close if completed.

**Comment by leeomara** [comment]
Moderation Scheduled Publish is implemented.
