### ISSUE TITLE
Hamburger menu options out of order in Drupal 10

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#297]
**Description:**
I just happened to notice this here and I wanted to document it. The main [Yukon.ca](http://yukon.ca/) hamburger menu displays pages in two sections. The heading appears in Drupal 10, but the menu items are not associated with it and some appear to be missing.
![image](https://github.com/ytgov/yukon-ca/assets/123640502/f20919d1-c901-46ac-bff8-20ddc6ffabcc)
![image](https://github.com/ytgov/yukon-ca/assets/123640502/a003a04c-a7b2-42ea-b1c1-27a77a46468b)

**Task:**
Fix Hamburger menu options order

**Deliverable:**
Hamburger menu options order should be the same as on D7

Jira: https://ygdevops.atlassian.net/browse/DMTPD3-128

**Comment by leeomara** [comment]
This was reported again today, with a slight variation.

Menu is missing the header "More on Yukon.ca" that separates 16 categories from "other sections" ; 16 categories need to be in alphabetical order.

**Comment by w3creatives** [comment]
More on Yukon.ca needs to added manually.  This was discussed earlier.

We will include the instructions in the readme file.

**Comment by leeomara** [comment]
After adding the "More on yukon.ca" `<nolink>` items, the display of the menu still differs from D7.

<img width="1105" alt="Screen Shot 2024-10-27 at 8 29 45 PM" src="https://github.com/user-attachments/assets/054118a8-d27a-4490-99bf-d33bbcb20d5c">

**Comment by w3creatives** [comment]
1. On the admin side of the website, go to >> Structure and click >> Menus.
2. From the available list of menus find >> Main menu secondary >> OR >> More on Yukon.ca >> Click edit
3. Then we need to add the 7 menu items from the **More on Yukon.ca** menus (Contact the government, Legislation, Documents, News, Events, Places, Forms) 
4. Remove the same 7 menu items from the Mega Menu.

**Comment by leeomara** [comment]
Tested this on UAT, and it works great. I see the code to update Readme landed in #669.
