### ISSUE TITLE
Button styles not working

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#298]
**Description:**
Example

D10 https://test-yukon-drupal-10.pantheonsite.io/view-all-current-job-postings
D7 [View all current job postings](https://yukon.ca/en/employment/find-government-job/view-all-current-job-postings)

**Task:**
Add styles for buttons

**Deliverable:**
Button styles should be the same as on D7 site

Jira:
- https://ygdevops.atlassian.net/browse/DMTPD3-183
- https://ygdevops.atlassian.net/browse/DMTPD3-22
- https://ygdevops.atlassian.net/browse/DMTPD3-191

RM: https://rm.ewdev.ca/issues/64794

**Comment by leeomara** [comment]
Relates to 
- https://github.com/ytgov/yukon-ca/issues/226
- https://github.com/ytgov/yukon-ca/issues/203

Not quite the same as https://github.com/ytgov/yukon-ca/issues/196

**Comment by adrianrylski** [comment]
@leeomara and @lgontard This issue is ready for testing in multidev https://edit-interf-yukon-drupal-10.pantheonsite.io/en/task-64794-buttons-test

**Comment by lgontard** [comment]
@adrianrylski @leeomara The buttons look good. The green "Success" button is fine as long as it's not visible to the public. 

The link colours are not quite right, but I think it was incorrect in some places on D7. According to our Digital Services Delivery Guide:
active link: #005a65
visited link: #643f5d
hover link: #008392

The "More" link would be at the bottom of multistep pages and the "See more..." on the LPs. The colours should be:
active link: #005a65
visited link: #643f5d
hover link: #008392

**Comment by leeomara** [comment]
This issue/task will be taken over by W3 Creatives. No further work by EW is required for this issue.

**Comment by leeomara** [comment]
Looks good on UAT. E.g. https://yukond10.cms-uat.yukon.ca/en/view-all-current-job-postings
