### ISSUE TITLE
Rich text editor toolbar

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#299]
**Description:**
Remove underline
Review and revise

**Task:**
Configure CKEditor 5

**Deliverable:**
CKEditor should have the same configurations as on D7

**Comment by w3creatives** [comment]
CKeditor configuration is matched (as possible) with D7.  Exact match will not be possible as the current version functionality is somewhat different.

Please pull the latest code to deploy UAT env.
