### ISSUE TITLE
Copyright year in footer is not aligned

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#300]
**Description:**
URL: https://test-yukon-drupal-10.pantheonsite.io/outdoor-recreation-and-wildlife/yukon-wildlife/yukon-wildlife-species

The copyright year should be aligned with the “Government of Yukon” in the footer. See screen grab from Drupal 7 to see how it should appear.
![image](https://github.com/ytgov/yukon-ca/assets/123640502/9c085b43-c9a2-498b-9240-09fa50e8f4b2)
![image](https://github.com/ytgov/yukon-ca/assets/123640502/ccc4e3d0-afab-4403-8e26-e1dfc3af9813)
![image](https://github.com/ytgov/yukon-ca/assets/123640502/a2a10e87-c473-4b94-b2dd-21b855f75f77)

**Task:**
Fix copyright year alignment in footer

**Deliverable:**
Copyright year in footer should be aligned

**Comment by adrianrylski** [comment]
@leeomara This issue does not exist anymore. 
![Screenshot from Adrian Rylski 2024-07-12 at 09 39 04@2x](https://github.com/user-attachments/assets/b4b2ce09-273c-41c8-835a-2e1983e1cddd)

**Comment by leeomara** [comment]
Looks good on Pantheon dev and test.

I'll need to figure out why on YG UAT, the footer block shows up as "This block is broken or missing"

**Comment by leeomara** [comment]
This issue/task will be taken over by W3 Creatives. No further work by EW is required for this issue.

**Comment by w3creatives** [comment]
This is fixed.

**Comment by leeomara** [comment]
This looks great in UAT.
