### ISSUE TITLE
Some links are absolute to yukon.ca

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#301]
**Description:**
Concerned that this may cause issues for migrated content, where the new version of content has a different URL than the old.

First seen in a campground: https://test-yukon-drupal-10.pantheonsite.io/outdoor-recreation-and-wildlife/camping/site/congdon-creek-campground Related tasks are to [yukon.ca](http://yukon.ca/).

**Task:**
Improve migration logic to avoid absolute links to yukon.ca

**Deliverable:**
There shouldn't be absolute links to yukon.ca on D10

**Comment by leeomara** [comment]
There are also issues where some content contains UUID links

- https://github.com/ytgov/yukon-ca/issues/253
- https://github.com/ytgov/yukon-ca/issues/201

**Comment by leeomara** [comment]
Another broken link issue: https://github.com/ytgov/yukon-ca/issues/216

**Comment by adrianrylski** [comment]
@leeomara, I must have missed updating this one and adding it to the project, but it was in our sprint, so I added it.

We have discovered that this relates to the UUID link module, which does not have D10 versions, so we will use the script to migrate and convert the links to relative URLs. 

Please let me know if that is ok with you. Thank you

**Comment by leeomara** [comment]
@ab-ew While testing this on my local, I'm seeing improvements, but also a problem. The content looks okay in the editor, but the rendered link is broken (empty).

For example, on the Aishihik Lake Campground page, the "Related tasks" links look okay on the admin/editor side, but they all render with blank URLs.

- Related link name: "Get a camping permit"
- D10 URL: `/en/outdoor-recreation-and-wildlife/camping/get-camping-permit`
- D7 URL: `https://yukon.ca/en/outdoor-recreation-and-wildlife/camping/get-camping-permit` (note the absolute, which is also not ideal)
- D10 Anchor tag: `<a href="">Get a camping permit</a>`

![Screenshot 2024-09-10 at 1 05 29 PM](https://github.com/user-attachments/assets/69d45d49-ace1-4b81-ab5e-d59d5dd59dda)
![Screenshot 2024-09-10 at 1 04 54 PM](https://github.com/user-attachments/assets/18f4f416-22a1-4817-980a-5323d0b31dc6)

I found one link where the URL was in the format `/node/NNN`, and that link did render correctly. Is the problem that the link URL values don't like path aliases?

**Comment by leeomara** [comment]
It looks like, accidentally as part of this work a change was made that results in the campground Site Description data using the wrong source ("Site Description App" instead).

See:
- commit https://github.com/ytgov/yukon-ca/commit/21c9048ad7566c17e99a2a0aeee3a9d64facb8fb#diff-62f3e80a1e547fff212350e52f8ed7d35545b122d9bc9fa4fc591ec96493a777L134
- Merge request: https://github.com/ytgov/yukon-ca/pull/530

**Comment by leeomara** [comment]
This issue/task will be taken over by W3 Creatives. No further work by EW is required for this issue.

**Comment by w3creatives** [comment]
This should work now:

**Comment by leeomara** [comment]
Looks good on UAT (MN).
