### ISSUE TITLE
Formatting of long breadcrumbs

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#302]
**Description:**
in D7 long breadcrumbs are truncatted with “…”

E.g.
D7 https://yukon.ca/en/news/statement-minister-responsible-women-and-gender-equity-directorate-jeanie-mclean-annual-meeting
D10 https://test-yukon-drupal-10.pantheonsite.io/news/statement-minister-responsible-women-and-gender-equity-directorate-jeanie-mclean-annual
![image](https://github.com/ytgov/yukon-ca/assets/123640502/cda9dc52-1391-474e-9e21-5b16acfba53c)

**Task:**
FIx styling for long breadcrumbs

**Deliverable:**
Long breadcrumbs styling should be the same as on D7 site

**Comment by adrianrylski** [comment]
This is ready for testing on https://global-yukon-drupal-10.pantheonsite.io/

**Comment by leeomara** [comment]
Tested at https://global-yukon-drupal-10.pantheonsite.io/en/news/statement-minister-responsible-women-and-gender-equity-directorate-jeanie-mclean-annual Looks good.

**Comment by leeomara** [comment]
This issue/task will be taken over by W3 Creatives. No further work by EW is required for this issue.

**Comment by w3creatives** [comment]
Please review:

https://yukon-new-d10.w3creatives.com/docroot/en/news/statement-minister-responsible-women-and-gender-equity-directorate-jeanie-mclean-annual

**Comment by leeomara** [comment]
This looks good on UAT.
