### ISSUE TITLE
Add Translation Management Tool

### ISSUE THREAD

**Issue by leeomara** [ytgov/yukon-ca#314]
To better support our staff who translate content in the site, we'd like to install and configure Translation Management Tool (TMGMT, https://www.drupal.org/project/tmgmt).

The desired "provider" is file (XLIFF).

**Comment by leeomara** [comment]
Should also include enabling Diff (or similar) with reasonable interface for translators to review changes, in order to inform if translation is required.

**Comment by adrianrylski** [comment]
@leeomara and @lgontard This issues is ready for your testing in multidev https://translation-yukon-drupal-10.pantheonsite.io/en/admin/tmgmt

**Comment by leeomara** [comment]
This looks great.

2 small configuration changes requested for the File provider (https://translation-yukon-drupal-10.pantheonsite.io/en/admin/tmgmt/translators/manage/file):

- check "XLIFF CDATA"
- uncheck " Allow to override the format per job"

**Comment by adrianrylski** [comment]
@leeomara Config updated. Ready for testing.

**Comment by leeomara** [comment]
Looks perfect!

**Comment by leeomara** [comment]
✅ This looks good in UAT.
