### ISSUE TITLE
[P-1] Homepage is not setup as the default front page.

### ISSUE THREAD

**Issue by ab-ew** [ytgov/yukon-ca#326]
The configuration for the default frontpage must be updated with the current homepage node, if it is not setup, everytime a deployment is executed the homepage will appear empty, currently is redirecting to node/55xxx it should be /home, i have updated the current develop environment, but once we deploy that will be lost again.

![image](https://github.com/ytgov/yukon-ca/assets/121197042/5b51fb05-49bb-4163-8885-ee7788b6ccc2)

It can be updated here:

https://develop-yukon-drupal-10.pantheonsite.io/admin/config/system/site-information

Then we need to export the configuration and commit the change.

c.c @leeomara

**Comment by ew-andrew-sus** [comment]
@w3creatives PR is merged to the 'develop' branch. Complete deployment steps if needed and check the task on [develop multidev env](https://develop-yukon-drupal-10.pantheonsite.io/) please.

**Comment by leeomara** [comment]
The homepage now loads at https://develop-yukon-drupal-10.pantheonsite.io/ and https://develop-yukon-drupal-10.pantheonsite.io/fr

**Comment by leeomara** [comment]
Noted that https://develop-yukon-drupal-10.pantheonsite.io/fr no longer works. It now returns a 404. The `/fr/accueil` URL does work: https://develop-yukon-drupal-10.pantheonsite.io/fr/accueil

**Comment by leeomara** [comment]
Confirmed that this is working correctly on dev.

**Comment by leeomara** [comment]
Looks good on `test`.
