### ISSUE TITLE
Hide the text "On" 

### ISSUE THREAD

**Issue by w3creatives** [ytgov/yukon-ca#340]
**Description:**
https://test-yukon-drupal-10.pantheonsite.io/immigrate-yukon

**Task:**
Hide "On" thats comes on top of Full Width. See screenshot

**Deliverable:**
"On" field shouldn't be visible on the page view

![Immigrate-to-the-Yukon-Yukon-ca](https://github.com/ytgov/yukon-ca/assets/150289876/44c89657-8a2a-47a3-a11d-1095b12b54a1)

**Comment by ew-andrew-sus** [comment]
@w3creatives PR is merged to the 'develop' branch. Complete deployment steps if needed and check the task on [develop multidev env](https://develop-yukon-drupal-10.pantheonsite.io/) please.

**Comment by leeomara** [comment]
Tested at https://develop-yukon-drupal-10.pantheonsite.io/immigrate-yukon. Look right.

**Comment by leeomara** [comment]
Now looks good on `test`.
