### ISSUE TITLE
Charts render as code not charts

### ISSUE THREAD

**Issue by leeomara** [ytgov/yukon-ca#342]
Pages that have chart content render the "raw" chart code instead of rendering the chart that code/config would create.

- D7: https://yukon.ca/en/statistics-and-data/economic-equality-and-employment
- D10: https://develop-yukon-drupal-10.pantheonsite.io/statistics-and-data/economic-equality-and-employment

<img width="1355" alt="Screen Shot 2024-02-12 at 1 13 10 PM" src="https://github.com/ytgov/yukon-ca/assets/93003/bbc77237-40ae-46bb-b0ec-11f2ca7c3506">

**Comment by leeomara** [comment]
Charts now look like charts on `develop`, however they exhibit a strange "drooping" behaviour -- they stretch vertically over time.

e.g. Employment insurance (EI) beneficiaries in the Yukon, by gender on https://develop-yukon-drupal-10.pantheonsite.io/en/statistics-and-data/economic-equality-and-employment

![chart-droop](https://github.com/ytgov/yukon-ca/assets/93003/2c45c0a2-dcd3-4b2d-936b-3f351c5ac08d)

**Comment by w3creatives** [comment]
We cannot see this on our end.  Which browser are you using to test it?

**Comment by leeomara** [comment]
I am able to reproduce this issue with Firefox 125.0.2 on MacOS 12.7.4.

Testing in Safari does not show this problem.

**Comment by w3creatives** [comment]
We tested on the same version of Firefox 125.0.2 on MacOS 12.6.9 and then on Firefox 125.0.3 on MacOS 14.3....but couldn't replicate the same. Please check the production website to confirm whether it exists there as well or not.

**Comment by w3creatives** [comment]
We got this issue replicated on our end and will get back with more details.

**Comment by w3creatives** [comment]
Please check this issue again and confirm.

Also see the pending PR from the last phase:

https://github.com/ytgov/yukon-ca/pull/464

**Comment by leeomara** [comment]
Looks good in UAT.
