### ISSUE TITLE
[P-3] Configuration of roles permissions

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#364]
**Description:**
Role permissions aren't configured properly

**Task:**
Configure role permissions

**Deliverable:**
Role permissions should be configured in the same way as on D7

**Comment by leeomara** [comment]
Roles have been defined. Permissions have not been carefully reviewed or synced.

**Comment by w3creatives** [comment]
We have manually reviewed and updated the permissions. Config import will update/fix any pending issues.

**Comment by leeomara** [comment]
This looks good in UAT.
