### ISSUE TITLE
Configuration of breakpoints

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#367]
**Description:**
Breakpoints aren't configured

**Task:**
Configure breakpoints

**Deliverable:**
D10 should have the same breakpoints as D7

**Comment by adrianrylski** [comment]
@leeomara @lgontard This is ready for you to test at https://global-yukon-drupal-10.pantheonsite.io/

**Comment by leeomara** [comment]
They differ a bit from D7 (middle sizes) but seem mostly fine.

Tested
- ✅ home page e.g. https://dev-yukon-drupal-10.pantheonsite.io/ 
- ✅ landing page e.g. https://dev-yukon-drupal-10.pantheonsite.io/en/find-board-committee
- ❌ basic page e.g. https://dev-yukon-drupal-10.pantheonsite.io/en/find-board-committee

For basic page, at medium small sizes, the left navigation remains and pushes the body content very far down.

![D10 breakpoint basic-page 2024-09-10](https://github.com/user-attachments/assets/a969f461-9225-4b7f-85bd-1c40f4d25a75)

**Comment by leeomara** [comment]
This issue/task will be taken over by W3 Creatives. No further work by EW is required for this issue.

**Comment by w3creatives** [comment]
You may check the following link again:

https://yukon-new-d10.w3creatives.com/docroot/en/find-board-committee

**Comment by lgontard** [comment]
@w3creatives @leeomara This is working now.
