### ISSUE TITLE
Configure Text formats

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#368]
**Description:**
Text formats:
- wetkit_wysiwyg_text
- wetkit_html_text
- plain_text
- php_code - skip (migrate the logic if needed)

**Task:**
Create and configure Text formats

**Deliverable:**
Text formats should be the same as on D7

RM: https://rm.ewdev.ca/issues/64797

**Comment by adrianrylski** [comment]
Text formats have been created and are ready for testing: https://admin-yukon-drupal-10.pantheonsite.io/

Shield credentials: ew/ewdev

Pls note that the Wetkits text formats were replaced by default ones during the migration.

**Comment by leeomara** [comment]
D10 now has:
- Basic HTML (`basic_html`)
- Restricted HTML (`restricted_html`)
- Full HTML (`full_html`)
- Plain text (`plain_text`)

This looks good.

How can I tell what has been mapped to what as part of the migrations?

**Comment by ew-andrew-sus** [comment]
**full_html** is used in all migrations (see the screenshot below how it looks like in the migration script)
![image](https://github.com/ytgov/yukon-ca/assets/123640502/4e2a4500-45cc-4eb8-8d32-a5da9dc9c7ad)

**Comment by w3creatives** [comment]
This task was done by EW. Please close if it is done.

**Comment by leeomara** [comment]
This is done.
