### ISSUE TITLE
Configure Linkit Profiles

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#369]
**Description:**
The linkit module is used on the D7 site, several fields use the module to reference internal content, and it is embedded on the ckeditor too

**Task:**
Configure Linkit Profiles

**Deliverable:**
Linkit Profiles should be the same as on D7

Jira: https://ygdevops.atlassian.net/browse/DMTPD3-12

RM: https://rm.ewdev.ca/issues/64793

**Comment by adrianrylski** [comment]
Linkit functionality has been added to both Basic and Full HTML text formats. Please test https://edit-interf-yukon-drupal-10.pantheonsite.io/ using shield credentials ew/ewdev

![Image](https://github.com/ytgov/yukon-ca/assets/169937189/d8392e46-4105-4626-b68b-4ba77619b22e)

**Comment by leeomara** [comment]
Tested in Basic page, Blog and Document. Looks good!

**Comment by w3creatives** [comment]
This task was done by EW. Please close if it is done.
