### ISSUE TITLE
Media WYSIWYG Settings

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#370]
**Description:**
There are Media WYSIWYG functionality on D7 that also should be migrated/replicated

**Task:**
Configure Media WYSIWYG Settings

**Deliverable:**
Media WYSIWYG functionality should be equal to D7

RM: https://rm.ewdev.ca/issues/64792

**Comment by adrianrylski** [comment]
A big menu module was implemented and is ready to be tested at https://edit-interf-yukon-drupal-10.pantheonsite.io/

Shield credentials: ew/ewdev

Please go to: https://edit-interf-yukon-drupal-10.pantheonsite.io/en/admin/structure/menu/manage/main

![Image](https://github.com/ytgov/yukon-ca/assets/169937189/73199ee1-cc69-4126-a30a-e940164da933)
![Image](https://github.com/ytgov/yukon-ca/assets/169937189/54699b5a-dd7e-46d5-b61b-595abf4cd270)

**Comment by lgontard** [comment]
@adrianrylski When I upload an image using the WYSIWYG media editor in D7, I get a few options before completing the upload. And after the upload, if I right click on the image there's a image properties option. I don't see that option on D10. Maybe it's hidden somewhere? We do not use these image properties much right now, but one finding from our UX assessment earlier this year was to have more images. So I expect we're going to have more images on Yukon.ca in the future.

Otherwise, the media upload icon works. The media folders and subfolders are there. File size should be limited to 64 MB

![image](https://github.com/ytgov/yukon-ca/assets/157647061/4cc17d34-c425-4625-9dff-72e7a890ce7c)
![image](https://github.com/ytgov/yukon-ca/assets/157647061/0e329810-a1cf-472d-8ece-545f0daac4af)

**Comment by adrianrylski** [comment]
@lgontard We have talked about it recently but you have never provided image sizes to implement for the Display as in D10. Could you? Thank you

**Comment by lgontard** [comment]
@adrianrylski on D7 the file size max is 64MB (terrifyingly large, but sometimes there's the need), but we do not have a pixel size (height or width) limit.

**Comment by w3creatives** [comment]
We have enabled the image resize option on the editor. Please review.

**Comment by leeomara** [comment]
That looks great. In testing, I'm not able to access that.

On UAT, I see "Allow the user to resize images" enabled at `/en/admin/config/content/formats/manage/full_html`

However, when editing, I don't see the control points in the corners, nor the resize interface (your red highlight). Not our our UAT, nor on W3 test server.

![Screenshot 2024-11-12 at 10 42 23 AM](https://github.com/user-attachments/assets/1394b3a2-65cf-4ccf-8973-c8dc113067ee)

**Comment by leeomara** [comment]
I see now that this seems to apply only to uploaded images, not managed media.

**Comment by w3creatives** [comment]
We have added image style option for the Media upload. Please review

![scr1](https://github.com/user-attachments/assets/7e3e9801-1ff1-4bb8-8870-0072d3d61550)

**Comment by leeomara** [comment]
> We have added image style option for the Media upload. Please review

@lgontard what do you think?

**Comment by lgontard** [comment]
@leeomara I'm not seeing the image style option in D10UAT. I uploaded an image and I chose an image from the media files.
<img width="346" alt="image" src="https://github.com/user-attachments/assets/c25ce7b6-b6c1-4aab-a42b-9d7ec6f444d1">

**Comment by leeomara** [comment]
Lily and I tested on W3. Please make the following changes:
- resolve the CSS issue where all even resized images are limited to 300px max width
- remove the option to upload inline images from the CKEditor toolbar. Images should only be added through "Insert media"

![Screenshot 2024-11-15 at 2 52 29 PM](https://github.com/user-attachments/assets/51d8c7d3-6895-489c-b082-88809e72245c)

**Comment by w3creatives** [comment]
CSS removed.

![Screenshot from 2024-11-20 03-31-01](https://github.com/user-attachments/assets/cace280d-970d-4604-9c0a-03ccbd83f3b4)

**Comment by lgontard** [comment]
@leeomara @w3creatives This is resolved in YG UAT
