### ISSUE TITLE
WYSIWYG Settings

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#371]
**Description:**
There is CKEditor 5 on Drupal 10 that should be configured properly

**Task:**
Configure WYSIWYG (CKEditor 5)

**Deliverable:**
WYSIWYG should have the same functionality as CKEditor 4 on D7

From DMTPD3-196:

> This applies to the body and other fields (e.g. contact, step fields)
> 
> We don’t use all of the formatting, but notable absences are:
> 
> - Table
> - Horizontal line
> - Anchor
> - Media browser (rarely used, but still needed)

From DMTPD3-85:
> - We cannot add images from the section content box
> - cannot easily create tables (not tables button)
> - No superscript and subscript
> - Cannot insert horizontal line
> - no bloc quote button

Jira:
- https://ygdevops.atlassian.net/browse/DMTPD3-196 "WYSIWYG editor missing formatting options and tools"
- https://ygdevops.atlassian.net/browse/DMTPD3-85 "Backend editor experience"
- https://ygdevops.atlassian.net/browse/DMTPD3-43 "Text format dropdown menu doesn't include WYSIWYG"
- https://ygdevops.atlassian.net/browse/DMTPD3-39 "Images can not be added in body, except through HTML"
- https://ygdevops.atlassian.net/browse/DMTPD3-30 "cannot embed video"
- https://ygdevops.atlassian.net/browse/DMTPD3-8 "Body fields should default to a rich-text editor"

RM: https://rm.ewdev.ca/issues/64790

**Comment by leeomara** [comment]
Related to https://github.com/ytgov/yukon-ca/issues/473

**Comment by adrianrylski** [comment]
This issue is ready for testing in multidev https://edit-interf-yukon-drupal-10.pantheonsite.io/en/ckeditor-5-toolbar-funcltionality

**Comment by lgontard** [comment]
@adrianrylski @leeomara The WYSIWYG is the same on D10 as it was on D7. This is ready for deploy.

**Comment by leeomara** [comment]
Increase and decrease indent and remove formatting icons are grayed out and cannot be applied. 

We do not use indent and decrease indent, and on D10 will not need remove formatting. I will create a new issue to refine the WYSIWYG toolbar.
