### ISSUE TITLE
Metatag settings

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#372]
**Description:**
Metatag isn't configured properly

**Task:**
Configure Metatag settings

**Deliverable:**
Metatag should be configured the same as on D7

RM: https://rm.ewdev.ca/issues/64799

**Comment by adrianrylski** [comment]
Issue is ready for testing in the Pantheon Multidev environment: https://admin-yukon-drupal-10.pantheonsite.io/

Shield credentials for this env are: ew/ewdev

**Comment by ew-andrew-sus** [comment]
No, it is just a general metatag configurations

**Comment by lgontard** [comment]
This looks good. I do not have permissions to change the status.

**Comment by leeomara** [comment]
This issue/task will be taken over by W3 Creatives. No further work by EW is required for this issue.

**Comment by w3creatives** [comment]
We checked the Meta tags settings again and it is already done. Please close if possible.

**Comment by leeomara** [comment]
I think we're calling this good/done.
