### ISSUE TITLE
Configure Solr and create an index and Facets

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#374]
**Description:**
There are two indexes  (might be merged into one single if possible)
- search_solr
- wetkit_database_search
The goal is to create a new index based on standard search api module and setup the fields, filters.

**Task:**
Configure Search Servers, Index, and Facets

**Deliverable:**
Search should have the same functionality as on D7

**Comment by adrianrylski** [comment]
This should be tested together with https://github.com/ytgov/yukon-ca/issues/375

**Comment by leeomara** [comment]
Looks good on dev-64782-yukon-drupal-10

**Comment by leeomara** [comment]
These look good on dev. There is still some work to do to capture YG-specific configuration (instead of Pantheon), but this issue can be closed.
