### ISSUE TITLE
Create global Search view

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#375]
**Description:**
Search views functionality is not migrated

**Task:**
Migrate Search Views

**Deliverable:**
D10 should have the same search functionality as D7

D7 currently has:
- https://yukon.ca/en/search
- https://yukon.ca/en/documents
- https://yukon.ca/en/events
- https://yukon.ca/en/forms
- https://yukon.ca/en/news (is this a Search view?)
- https://yukon.ca/en/places

_Dependencies:_
- [x] #374

https://rm.ewdev.ca/issues/64783

**Comment by leeomara** [comment]
Overall this looks good.

Comparing D7 and D10, I think there might be places were we want to better understand the reasons for differences

| Query  | D7 | D10 |
|---|---|--|
| "Extended Producer Responsibility" (news) | [D7 10 results](https://yukon.ca/en/search?query=%22Extended%20Producer%20Responsibility%22&type[3]=3&field_department_term=All) | [D10 5 results](https://dev-64782-yukon-drupal-10.pantheonsite.io/en/search?query=%22Extended+Producer+Responsibility%22&type%5B3%5D=3&department=All) |
| morel mushrooms (events) | [D7 no results](https://yukon.ca/en/search?query=morel%20mushrooms&type[4]=4&field_department_term=All) | [D10 3 results](https://dev-64782-yukon-drupal-10.pantheonsite.io/en/search?query=morel+mushrooms&type%5B4%5D=4&department=All) |
| nominee program (documents) | [D7 800 results](https://yukon.ca/en/search?query=nominee%20program&type[2]=2&field_department_term=All) | [D10 2,600 results](https://dev-64782-yukon-drupal-10.pantheonsite.io/en/search?query=nominee+program&type%5B2%5D=2&department=All) |
| drivers abstract (web page) | [D7 67 results](https://yukon.ca/en/search?query=drivers%20abstract&type[1]=1&field_department_term=All) | [D10 21 results](https://dev-64782-yukon-drupal-10.pantheonsite.io/en/search?query=drivers+abstract&type%5B1%5D=1&department=All) |

**Comment by leeomara** [comment]
✅ This looks good in YG dev.
