### ISSUE TITLE
Multilingual/Translation configuration

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#377]
**Description:**
Multilingual/Translation settings aren't completely configured.

**Task:**
Complete Multilingual/Translation configuration

**Deliverable:**
There should be the same Multilingual/Translation settings as on D7

RM: https://rm.ewdev.ca/issues/64801

**Comment by adrianrylski** [comment]
@leeomara and @lgontard This issue is ready for testing in multidev https://translation-yukon-drupal-10.pantheonsite.io/en/admin/config/regional/

**Comment by leeomara** [comment]
Settings and updated Content list looks good.

https://translation-yukon-drupal-10.pantheonsite.io/en/admin/content

**Comment by w3creatives** [comment]
EW worked on this task. Please close if complete.

**Comment by leeomara** [comment]
This is, broadly speaking, done.
