### ISSUE TITLE
[P-1] Paragraphs - Campground event

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#378]
**Description:**
Paragraph "Campground event" isn't migrated

**Task:**
Migrate Paragraph "Campground event"

**Deliverable:**
 Paragraph "Campground event" should be migrated

**Comment by w3creatives** [comment]
We have migrated the Campground event.  Please check and confirm.

**Comment by leeomara** [comment]
On UAT, reviewing the list of Paragraphs types (`en/admin/structure/paragraphs_type`), I don't see "Campground event (campground_event)".

**Comment by leeomara** [comment]
Based on research, it appears that this paragraph type has never been used.

We should not migrate this.
