### ISSUE TITLE
[P-2] Campground views

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#381]
**Description:**
Views:
- campground_or_recreations_site

**Task:**
Recreate "campground_or_recreations_site" view

**Deliverable:**
"campground_or_recreations_site" view should be recreated and properly placed

**Comment by leeomara** [comment]
The view `find_a_campground_or_recreation_site` has been created. It has 2 blocks

1. Backcountry campgrounds
2. Find a campground or recreation site

There's a bug in UAT where no content is returned by these views, but I'll close this issue and track that problem in #257.
