### ISSUE TITLE
[P-2] Places configuration

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#382]
**Description:**
- Pathauto patterns
- Breadcrumbs
- Field group"

**Task:**
Complete Places CT configuration

**Deliverable:**
Places CT should be configured the same as on D7

**Comment by leeomara** [comment]
EF reported: 
> ... breadcrumbs seem same; main difference is that D10 not showing "featured events"

**Comment by w3creatives** [comment]
This page is showing featured events on D7 and we discussed not showing events on the places page on D10.  Let us know if we need to change something here.

**Comment by leeomara** [comment]
Quite right. My mistake.

This looks good on UAT.
