### ISSUE TITLE
[P-2] Places Views

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#383]
**Description:**
Views:
- views--exp-places_listing-block_1
- views-places_listing-block_1
- views-places_listing-block_2

**Task:**
Recreate Views

**Deliverable:**
All Places views should be recreated and properly placed

**Comment by leeomara** [comment]
Need to more clearly define what those blocks are and where to go to confirm if this work is complete.

**Comment by leeomara** [comment]
New (single) Places listing view (block) is set up in UAT.

On D7 there were some other view displays, but I don't believe they were being used.
