### ISSUE TITLE
[P-2] Engagement panels

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#384]
**Description:**
 D7 Panels
- Public engagements "Panels"
- Layouts
Should be recreated by available D10 features

**Task:**
Recreate panels functionality

**Deliverable:**
All panels functionality should be recreated

**Comment by w3creatives** [comment]
Engagement panels are replaced with custom code as agreed:

https://yukon-new-d10.w3creatives.com/docroot/engagements

**Comment by leeomara** [comment]
Looks good on UAT.
