### ISSUE TITLE
Missing Secondary Content Translations

### ISSUE THREAD

**Issue by w3creatives** [ytgov/yukon-ca#410]
Landing page content type secondary content is missing title translations (French titles).

![image](https://github.com/ytgov/yukon-ca/assets/150289876/80a97546-2610-4f62-9b88-275e8a71db23)

**Comment by ew-andrew-sus** [comment]
@w3creatives PR is merged to the 'develop' branch. Complete deployment steps if needed and check the task on [develop multidev env](https://develop-yukon-drupal-10.pantheonsite.io/) please.

**Comment by leeomara** [comment]
This looks good in `develope` and `dev`. E.g. https://dev-yukon-drupal-10.pantheonsite.io/fr/immigration

Not yet in `test`.

**Comment by w3creatives** [comment]
Please run <root domain>/custom_migrate URL to fix this.

**Comment by leeomara** [comment]
Looks good on UAT.
