### ISSUE TITLE
Set default language URL

### ISSUE THREAD

**Issue by w3creatives** [ytgov/yukon-ca#415]
Specify "en" as the English language parameter in the URL and passing in the language code.

**Comment by leeomara** [comment]
| Site ↓ / Language → | English | French |
|------|-----|------|
| W3 server | ✅ `/en` | ❌ `/fr/accueil` |
| UAT | ❌ `/` | ❌ `/fr/accueil` |

**Comment by w3creatives** [comment]
This should be working if URL alias migration is completed as documented.

**Comment by leeomara** [comment]
Testing on UAT I get:
- ✅ English: `/en`
- ❌ French: `/fr/node/51`

**Comment by w3creatives** [comment]
We ran the migration this weekend and it works as expected. Please consider the following URL for verifying this task only:

https://27.yukon-w3-d10.w3creatives.com/

**Comment by leeomara** [comment]
On the W3 test server (27....), I get

- ✅ English `/en`
- 🟠 French  `/fr/accueil`
- 🟠 English link from French page is to `/en/accueil`

I'm okay closing this as working and opening a new, low priority issue to improve the URLs further still. We can also look at server-side redirect or proxying to accomplish the intended result.

**Comment by lgontard** [comment]
@leeomara @w3creatives This is resolved in YG UAT
