### ISSUE TITLE
Sidebar not showing on various content types

### ISSUE THREAD

**Issue by w3creatives** [ytgov/yukon-ca#436]
Sidebar is not showing on various content types. It was reported for Basic page only.

**Comment by ew-andrew-sus** [comment]
@w3creatives PR is merged to the 'develop' branch. Complete deployment steps if needed and check the task on [develop multidev env](https://develop-yukon-drupal-10.pantheonsite.io/) please.

**Comment by leeomara** [comment]
This looks good on UAT.
