### ISSUE TITLE
Header & Footer Layouts - Sitewide

### ISSUE THREAD

**Issue by w3creatives** [ytgov/yukon-ca#459]
**Header** - Translation selector and burger menu are displayed.
**Footer** - Yukon logo, Aurora graphic are zoomed out (First picture is D10 and second D7)

 
![Home-Yukon-ca](https://github.com/ytgov/yukon-ca/assets/150289876/df6fd63a-9264-4722-9a46-aa5d06d1422e)
![Home-Government-of-Yukon](https://github.com/ytgov/yukon-ca/assets/150289876/17545676-b93c-406f-b44b-dcf945dcdc77)

Jira:
- https://ygdevops.atlassian.net/browse/DMTPD3-130
- https://ygdevops.atlassian.net/browse/DMTPD3-126
- https://ygdevops.atlassian.net/browse/DMTPD3-137
- https://ygdevops.atlassian.net/browse/DMTPD3-144
- https://ygdevops.atlassian.net/browse/DMTPD3-148
- https://ygdevops.atlassian.net/browse/DMTPD3-158
- https://ygdevops.atlassian.net/browse/DMTPD3-152

**Comment by leeomara** [comment]
Looks good in dev. See https://dev-yukon-drupal-10.pantheonsite.io/en/home

**Comment by adrianrylski** [comment]
@leeomara This issue does not exist anymore. 
![Screenshot from Adrian Rylski 2024-07-12 at 09 40 34@2x](https://github.com/user-attachments/assets/490572b5-5135-4633-8bbe-32b2ec4032a5)

**Comment by leeomara** [comment]
This issue/task will be taken over by W3 Creatives. No further work by EW is required for this issue.

**Comment by w3creatives** [comment]
All translations are done. 
Copyright also hyperlinked.

**Comment by leeomara** [comment]
This looks good in UAT.
