### ISSUE TITLE
Menu link - editing menu is too large to use

### ISSUE THREAD

**Issue by adrianrylski** [ytgov/yukon-ca#472]
Add Big Menu https://www.drupal.org/project/bigmenu

![D10 landing page level 2 menu-full-on 2024-04-03](https://github.com/ytgov/yukon-ca/assets/93003/be2a018b-35ba-4d6f-8d83-e9082546e1b7)

![image-20240517-212609](https://github.com/ytgov/yukon-ca/assets/93003/1c75c6ae-f16c-4a5d-89d5-f99ee9b1f0e4)

Jira: https://ygdevops.atlassian.net/browse/DMTPD3-29
RM: https://rm.ewdev.ca/issues/64795

**Comment by adrianrylski** [comment]
@leeomara, Could you add priority to this one? Thank you

**Comment by adrianrylski** [comment]
A big menu module was implemented and is ready to be tested at https://edit-interf-yukon-drupal-10.pantheonsite.io/

Shield credentials: ew/ewdev

Please go to: https://edit-interf-yukon-drupal-10.pantheonsite.io/en/admin/structure/menu/manage/main

![Image](https://github.com/ytgov/yukon-ca/assets/169937189/73199ee1-cc69-4126-a30a-e940164da933)
![Image](https://github.com/ytgov/yukon-ca/assets/169937189/54699b5a-dd7e-46d5-b61b-595abf4cd270)

**Comment by leeomara** [comment]
I don't see a changed menu item selection interface. For example, when creating a new basic page

https://edit-interf-yukon-drupal-10.pantheonsite.io/en/node/add/basic_page

![Image](https://github.com/ytgov/yukon-ca/assets/93003/d2ced5e2-b46d-4687-914a-21261cd31fef)

**Comment by ew-andrew-sus** [comment]
I also improved the node add/edit widget 
![image](https://github.com/ytgov/yukon-ca/assets/123640502/564ad584-e07f-4799-8d68-a0d42efac08c)
@leeomara please check it now

**Comment by lgontard** [comment]
Tested as a basic page, multistep page, LPL2 and topics. The nesting works. 

@adrianrylski should I make the two issues below into another issue?
See screengrab: the list of categories is not in alphabetical order after Outdoor recreation and wildlife. 
Everything from "Contact the government" down should not be in the dropdown menu

![Image](https://github.com/ytgov/yukon-ca/assets/157647061/f1d1dce2-930e-4943-ab65-ac9ee58b028c)

**Comment by leeomara** [comment]
Menu order item is already an issue, see 

- https://github.com/ytgov/yukon-ca/issues/297

**Comment by adrianrylski** [comment]
@leeomara This issue is not related to the Big Menu module

**Comment by leeomara** [comment]
This works perfect now! Tested at `edit-interf-yukon-drupal-10`

**Comment by leeomara** [comment]
✅ This looks good in UAT.
