### ISSUE TITLE
Body fields should default to a rich-text editor

### ISSUE THREAD

**Issue by adrianrylski** [ytgov/yukon-ca#473]
When creating new records, HTML content fields (body/description/etc.) should default to a rich text editor.

Current many default to “Basic HTML”, which shows no rich-text-editor.

Jira: https://ygdevops.atlassian.net/browse/DMTPD3-8

**Comment by adrianrylski** [comment]
@leeomara and @lgontard This issue is ready for testing in multidev https://edit-interf-yukon-drupal-10.pantheonsite.io/en/ckeditor-5-toolbar-funcltionality Default rich text format is Full HTML

**Comment by lgontard** [comment]
@adrianrylski @leeomara The default rick text format is FULL HTML. This is ready to go.

**Comment by w3creatives** [comment]
Task completed by EW. Please close if done.
