### ISSUE TITLE
Config import error TypeError on ReverseContainer::generateServiceIdHash

### ISSUE THREAD

**Issue by leeomara** [ytgov/yukon-ca#483]
When importing configuration on a new/blank site, I get this error

> `TypeError: Drupal\Component\DependencyInjection\ReverseContainer::generateServiceIdHash(): Argument #1 ($object) must be of type object, null given in Drupal\Component\DependencyInjection\ReverseContainer->generateServiceIdHash() (line 87 of /var/www/docroot/core/lib/Drupal/Component/DependencyInjection/ReverseContainer.php).`

The workaround is to re-run `config:import`, which seems to succeed on subsequent runs.

**Comment by w3creatives** [comment]
We recommend running **config:import** three times at least. Only the first run will show errors.

**Comment by leeomara** [comment]
As the workaround is now documented in the Readme, I feel like we can close this.
