### ISSUE TITLE
Core, modules, security update > D 10.3

### ISSUE THREAD

**Issue by adrianrylski** [ytgov/yukon-ca#503]
@leeomara  Is it time for us to make updates to Drupal

![Image](https://github.com/ytgov/yukon-ca/assets/169937189/978e11f1-6c87-4978-a772-d3aa3aa127d7)

**Comment by adrianrylski** [comment]
@leeomara Updates were merged into the master and deployed on DEV. Ready for testing 

1. Core is updated to latest Drupal 10.3.1 - https://dev-yukon-drupal-10.pantheonsite.io/en/admin/reports/status
2. All contrib modules are up to date - All of your projects are up to date - https://dev-yukon-drupal-10.pantheonsite.io/en/admin/modules/update
3. Configuration is synced and clean - The staged configuration is identical to the active configuration - https://dev-yukon-drupal-10.pantheonsite.io/en/admin/config/development/configuration

**Comment by adrianrylski** [comment]
![Image](https://github.com/user-attachments/assets/5e4b4f79-6321-471f-b943-b98c813d27a6)



![Image](https://github.com/user-attachments/assets/29efeb5a-58cb-4cf9-b17a-ca43d38ada73)

**Comment by leeomara** [comment]
This issue/task will be taken over by W3 Creatives. No further work by EW is required for this issue.

**Comment by leeomara** [comment]
This has landed and can now be closed.
