### ISSUE TITLE
D7/D10 search results differences

### ISSUE THREAD

**Issue by adrianrylski** [ytgov/yukon-ca#507]
Overall this looks good.

Comparing D7 and D10, I think there might be places were we want to better understand the reasons for differences

| Query  | D7 | D10 |
|---|---|--|
| "Extended Producer Responsibility" (news) | [D7 10 results](https://yukon.ca/en/search?query=%22Extended%20Producer%20Responsibility%22&type[3]=3&field_department_term=All) | [D10 5 results](https://dev-64782-yukon-drupal-10.pantheonsite.io/en/search?query=%22Extended+Producer+Responsibility%22&type%5B3%5D=3&department=All) |
| morel mushrooms (events) | [D7 no results](https://yukon.ca/en/search?query=morel%20mushrooms&type[4]=4&field_department_term=All) | [D10 3 results](https://dev-64782-yukon-drupal-10.pantheonsite.io/en/search?query=morel+mushrooms&type%5B4%5D=4&department=All) |
| nominee program (documents) | [D7 800 results](https://yukon.ca/en/search?query=nominee%20program&type[2]=2&field_department_term=All) | [D10 2,600 results](https://dev-64782-yukon-drupal-10.pantheonsite.io/en/search?query=nominee+program&type%5B2%5D=2&department=All) |
| drivers abstract (web page) | [D7 67 results](https://yukon.ca/en/search?query=drivers%20abstract&type[1]=1&field_department_term=All) | [D10 21 results](https://dev-64782-yukon-drupal-10.pantheonsite.io/en/search?query=drivers+abstract&type%5B1%5D=1&department=All) |

_Originally posted by @leeomara in https://github.com/ytgov/yukon-ca/issues/375#issuecomment-2197702638_

**Comment by adrianrylski** [comment]
| Query  | D7 | D10 | Notes |
|---|---|--|--|
| "Extended Producer Responsibility" (news) | [D7 10 results](https://yukon.ca/en/search?query=%22Extended%20Producer%20Responsibility%22&type[3]=3&field_department_term=All) | [D10 5 results](https://dev-64782-yukon-drupal-10.pantheonsite.io/en/search?query=%22Extended+Producer+Responsibility%22&type%5B3%5D=3&department=All) | after adding missing fields to the D10 index we have even move results in D10 |
| morel mushrooms (events) | [D7 no results](https://yukon.ca/en/search?query=morel%20mushrooms&type[4]=4&field_department_term=All) | [D10 3 results](https://dev-64782-yukon-drupal-10.pantheonsite.io/en/search?query=morel+mushrooms&type%5B4%5D=4&department=All) | We are not searching strict string like in the previous request, and in the D10 we have matches for 'mushrooms' |
| nominee program (documents) | [D7 800 results](https://yukon.ca/en/search?query=nominee%20program&type[2]=2&field_department_term=All) | [D10 2,600 results](https://dev-64782-yukon-drupal-10.pantheonsite.io/en/search?query=nominee+program&type%5B2%5D=2&department=All) | We have another PDF indexing logic and seems it is better than in D7 |
| drivers abstract (web page) | [D7 67 results](https://yukon.ca/en/search?query=drivers%20abstract&type[1]=1&field_department_term=All) | [D10 21 results](https://dev-64782-yukon-drupal-10.pantheonsite.io/en/search?query=drivers+abstract&type%5B1%5D=1&department=All) | We have more results after adding missing fields into the index |

**Comment by leeomara** [comment]
Okay, here's what I now see.

| Query  | D7 | D10 | Notes |
|---|---|--|--|
| "Extended Producer Responsibility" (news) | [10 results](https://yukon.ca/en/search?query=%22Extended%20Producer%20Responsibility%22&type[3]=3&field_department_term=All) | [~5~ **11** results](https://dev-64782-yukon-drupal-10.pantheonsite.io/en/search?query=%22Extended+Producer+Responsibility%22&type%5B3%5D=3&department=All) | 👍 Results look good |
| morel mushrooms (events) | [no results](https://yukon.ca/en/search?query=morel%20mushrooms&type[4]=4&field_department_term=All) | [3 results](https://dev-64782-yukon-drupal-10.pantheonsite.io/en/search?query=morel+mushrooms&type%5B4%5D=4&department=All) | 👍 makes sense |
| nominee program (documents) | [800 results](https://yukon.ca/en/search?query=nominee%20program&type[2]=2&field_department_term=All) | [~2,600~ 2,700 results](https://dev-64782-yukon-drupal-10.pantheonsite.io/en/search?query=nominee+program&type%5B2%5D=2&department=All) | Okay |
| drivers abstract (web page) | [67 results](https://yukon.ca/en/search?query=drivers%20abstract&type[1]=1&field_department_term=All) | [~21~ 70 results](https://dev-64782-yukon-drupal-10.pantheonsite.io/en/search?query=drivers+abstract&type%5B1%5D=1&department=All) | 👍 Results look good |

**Comment by leeomara** [comment]
I'm measuring search performance against the top 25 searches done for the last calendar year.

Here's a large, very spammy-looking table that provides links to search results across 3 sites:

- Existing Drupal site (D7). What we currently have/do
- Google `{term} site:yukon.ca -open.yukon.ca -laws.yukon.ca -service.yukon.ca`. A reference "good" result set
- Multidev (currently `dev-64782-yukon-drupal-10`). The new D10 version

This can be useful for comparisons.

| Top 25 (2023)        | Yukon.ca (D7)                                                                   | Google                                                                                                                          | Multidev                                                                                                       |
| -------------------- | ------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------------------------------------------- |
| jobs                 | [jobs](https://yukon.ca/en/search?query=jobs)                                   | [jobs](https://www.google.com/search?q=abstract+site:yukon.ca+-open.yukon.ca+-laws.yukon.ca+-service.yukon.ca)                  | [jobs](https://dev-64782-yukon-drupal-10.pantheonsite.io/en/search?query=jobs)                                 |
| nominee program      | [nominee program](https://yukon.ca/en/search?query=nominee%20program)           | [nominee program](https://www.google.com/search?q=budget+site:yukon.ca+-open.yukon.ca+-laws.yukon.ca+-service.yukon.ca)         | [nominee program](https://dev-64782-yukon-drupal-10.pantheonsite.io/en/search?query=nominee+program)           |
| vehicle registration | [vehicle registration](https://yukon.ca/en/search?query=vehicle%20registration) | [vehicle registration](https://www.google.com/search?q=camping+site:yukon.ca+-open.yukon.ca+-laws.yukon.ca+-service.yukon.ca)   | [vehicle registration](https://dev-64782-yukon-drupal-10.pantheonsite.io/en/search?query=vehicle+registration) |
| covid                | [covid](https://yukon.ca/en/search?query=covid)                                 | [covid](https://www.google.com/search?q=careers+site:yukon.ca+-open.yukon.ca+-laws.yukon.ca+-service.yukon.ca)                  | [covid](https://dev-64782-yukon-drupal-10.pantheonsite.io/en/search?query=covid)                               |
| job                  | [job](https://yukon.ca/en/search?query=job)                                     | [job](https://www.google.com/search?q=covid+site:yukon.ca+-open.yukon.ca+-laws.yukon.ca+-service.yukon.ca)                      | [job](https://dev-64782-yukon-drupal-10.pantheonsite.io/en/search?query=job)                                   |
| staff directory      | [staff directory](https://yukon.ca/en/search?query=staff%20directory)           | [staff directory](https://www.google.com/search?q=dental+site:yukon.ca+-open.yukon.ca+-laws.yukon.ca+-service.yukon.ca)         | [staff directory](https://dev-64782-yukon-drupal-10.pantheonsite.io/en/search?query=staff+directory)           |
| directory            | [directory](https://yukon.ca/en/search?query=directory)                         | [directory](https://www.google.com/search?q=directory+site:yukon.ca+-open.yukon.ca+-laws.yukon.ca+-service.yukon.ca)            | [directory](https://dev-64782-yukon-drupal-10.pantheonsite.io/en/search?query=directory)                       |
| mining tenure        | [mining tenure](https://yukon.ca/en/search?query=mining%20tenure)               | [mining tenure](https://www.google.com/search?q=drivers+abstract+site:yukon.ca+-open.yukon.ca+-laws.yukon.ca+-service.yukon.ca) | [mining tenure](https://dev-64782-yukon-drupal-10.pantheonsite.io/en/search?query=mining+tenure)               |
| drivers abstract     | [drivers abstract](https://yukon.ca/en/search?query=drivers%20abstract)         | [drivers abstract](https://www.google.com/search?q=immigration+site:yukon.ca+-open.yukon.ca+-laws.yukon.ca+-service.yukon.ca)   | [drivers abstract](https://dev-64782-yukon-drupal-10.pantheonsite.io/en/search?query=drivers+abstract)         |
| vacation             | [vacation](https://yukon.ca/en/search?query=vacation)                           | [vacation](https://www.google.com/search?q=insurance+site:yukon.ca+-open.yukon.ca+-laws.yukon.ca+-service.yukon.ca)             | [vacation](https://dev-64782-yukon-drupal-10.pantheonsite.io/en/search?query=vacation)                         |
| insurance            | [insurance](https://yukon.ca/en/search?query=insurance)                         | [insurance](https://www.google.com/search?q=job+site:yukon.ca+-open.yukon.ca+-laws.yukon.ca+-service.yukon.ca)                  | [insurance](https://dev-64782-yukon-drupal-10.pantheonsite.io/en/search?query=insurance)                       |
| map                  | [map](https://yukon.ca/en/search?query=map)                                     | [map](https://www.google.com/search?q=jobs+site:yukon.ca+-open.yukon.ca+-laws.yukon.ca+-service.yukon.ca)                       | [map](https://dev-64782-yukon-drupal-10.pantheonsite.io/en/search?query=map)                                   |
| mining               | [mining](https://yukon.ca/en/search?query=mining)                               | [mining](https://www.google.com/search?q=legislation+site:yukon.ca+-open.yukon.ca+-laws.yukon.ca+-service.yukon.ca)             | [mining](https://dev-64782-yukon-drupal-10.pantheonsite.io/en/search?query=mining)                             |
| abstract             | [abstract](https://yukon.ca/en/search?query=abstract)                           | [abstract](https://www.google.com/search?q=map+site:yukon.ca+-open.yukon.ca+-laws.yukon.ca+-service.yukon.ca)                   | [abstract](https://dev-64782-yukon-drupal-10.pantheonsite.io/en/search?query=abstract)                         |
| legislation          | [legislation](https://yukon.ca/en/search?query=legislation)                     | [legislation](https://www.google.com/search?q=maps+site:yukon.ca+-open.yukon.ca+-laws.yukon.ca+-service.yukon.ca)               | [legislation](https://dev-64782-yukon-drupal-10.pantheonsite.io/en/search?query=legislation)                   |
| whitehorse           | [whitehorse](https://yukon.ca/en/search?query=whitehorse)                       | [whitehorse](https://www.google.com/search?q=medical+travel+site:yukon.ca+-open.yukon.ca+-laws.yukon.ca+-service.yukon.ca)      | [whitehorse](https://dev-64782-yukon-drupal-10.pantheonsite.io/en/search?query=whitehorse)                     |
| medical travel       | [medical travel](https://yukon.ca/en/search?query=medical%20travel)             | [medical travel](https://www.google.com/search?q=mining+site:yukon.ca+-open.yukon.ca+-laws.yukon.ca+-service.yukon.ca)          | [medical travel](https://dev-64782-yukon-drupal-10.pantheonsite.io/en/search?query=medical+travel)             |
| maps                 | [maps](https://yukon.ca/en/search?query=maps)                                   | [maps](https://www.google.com/search?q=mining+tenure+site:yukon.ca+-open.yukon.ca+-laws.yukon.ca+-service.yukon.ca)             | [maps](https://dev-64782-yukon-drupal-10.pantheonsite.io/en/search?query=maps)                                 |
| immigration          | [immigration](https://yukon.ca/en/search?query=immigration)                     | [immigration](https://www.google.com/search?q=nominee+program+site:yukon.ca+-open.yukon.ca+-laws.yukon.ca+-service.yukon.ca)    | [immigration](https://dev-64782-yukon-drupal-10.pantheonsite.io/en/search?query=immigration)                   |
| school calendar      | [school calendar](https://yukon.ca/en/search?query=school%20calendar)           | [school calendar](https://www.google.com/search?q=pharmacare+site:yukon.ca+-open.yukon.ca+-laws.yukon.ca+-service.yukon.ca)     | [school calendar](https://dev-64782-yukon-drupal-10.pantheonsite.io/en/search?query=school+calendar)           |
| budget               | [budget](https://yukon.ca/en/search?query=budget)                               | [budget](https://www.google.com/search?q=school+calendar+site:yukon.ca+-open.yukon.ca+-laws.yukon.ca+-service.yukon.ca)         | [budget](https://dev-64782-yukon-drupal-10.pantheonsite.io/en/search?query=budget)                             |
| dental               | [dental](https://yukon.ca/en/search?query=dental)                               | [dental](https://www.google.com/search?q=staff+directory+site:yukon.ca+-open.yukon.ca+-laws.yukon.ca+-service.yukon.ca)         | [dental](https://dev-64782-yukon-drupal-10.pantheonsite.io/en/search?query=dental)                             |
| pharmacare           | [pharmacare](https://yukon.ca/en/search?query=pharmacare)                       | [pharmacare](https://www.google.com/search?q=vacation+site:yukon.ca+-open.yukon.ca+-laws.yukon.ca+-service.yukon.ca)            | [pharmacare](https://dev-64782-yukon-drupal-10.pantheonsite.io/en/search?query=pharmacare)                     |
| camping              | [camping](https://yukon.ca/en/search?query=camping)                             | [camping](https://www.google.com/search?q=vehicle+registration+site:yukon.ca+-open.yukon.ca+-laws.yukon.ca+-service.yukon.ca)   | [camping](https://dev-64782-yukon-drupal-10.pantheonsite.io/en/search?query=camping)                           |
| careers              | [careers](https://yukon.ca/en/search?query=careers)                             | [careers](https://www.google.com/search?q=whitehorse+site:yukon.ca+-open.yukon.ca+-laws.yukon.ca+-service.yukon.ca)             | [careers](https://dev-64782-yukon-drupal-10.pantheonsite.io/en/search?query=careers)                           |

**Comment by leeomara** [comment]
Based an analysis of the multidev search results from today, I have a list of which URLs Google returned in the top 10, that Drupal misses. It's another big table (176 rows), across the measured 25 searches.

**Comment by leeomara** [comment]
Based on a manual review of the differences in search results for "abstract", "budget", "careers" and "mining", I suspected  that maybe Landing Page and Landing Page level 2 is not being included in search results.

Looking at the [Search API index configuration in multidev](https://dev-64782-yukon-drupal-10.pantheonsite.io/en/admin/config/search/search-api/index/global/edit) confirm this.

![Screenshot 2024-07-04 at 9 00 28 AM](https://github.com/ytgov/yukon-ca/assets/93003/3f618af7-e21c-408d-9703-06b6d0cb218a)

**Comment by adrianrylski** [comment]
@leeomara, missing content types have been added to the index. The index was re-run. Please, re-test.

**Comment by leeomara** [comment]
I'm not able to re-test search on YG UAT because an issue (#546) is preventing me from running migration in that environment.

**Comment by w3creatives** [comment]
This issue belongs to EW and #546 is closed, please see if this issue is resolved and can be closed.

**Comment by leeomara** [comment]
This issue can be closed. I'll likely open a new issue for changes we want to make to search in order to improve performance.
