### ISSUE TITLE
Migrate D7 workflows [post-implementation]

### ISSUE THREAD

**Issue by adrianrylski** [ytgov/yukon-ca#509]
Depends on: #508 

Acceptance criteria:
Implement migration for newly created D10 workflow and migrate.

**Comment by leeomara** [comment]
Tested a number of draft pages from Yukon.ca D7, they were also in draft in D10. Looks good.

**Comment by leeomara** [comment]
This is related to: 

- https://github.com/ytgov/yukon-ca/issues/624
- https://github.com/ytgov/yukon-ca/issues/616

**Comment by leeomara** [comment]
Closing this, will leave #616 open.
