### ISSUE TITLE
Pantheon Advanced Page Cache sends very large headers

### ISSUE THREAD

**Issue by leeomara** [ytgov/yukon-ca#512]
In YGs environment, the `pantheon_advanced_page_cache` module leads to overly large HTTP headers, which exceeds the maximum allowed by our reverse proxy.

In our test environments we've been working around this by disabling that module

```
drush pm:uninstall pantheon_advanced_page_cache
```

Is there a nicer way to have this module enabled when deployed to Pantheon, but not enabled when deployed elsewhere?

**Comment by leeomara** [comment]
With this module enabled, our reverse proxy often errors with this message:

> 502 Bad Gateway

In the error log, the reverse proxy reports 

> upstream sent too big header while reading response header from upstream

Looking at output from the upstream, we can see that when this module is enabled, the HTTP header includes a very large `Surrogate-Key:` value.

**Comment by w3creatives** [comment]
Since Pantheon is not going to be involved in production launch, should we close this ticket?

**Comment by leeomara** [comment]
We shouldn't close this issue until the problem is resolved. On our production systems, having this module enabled will continue to cause issues.

I'm happy to do away with this module.

**Comment by w3creatives** [comment]
Ok. We will deactivate the module in composer.json.

**Comment by w3creatives** [comment]
We have disabled the menu in the [latest PR](https://github.com/ytgov/yukon-ca/pull/664).

**Comment by leeomara** [comment]
Testing on dev, `drush config:import` fails with errors about pantheon_advanced_page_cache.

Full error message:

```
[error]  Drupal\Core\Config\ConfigImporterException: There were errors validating the config synchronization.
Site UUID in source storage does not match the target storage.
Unable to install the <em class="placeholder">pantheon_advanced_page_cache</em> module since it does not exist.

Configuration <em class="placeholder">low_seetings.settings</em> depends on the 
<em class="placeholder">low_seetings</em> extension that will not be installed after import. in Drupal\Core\Config\ConfigImporter->validate() (line 823 of /var/www/yukon-ca-d10/docroot/core/lib/Drupal/Core/Config/ConfigImporter.php).
```

It looks like there's still a reference to `pantheon_advanced_page_cache` in `config/default/core.extension.yml`

**Comment by leeomara** [comment]
@w3creatives also the config file `config/default/pantheon_advanced_page_cache.settings.yml` references the module and needs to be removed.

**Comment by leeomara** [comment]
Now that https://github.com/ytgov/yukon-ca/pull/669 landed, this is good.
