### ISSUE TITLE
Adjust theming post date format updates

### ISSUE THREAD

**Issue by adrianrylski** [ytgov/yukon-ca#515]
Derives from #465 

Most of these look great. Some of the ones that have ranges seem to be missing a space after the word "to".

See
- https://dev-64840-2-yukon-drupal-10.pantheonsite.io//en/events/managing-conflict-after-separation-or-divorce-1
- https://dev-64840-2-yukon-drupal-10.pantheonsite.io/en/places-2

Notably, Campgrounds, which have ranges seem fine. E.g. https://dev-64840-2-yukon-drupal-10.pantheonsite.io/en/outdoor-recreation-and-wildlife/camping/site/tatchun-creek-campground

![Yukon ca d10 465 Screenshot 2024-07-12 at 2 37 27 PM](https://github.com/user-attachments/assets/1f93c503-103d-455d-b38e-6b1048d94889)

![Yukon ca d10 465 Screenshot 2024-07-12 at 2 37 17 PM](https://github.com/user-attachments/assets/ab3be8c7-bba7-4ac1-8467-090fc7e292ff)

**Comment by adrianrylski** [comment]
@leeomara @lgontard Issues is ready for testing https://dev-67138-yukon-drupal-10.pantheonsite.io/

**Comment by leeomara** [comment]
Tested on a local instance and it look good.

Also tested:
- https://dev-yukon-drupal-10.pantheonsite.io/en/arts-and-culture/events
- https://dev-yukon-drupal-10.pantheonsite.io/en/events/managing-conflict-after-separation-or-divorce-3

**Comment by leeomara** [comment]
This issue/task will be taken over by W3 Creatives. No further work by EW is required for this issue.

**Comment by leeomara** [comment]
Looks good on W3 server

**Comment by leeomara** [comment]
Looks good on UAT.
