### ISSUE TITLE
Create Peak Times view block

### ISSUE THREAD

**Issue by adrianrylski** [ytgov/yukon-ca#516]
![Image](https://github.com/user-attachments/assets/5c39391c-c113-4460-a9b5-5fc7d328b852)

RM [67139](https://rm.ewdev.ca/issues/67139)

**Comment by w3creatives** [comment]
We have created a view for this. Please check and confirm.

**Comment by leeomara** [comment]
- ✅ This look good for individual campgrounds, both on the top-level (find campground) page, and per-campground pages (on UAT)
- ❌ The Peak times overview (is that even a block?) is broken on the top-level page. This is probably best addressed separately in #633
