### ISSUE TITLE
Create Find a campground or recreation site view block

### ISSUE THREAD

**Issue by adrianrylski** [ytgov/yukon-ca#517]
![Image](https://github.com/user-attachments/assets/1e6db98a-9911-4973-8dab-708162faa122)

RM [67140](https://rm.ewdev.ca/issues/67140)

**Comment by w3creatives** [comment]
We have created a view for this. Please check and confirm.

**Comment by leeomara** [comment]
Notwithstanding the issue identified below, this is working well on UAT

- https://github.com/ytgov/yukon-ca/issues/257
