### ISSUE TITLE
Create Campgrounds and recreation sites view block

### ISSUE THREAD

**Issue by adrianrylski** [ytgov/yukon-ca#518]
![Image](https://github.com/user-attachments/assets/d16986cd-2e69-4b45-8fd9-b01d48b3f007)

RM [67141](https://rm.ewdev.ca/issues/67141)

**Comment by leeomara** [comment]
This appears related to:
- #381 
- #257
- #523  (Phase E)
- possibly also #261

**Comment by w3creatives** [comment]
Please review:

https://yukon-new-d10.w3creatives.com/docroot/node/1374

**Comment by w3creatives** [comment]
Please review the following tasks:

- #247 
- #257 
- #261

**Comment by leeomara** [comment]
This looks good on UAT.
