### ISSUE TITLE
Find a campground or recreation site page bocks

### ISSUE THREAD

**Issue by adrianrylski** [ytgov/yukon-ca#523]
RM [67558](https://rm.ewdev.ca/issues/67558)

As a site owner, I need to Find a campground or recreation site page to render missing blocks:

1. View block and filters for Campgrounds and recreation sites as per https://yukon.cms-uat.yukon.ca/en/node/1372
2. Custom HTML content block - Peak Times also as per https://yukon.cms-uat.yukon.ca/en/node/1372

Investigation solution for;
1. Implementing a custom block/mid content solution
2. Is there an ability for us to code deploy then or do we recreate then post final migration

[Additional references](https://docs.google.com/spreadsheets/d/1l5oLPS9lDoq1AfVj0l2yBByi9HSbmZYOW-KyQaJEMA4/edit?pli=1&gid=438591286#gid=438591286) and links to configuration of views for EW

**Comment by w3creatives** [comment]
1...We have added the view block and assigned a filter.
2..We have created a custom block at this location: /admin/content/block/2

**Comment by leeomara** [comment]
Looks good on UAT.
