### ISSUE TITLE
Backcountry campgrounds page blocks

### ISSUE THREAD

**Issue by adrianrylski** [ytgov/yukon-ca#524]
RM [67559](https://rm.ewdev.ca/issues/67559)

As a site owner, I need to Backcountry campgrounds page to render missing blocks:

1 .View block and filters Campgrounds and recreation sites as [per https://yukon.cms-uat.yukon.ca/en/node/1372](https://yukon.cms-uat.yukon.ca/en/node/1374)

View is created in D10 but is missing on the page, missing styles

Implementation of the placement on page approach will be confirmed in #523 

[Additional references](https://docs.google.com/spreadsheets/d/1l5oLPS9lDoq1AfVj0l2yBByi9HSbmZYOW-KyQaJEMA4/edit?pli=1&gid=438591286#gid=438591286) and links to configuration of views for EW

**Comment by w3creatives** [comment]
This is done. This task is linked with the TID issues.  

- #247
- #257 
- #261

**Comment by leeomara** [comment]
Looks good on UAT.
