### ISSUE TITLE
Places page block updates

### ISSUE THREAD

**Issue by adrianrylski** [ytgov/yukon-ca#525]
RM [67560](https://rm.ewdev.ca/issues/67560)

As a site owner, I need to Places page view block to have missing functionality and styles as per D7

D7 - https://yukon.cms-uat.yukon.ca/en/node/11750/?title=andrew&field_community_facility_type_tid_i18n=All&field_community_tid_i18n=All

D10 - https://dev-yukon-drupal-10.pantheonsite.io/en/places?title=andrew&field_community_facility_type_target_id=All&field_community_target_id=All

Implementation of the placement on page approach will be confirmed in https://github.com/ytgov/yukon-ca/issues/523

[Additional references](https://docs.google.com/spreadsheets/d/1l5oLPS9lDoq1AfVj0l2yBByi9HSbmZYOW-KyQaJEMA4/edit?pli=1&gid=438591286#gid=438591286) and links to configuration of views for EW

**Comment by w3creatives** [comment]
Please check:

https://yukon-new-d10.w3creatives.com/docroot/en/places?title=andrew&field_community_facility_type_target_id=All&field_community_target_id=All

On D10, the third filter on the left has "All Communities" instead of "Any Community" as in D7.

**Comment by leeomara** [comment]
Overall this looks good on UAT. 

I'm not clear on why there is a new "All communities" option in D10. Do any places belong to All communities (which is very different from "Any", which would match any different single community -- which "all" wouldn't)

**Comment by leeomara** [comment]
Places "All" and "Any" are referenced in this issue:

- https://github.com/ytgov/yukon-ca/issues/235

**Comment by leeomara** [comment]
Calling this done. The "All" vs "Any" can be dealt with separately.
