### ISSUE TITLE
Migration update error integrity constraint on UUID column being null

### ISSUE THREAD

**Issue by leeomara** [ytgov/yukon-ca#540]
As part of testing out #535 on YG UAT, I ran `migrate_inital.sh` and then `migrate_update.sh`. Many of the migrations that relate to paragraphs, and some others reported a large number of errors related an SQL integrity constraint due to UUID being empty/null.

Errors look like

```
(/var/www/yukon-ca-d10/docroot/core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php:817) 
 [error]  Drupal\Core\Database\IntegrityConstraintViolationException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'uuid' cannot be null: 
UPDATE "paragraphs_item" 
 SET 
  "revision_id"=:db_update_placeholder_0, 
  "type"=:db_update_placeholder_1, 
  "uuid"=:db_update_placeholder_2, 
  "langcode"=:db_update_placeholder_3
WHERE "id" = :db_condition_placeholder_0; Array
(
    [:db_update_placeholder_0] => 1363
    [:db_update_placeholder_1] => collapsable_field
    [:db_update_placeholder_2] => 
    [:db_update_placeholder_3] => en
    [:db_condition_placeholder_0] => 1363
)
```

I think these might be in  `yukon_migrate_top_tasks`, `yukon_migrate_department_section`, `yukon_migrate_related_content`, `yukon_migrate_quick_facts_translations`, `yukon_migrate_quotes_translations`, `yukon_migrate_secondary_content`, `yukon_migrate_primary_content`, `yukon_migrate_quotes` and others.

A similar error, but  for "media" (instead of "paragraph_item"):
```
 (/var/www/yukon-ca-d10/docroot/core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php:817) 
 [error]  Drupal\Core\Database\IntegrityConstraintViolationException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'uuid' cannot be null: UPDATE "media" SET "vid"=:db_update_placeholder_0, "bundle"=:db_update_placeholder_1, "uuid"=:db_update_placeholder_2, "langcode"=:db_update_placeholder_3
WHERE "mid" = :db_condition_placeholder_0; Array
(
    [:db_update_placeholder_0] => 44731
    [:db_update_placeholder_1] => video
    [:db_update_placeholder_2] => 
    [:db_update_placeholder_3] => en
    [:db_condition_placeholder_0] => 44731
)
```
I think those are from `yukon_migrate_media_video_from_video_and_text`, which reports 47 failures (many more than 47 errors reported)

As the recent MR touched on UUID, I thought I'd report it.

cc @ab-ew @adrianrylski

**Comment by w3creatives** [comment]
It should have been fixed as of now.

**Comment by leeomara** [comment]
That works for me.
