### ISSUE TITLE
Global - Migration Missing Configurations & Process Changes

### ISSUE THREAD

**Issue by w3creatives** [ytgov/yukon-ca#556]
**Migration & Configurations (Config Imports):**

1. nid (node ID) matching not done which creates a different node ID on Drupal10. (Done)
   - Relates to https://github.com/ytgov/yukon-ca/issues/187
2. There is UUId error in almost all paragraphs migrations because paragraphs do not require UUIDs. (Done)
   - Relates to https://github.com/ytgov/yukon-ca/issues/540
3. `docroot/modules/custom/yukon_migrate/yukon_migrate.info.yml` incorrectly placed `drush:drush`. (Done)
   - This was previously reported in https://github.com/ytgov/yukon-ca/issues/538#issuecomment-2278358833
4. User Migration not present. (Done)
   - This was previously reported as https://github.com/ytgov/yukon-ca/issues/363
5. UND language parameter is not set on the D10 version. This creates incorrect redirects for pages with UND as the default language after migration. (Done)
6. Footer copyright content, logo and aurora needs custom block and other configurations.  (Done)
7. Fid issue exists for multiple images all over the site. [Reference Prod Link](https://yukon.ca/en/emergencies-and-safety/wildfires/get-text-only-wildfire-updates?__cf_chl_rt_tk=v.nTeFo7ymmpK7VKl0bA4k2PzPfL6Ucxlv4Gm18QSJA-1725655358-0.0.1.1-6570)  (Done)

**Running Migration - Process Update:**

7. URL alias migration (`yukon_migrate_url_alias_node`) along with other migrations create duplicates aliases. This corrupts the ID (order or sequence) of individual aliases in the `path_alias` table where the highest ID of any node is considered the current alias. We need to implement a process of preserving the sequence and avoid duplicates to compare D10 migration with D7. (Done - Updated migration files) 
   - This was initially identified in https://github.com/ytgov/yukon-ca/issues/365#issuecomment-2342336146
8. Drupal 7 database >> `paragraph_items` table has `revision_ids` that do not correlate with the revision tables.  This causes incomplete migration of paragraph items and impacts other dependent migrations. (Done - Created a raw PHP file)
9. Because of the data size, migration import does not complete the migration on its own in first attempt. Migration update is a requirement after migration import nut certain items needs monitoring for their failed status. This includes `yukon_migrate_charts` migrations which gets failed in first attempt. (Done - Created new sh file)

**Comment by leeomara** [comment]
Some reference to existing/previous issues:
- No 3: https://github.com/ytgov/yukon-ca/issues/538#issuecomment-2278358833
- No 4: #363
- No 6: #186

**Comment by leeomara** [comment]
✅ All of these look good on UAT.

**Comment by leeomara** [comment]
@w3creatives why is this re-opened? Are there issues for me to work on, or should this be re-assigned to you?

**Comment by w3creatives** [comment]
Opened by mistake.
