### ISSUE TITLE
Global - Design Updates

### ISSUE THREAD

**Issue by w3creatives** [ytgov/yukon-ca#557]
1. Font awesome library is missing and seems like a version issue.  The issue impacts loading of icons on some pages. (Done)
2. Webform thumbs up/down missing and needs implementation (Design + Translation). Submitted response should be accessible from admin end. (Done)
   - This was previously reported as https://github.com/ytgov/yukon-ca/issues/283
3. Burger menu border spacing is less than what exists on production. This is visible when the user is logged in. (Done)
4. Thumbs up/down and aurora graphics below the right side body content needs implementation. [Reference link](https://dev-yukon-drupal-10.pantheonsite.io/en/archival-reproductions). (Done)
5. Copyright text should translate to French. (Done)

**Need eServices Feedback:**

6. Top page heading in grey strip with aurora can be made site-wide.
7. Bottom aurora can be centralized and moved above footer.

**Comment by leeomara** [comment]
(draft review, incomplete)
 
- 🟠 Re 1: Font Awesome 
    - ✅ Looks perfect on W3 Creatives test site.
    - 🟠 Loads okay for some (e.g. download link), but not others (webform thumbs) on UAT
- ✅ Re 2: Webform design
    - ✅ Works perfect on W3 Creatives test site. Problem on UAT is part of issue 1 (font awesome/glyphicon not entirely loading)

![Screenshot 2024-10-09 at 9 22 07 AM](https://github.com/user-attachments/assets/96929ccc-feb8-4543-b22b-dc18ea13f070)

Firefox reports these errors on UAT:

```
downloadable font: rejected by sanitizer (font-family: "Glyphicons Halflings" style:normal weight:400 stretch:100 src index:0) source: https://yukond10.cms-uat.yukon.ca/themes/custom/yukonca_glider/fonts/Glyphicons%20Halflings/glyphicons-halflings-regular.eot 
GET https://yukond10.cms-uat.yukon.ca/themes/custom/yukonca_glider/dist/css/font-awesome.css?skzyn2 NS_ERROR_CORRUPTED_CONTENT
```

**Comment by w3creatives** [comment]
Font awesome library was included in a different way previously and you should be able to test it in the next re-run.

**Comment by w3creatives** [comment]
Please check again.

**Comment by leeomara** [comment]
All of these look good on UAT.
