### ISSUE TITLE
Basic Page

### ISSUE THREAD

**Issue by w3creatives** [ytgov/yukon-ca#559]
**Design and Functionality:**

1. Download Board Decision button missing. (It looks like inserted manually on D7 production later on. Done)
2. Download button design missing. (Done)
   - Likely related to https://github.com/ytgov/yukon-ca/issues/298
3. Accordion should be before contact information. (Done)
https://yukon-new-d10.w3creatives.com/docroot/en/doing-business/businesses-societies-and-securities/yukon-societies/how-keep-records-non-profits
4. First child of accordion should be open by default. (Done)
https://yukon-new-d10.w3creatives.com/docroot/en/doing-business/businesses-societies-and-securities/yukon-societies/how-keep-records-non-profits
5. Missing table design: (Done)
https://dev-yukon-drupal-10.pantheonsite.io/en/Dates-limites-des-depots-pour-municipalites
https://yukon-new-d10.w3creatives.com/docroot/en/Dates-limites-des-depots-pour-municipalites
https://yukon-new-d10.w3creatives.com/docroot/en/Dates-limites-des-depots-pour-municipalites , https://yukon.ca/en/find-out-about-tipping-fees-rural-communities
6. Image size adjustment and alignment issue: (Done)
https://yukon-new-d10.w3creatives.com/docroot/en/evacuation-alert-silver-trail-highway-11-kilometre-10-kilometre-35-0 
7. Design needs fixing: (Done)
https://yukon-new-d10.w3creatives.com/docroot/en/node/11914
8. Alias is incorrect: (Done)
https://yukon-new-d10.w3creatives.com/docroot/en/node/11914

**Content & Migration:**

9. Basic pages are missing related links. (Done)
   - Suspect this relates to https://github.com/ytgov/yukon-ca/issues/163

**Translation:**

10. Related links has two hyperlinks on D10 french page as compared to one on D7 and on D10 English.  (Known issue. Done)
11. Related links and contact missing French translation:
https://dev-yukon-drupal-10.pantheonsite.io/fr/sante-et-bien-etre/services-de-soins/inscription-un-atelier-de-soutien-ou-dinformation-sur-les (Done)
12. Incorrect translation (English has French content and this exists on production as well): 
https://yukon-new-d10.w3creatives.com/docroot/en/Dates-limites-des-depots-pour-municipalites (Known issue. Done)
13. Image alignment needs to be on left side: (Done)
https://dev-yukon-drupal-10.pantheonsite.io/en/travel-safely-yukon-wilderness
https://yukon-new-d10.w3creatives.com/docroot/en/outdoor-recreation-and-wildlife/wilderness-safety/travel-safely-yukon-wilderness
14. Mobile responsiveness issue: (Done)
https://dev-yukon-drupal-10.pantheonsite.io/en/evacuation-alert-silver-trail-highway-11-kilometre-10-kilometre-35-0
https://yukon-new-d10.w3creatives.com/docroot/en/evacuation-alert-silver-trail-highway-11-kilometre-10-kilometre-35-0
15. FID is displaying instead of image: (Done)
https://yukon-new-d10.w3creatives.com/docroot/node/8620

**New Issues:**

16. Image caption and alignment needs left alignment. (Done)

https://yukon-new-d10.w3creatives.com/docroot/en/outdoor-recreation-and-wildlife/yukon-wildlife/american-black-bear
https://yukon.ca/en/outdoor-recreation-and-wildlife/yukon-wildlife/american-black-bear

**Reference Links:**

https://yukon.ca/en/find-status-northern-lights-resort-and-spa-liquor-licence-application-item-24-05
https://dev-yukon-drupal-10.pantheonsite.io/en/Dates-limites-des-depots-pour-municipalites
https://yukon-new-d10.w3creatives.com/docroot/en/find-status-northern-lights-resort-and-spa-liquor-licence-application-item-24-05

**Comment by leeomara** [comment]
(draft review, incomplete)

RE 1: ✅ Looks fine.

RE 2: ❓I couldn't find an example of a download button on a basic page.

RE 3: ❌ Contact section is above the accordion. See https://yukon-new-d10.w3creatives.com/docroot/en/doing-business/businesses-societies-and-securities/yukon-societies/how-keep-records-non-profits 

RE 4: ✅ Looks good.

RE 5: ✅ Looks good.

RE 6: 🟠 The layout looks good, however it looks like the full size image (5100 x 3300) is being served to the user, and just visually styled with CSS down to a smaller size. We should not be sending users a massive file when we only need a small image. The [version used in D7](https://yukon.ca/en/evacuation-alert-silver-trail-highway-11-kilometre-10-kilometre-35-0) is much smaller (480x311) than what D10 is using.

# Other issues

## Site media embed renders as code, not the media

- D7: https://yukon.ca/en/node/11914
- D10: https://yukon-new-d10.w3creatives.com/docroot/en/node/11914

Expected outcome (D7): Under "Site plan" heading, a graphic is visible

Actual outcome (D10):  Under "Site plan" heading, this code is visible:

```
[[{"fid":"13361","view_mode":"default","fields":{"format":"default","alignment":"left"},"type":"media","field_deltas":{"1":{"format":"default","alignment":"left"}},"attributes":{"class":"media-element file-default media-wysiwyg-align-left","data-delta":"1"}}]]
```

---
clipboard: ✅ 🟠 ❌ ❓

**Comment by w3creatives** [comment]
RE: 3 is fixed.

Fid issue is resolved.

**Comment by leeomara** [comment]
RE 3: ✅ No looks good.

RE 6: ✅ Looks good.

RE Site media embed renders as code: ✅ Looks good.

**Comment by leeomara** [comment]
Summary of current status:

- ✅ all look good except for 2 and 12
- RE 2: ❓I couldn't find an example of a download button on a basic page.
- RE 12: ❓ Looks like it [started broken](https://github.com/ytgov/yukon-ca/labels/started%20broken)

**Comment by leeomara** [comment]
All development here is done.
