### ISSUE TITLE
Public engagement

### ISSUE THREAD

**Issue by w3creatives** [ytgov/yukon-ca#560]
**Design and Functionality:** 

1. Public engagement main page missing. (Done)
   - This was previously reported as https://github.com/ytgov/yukon-ca/issues/213
2. Public engagement content type missing design, sidebar and partial content. (Done)
https://dev-yukon-drupal-10.pantheonsite.io/en/resource-roads-regulation
   - This was previously reported as https://github.com/ytgov/yukon-ca/issues/214
3. Heading font size is smaller. (Done)
4. Information/Notification blue box missing. (Done)
https://yukon-new-d10.w3creatives.com/docroot/en/resource-roads-regulation
5. Sidebar yellow border missing. (Done)

**Content & Migration:**

6. Public engagement missing "Result field" migration. (Done)
7. Sidebar has missing links. (Done)

**Translation:**

8. French translation not complete. (Done)
   - This was previously reported as https://github.com/ytgov/yukon-ca/issues/217
9. In French page links taking to English page. (Done)
10. Main/top page >> /engagements page missing translation. (Done)

**Reference Links:**

https://yukon.ca/en/engagements
https://yukon.ca/en/resource-roads-regulation
https://dev-yukon-drupal-10.pantheonsite.io/en/engagements (Missing)
https://yukon-new-d10.w3creatives.com/docroot/en/engagements  
http://dev-yukon-drupal-10.pantheonsite.io/en/resource-roads-regulation
https://yukon-new-d10.w3creatives.com/docroot/en/resource-roads-regulation

**Need eServices Feedback:**

11. We have created a custom page template to design this page to simplify this process. Previously it was done using panels. Let us know if we should use panels instead. (Approved & Done)

**Comment by leeomara** [comment]
Not using panels is fine.

**Comment by leeomara** [comment]
RE 1: ✅ Looks good on w3creatives test site.

RE 2: ✅ Looks good on w3creatives test site.

RE 3: ✅ Looks good on w3creatives test site.

RE 4: 🟠 Looks mostly right on w3creatives test site. The French version has one english "to" in the date.
   - > Elle était en cours du 2023-03-07 **to** 2023-05-07
   - from https://yukon-new-d10.w3creatives.com/docroot/fr/engagements/projet-de-reglement-sur-les-routes-dacces-
aux-ressources
   - "to" should be "au" in French.

RE 5: ✅ Looks good on w3creatives test site.

RE 6: ✅ Looks good on w3creatives test site.

RE 7: ✅ Looks good on w3creatives test site.

RE 8: ✅ Looks good on w3creatives test site. I do note that the "Status" values are not translated (not in D7 either, "started broken")

RE 9: ✅ Looks good on w3creatives test site.

RE 10: ✅ Looks good on w3creatives test site.

**Comment by leeomara** [comment]
- RE 4: 🟠 still showing English "to" in the French date. e.g. https://yukon-new-d10.w3creatives.com/docroot/fr/engagements/familles-inclusives-du-yukon
- RE 8: 🟠 Sidebar on french shows English content 
    > **Other public engagements**
    > No open engagements found

**Comment by w3creatives** [comment]
Re 4: Date is fixed.

**Comment by leeomara** [comment]
Looks good in UAT (MN).
