### ISSUE TITLE
Blog

### ISSUE THREAD

**Issue by w3creatives** [ytgov/yukon-ca#563]
**Design and Functionality:**

Blog Listing Page:

1. Missing Side bar and page content design. (Done)
https://yukon.ca/en/blogs/digital-information-and-services
https://dev-yukon-drupal-10.pantheonsite.io/en/blogs/digital-information-and-services
https://yukon-new-d10.w3creatives.com/docroot/en/blogs/digital-information-and-services

2. Remove duplicates and partial content. (Done)
https://yukon.ca/en/blogs/
https://dev-yukon-drupal-10.pantheonsite.io/en/blogs
https://yukon-new-d10.w3creatives.com/docroot/en/blogs/
 
3. Incorrect page redirects >> It can be based on server redirects (Done)
https://yukon.ca/en/blogs/wildfire-bulletins
https://dev-yukon-drupal-10.pantheonsite.io/en/emergencies-and-safety/wildfires/read-wildfire-bulletins
https://yukon-new-d10.w3creatives.com/docroot/en/blogs/wildfire-bulletins

4. Individual blogs listing page heading and description should be full width not in right container. (Done)
https://dev-yukon-drupal-10.pantheonsite.io/en/blogs/digital-information-and-services

5. Left sidebar >> Subscribe box missing. (Done)
6. Changed the URL and included the alias to digital-blog. (Done)
7. Images missing for blog listings: (Done)
https://yukon-new-d10.w3creatives.com/docroot/en/blogs/wildfire-bulletins
- This was previously reported as https://github.com/ytgov/yukon-ca/issues/271

Individual Blogs:

https://yukon.ca/en/digital-blog/open-data-update
https://dev-yukon-drupal-10.pantheonsite.io/en/digital-blog/open-data-update
https://yukon-new-d10.w3creatives.com/docroot/en/digital-blog/open-data-update

8. Breadcrumbs alignment is out of container. (Done)
9. The smaller text, just above the page heading, is not complete and missing the next element. (Done)
10. Learn more about and other headings >> font size is bigger. (Done)
11. Comment box design is different. (Done)
12. Sidebar >> Under share on social media top yellow border is missing.  (Done)

**Content & Migration:**

13. Image size in main body is smaller than D7 because migration is fetching the smaller size. (Done)
14. Images missing for blog categories: (Done)
https://yukon.ca/en/blogs/

**Translation:**

15. Sidebar >> “About this blog” >> French text is coming instead of English. (Done)

**Needs eServices Feedback:**

16. French version missing.
17. French version has no sidebar on D7 production.

**Comment by leeomara** [comment]
Regarding 16, yes, some posts are currently missing in French. Some are translated and available however. See, for example https://yukon.ca/fr/blogs/digital-information-and-services

Regarding 17, I am seeing a sidebar on both the blogs listing page and individual blog post pages in D7 production. E.g. https://yukon.ca/fr/blogs/digital-information-and-services and https://yukon.ca/fr/blogue-renseignements-et-services-en-ligne/lavenir-du-portail-de-donnees-ouvertes-du-gouvernement-du

**Comment by leeomara** [comment]
(draft, incomplete review)

- ✅ RE 1: Looks good on UAT
- ✅ RE 2: Looks good on UAT
- ❓ RE 3: These pages look fine, but I don't quite understand the issue.
- ✅ RE 4: Looks good on UAT
- 🟠 RE 5 Subscribe box
    - ✅ The box is there and looks good.
    - ❌ The RSS feed is not blog-specific. On D7 for the digital info blog, the RSS link is `https://yukon.ca/blogs/311/feed.xml`, but on D10, the RSS link is `https://yukond10.cms-uat.yukon.ca/en/blog-feed`
- ❓ RE 6: "Change URL and alias to digital-blog" I'm not sure what this is about.
- ✅ RE 7: This looks good on UAT

**Comment by w3creatives** [comment]
Re 3: Please ignore as it was initially happening on W3 server only
Re 5: Test RSS again
Re 6: Initially the URL contained /blog/ everywhere which was later changed /digital-blog/
Re 11: Test again 
Re 15: Pending

**Comment by leeomara** [comment]
- 👍 RE 3: Okay
- ✅ RE 5: Each blog has it's own distinct RSS feed
- ✅ RE 6: Okay
- ✅ RE 11: Looks good on UAT

**Comment by w3creatives** [comment]
Re 15: Test again

https://yukon-new-d10.w3creatives.com/docroot/en/digital-blog/getting-ready-next-stage-yukon-open-government-portal

**Comment by leeomara** [comment]
✅ RE 15: Looks good on W3 server

**Comment by w3creatives** [comment]
Assigning this issue to YG to be tested on the UAT environment.

**Comment by leeomara** [comment]
Looks good on UAT.
