### ISSUE TITLE
Documents & Forms

### ISSUE THREAD

**Issue by w3creatives** [ytgov/yukon-ca#564]
**Design and Functionality:**

1. In D10 Download button text is black (should be blue/green) and border is missing. (Done)
   - This was previously reported as https://github.com/ytgov/yukon-ca/issues/196

2. Download click does not work. (Done)
3. Documents listing page title is displayed twice.  https://dev-yukon-drupal-10.pantheonsite.io/en/documents (Done)
4. Documents listing page filter not collapsing working on mobile screens. (Done)
5. Documents listing page pagination not fitting on mobile screens. (Done)
6. Forms listing page filter not collapsing working on mobile screens. (Done)
https://dev-yukon-drupal-10.pantheonsite.io/en/forms
7. Forms listing page pagination not fitting on mobile screens. (Done)
https://dev-yukon-drupal-10.pantheonsite.io/en/forms

**Content & Migration:**

8. Document pages missing. (Done)
 
**Translation:**

9. French translation missing. (Done)
   - This may relate to https://github.com/ytgov/yukon-ca/issues/195

**Reference Links:**

https://yukon.ca/en/northern-lights-resort-and-spa-liquor-licence-application-summary-item-24-05
https://dev-yukon-drupal-10.pantheonsite.io/en/northern-lights-resort-and-spa-liquor-licence-application-summary-item-24-05
https://yukon-new-d10.w3creatives.com/docroot/en/northern-lights-resort-and-spa-liquor-licence-application-summary-item-24-05

**Comment by leeomara** [comment]
RE 1: ✅ Looks good on w3creatives test site.

RE 2: ✅ Looks good on w3creatives test site.

RE 3: ✅ Looks good on w3creatives test site.

RE 4: 🟠 Documents listing page filter does now collapse on mobile, but after collapes it's not accessible. Clicking on it does not expand. Reloading the page at the smaller size seems to resolve the issue. Also, on hover, the cursor should indicate that the filter is clickable (cursor changes from arrow pointer to as D7 does).

RE 5: ✅ Looks good on w3creatives test site.

RE 6: 🟠 Same as 4.

RE 7: ✅ Looks good on w3creatives test site.

RE 8: ✅ Looks good on w3creatives test site.

RE 9:  ✅  Looks good on w3creates test site.

# Other notes:

## Document reported sizes

On the w3creatives test site, document reports the wrong size.

- D7: 164.85 KB https://yukon.ca/en/northern-lights-resort-and-spa-liquor-licence-application-summary-item-24-05
- D10: 16.67 KB https://yukon-new-d10.w3creatives.com/docroot/en/northern-lights-resort-and-spa-liquor-licence-application-summary-item-24-05

The file downloaded from w3creatives looks like 168,804 bytes (172 KB on disk) to my local.

## Forms filter has english label

On the w3creatives test site Forms page the "Filter by" header is English. It should be "Filtrer par". Other filter elements are translated correctly. Compare https://yukon-new-d10.w3creatives.com/docroot/fr/forms and https://yukon.ca/fr/formulaires

This is not a problem on the Documents page https://yukon-new-d10.w3creatives.com/docroot/fr/documents shows "Filtrer par"

**Comment by w3creatives** [comment]
Please check again.

**Comment by lgontard** [comment]
"Filtrer par :" This was recently fixed by EW on D7
Doc size is still showing up incorrect

**Comment by lgontard** [comment]
@leeomara @w3creatives Still unresolved.

**Comment by lgontard** [comment]
@w3creatives @leeomara 
"Filter par" is resolved on the W3C environment
File size remains unresolved. See screengrabs.
![image](https://github.com/user-attachments/assets/23a5e7e0-334c-4027-8ad9-dd7a2f2e90ca)
![image](https://github.com/user-attachments/assets/a81e5549-4c3d-4f97-aa0c-5b4c4ad72805)

**Comment by w3creatives** [comment]
The file size will not be correct on our servers because we have these missing. Once the files folder is replaced on production, it will get fixed.

**Comment by leeomara** [comment]
Looks good on pre-prod
