### ISSUE TITLE
Campground and Recreation Site

### ISSUE THREAD

**Issue by w3creatives** [ytgov/yukon-ca#567]
**Design and Functionality:**

1. In D10 breadcrumb the text of the related page is not complete. (Done)
2. Body content alignment is not same as D7.  In D7  the body content is on right side and the bullet points are aligned. (Done)
   - This was previously reported as https://github.com/ytgov/yukon-ca/issues/249
3. Under Map Download - The Download button cloud is blue as compared to green in D7 . Also pdf file name is visible instead of text. (Done)
   - This was previously reported as https://github.com/ytgov/yukon-ca/issues/251
4. Under Location >> Highway name is hyperlinked in D10 as compared to no hyperlink in D7. (Done)
5. Color of the bar graph should be #7a9a01. (current color = rgb(0 128 0 / var(--tw-bg-opacity)). Bar color should vary as per the value. (Done)
   - This was previously reported as https://github.com/ytgov/yukon-ca/issues/256

**Content & Migration:**

**Translation:**

6. The French page translation is not complete for labels and missing content in French. (Done)
   - This was previously reported as https://github.com/ytgov/yukon-ca/issues/266

**Reference Links:**

https://yukon.ca/en/outdoor-recreation-and-wildlife/camping/site/aishihik-lake-campground
http://dev-yukon-drupal-10.pantheonsite.io/en/outdoor-recreation-and-wildlife/camping/site/frances-lake-campground
https://yukon-new-d10.w3creatives.com/docroot/en/outdoor-recreation-and-wildlife/camping/site/aishihik-lake-campground
https://yukon-new-d10.w3creatives.com/docroot/fr/plein-air-faune-et-flore/camping/site/camping-aishihik-lake
                                                                                                                    
**Need eServices Feedback:**

7. Should we remove the blank left sidebar area from this page to efficiently use the available space above fold? Logic should be to display sidebar if available otherwise show content in full-width. (Approved and Done)

**Comment by leeomara** [comment]
@lgontard what do you think of this question for Campground and rec sites:

> Should we remove the blank left sidebar area from this page to efficiently use the available space above fold? Logic should be to display sidebar if available otherwise show content in full-width.

**Comment by lgontard** [comment]
I wonder if the filtering on [this page](https://yukon.ca/en/find-campground-or-recreation-site) was supposed to be in that blank sidebar. I'll check with Parks and get back to you on this.

**Comment by lgontard** [comment]
@leeomara @w3creatives I heard back from Parks and they'd like to see that invisible filter removed and the text flushed to the left-hand side of the page.

**Comment by leeomara** [comment]
RE 1: ✅ Looks good.

RE 2: ✅ Looks good.

RE 3: ✅ Looks good.

RE 4: ✅ Looks good.

RE 5: ✅ Looks good.

RE 6: 🟠 Mostly good. The "Avec services" date is French but doesn't have quite the same language.

- [D7](https://yukon.ca/fr/plein-air-faune-et-flore/camping/site/camping-aishihik-lake) has: Avec services : Du 9 mai au 30 septembre 2024
- [D10](https://yukon-new-d10.w3creatives.com/docroot/fr/plein-air-faune-et-flore/camping/site/camping-aishihik-lake) has: Avec services 9: Mai 2024 to 30 Septembre 2024

# Other issue

French labels get an extra space before the colon. E.g. "Route : Alaska Highway" instead of "Route: Alaska Highway"

**Comment by leeomara** [comment]
Re-checked.

- RE 6: 🟠 Mostly good. The "Avec services" date is French but doesn't have quite the same language.

    [D7](https://yukon.ca/fr/plein-air-faune-et-flore/camping/site/camping-aishihik-lake) has: Avec services : Du 9 mai au 30 septembre 2024
    [D10](https://yukon-new-d10.w3creatives.com/docroot/fr/plein-air-faune-et-flore/camping/site/camping-aishihik-lake) has: Avec services 9: Mai 2024 to 30 Septembre 2024

# Other issues

- (minor) French labels get an extra space before the colon. E.g. "Route : Alaska Highway" instead of "Route: Alaska Highway"
- (medium) Field label "Site description" should be "Description" in French

**Comment by w3creatives** [comment]
Please check on W3 servers.

**Comment by leeomara** [comment]
- ✅ RE 6: Looks good on UAT
- 🟠 RE extra 1 (extra space before colon in French) still an issue on W3 Creatives test site
- ✅ RE extra 2 ("Site description" should be "Description" in French) looks good on UAT
- ❌ RE extra 3 (new): The label "Gate open" is incorrectly translated to French as "Avec services". Should be "Portillon ouvert" (D7 omits this field in French)

**Comment by w3creatives** [comment]
Please review the following link for Re extra 1 and Re extra 3:

https://yukon-new-d10.w3creatives.com/docroot/fr/plein-air-faune-et-flore/camping/site/camping-aishihik-lake

**Comment by lgontard** [comment]
Re extra 1: It looks like there are still two character spaces before and after the colons, when there should only be one
Re extra 3: The label in French is correct (Portillon ouvert), but the text after the label is appearing in English (Gate open year-round) 
![image](https://github.com/user-attachments/assets/9817cb34-853e-4873-aabd-24fd81f86316)

**Comment by w3creatives** [comment]
Re extra 1: We have made it 1 space now:
https://yukon-new-d10.w3creatives.com/docroot/fr/plein-air-faune-et-flore/camping/site/camping-aishihik-lake

Re extra 3: Because (Gate open year-round) in French does not exist on the D7 version, it is coming in English. @leeomara mentioned keeping this label in French as well.  Should we keep it or remove it?

**Comment by lgontard** [comment]
It looks like there are still two character spaces after the colon; yes, leave the label.
![image](https://github.com/user-attachments/assets/c7b41b0f-6c3b-4a51-b5cb-e7d251169d84)
The translation for "Gate open year-round" is "Barrières ouvertes toute l'année"

**Comment by lgontard** [comment]
@leeomara @w3creatives This is resolved in YG UAT
