### ISSUE TITLE
News

### ISSUE THREAD

**Issue by w3creatives** [ytgov/yukon-ca#568]
**Design and Functionality:**

1. Bread crumb is not in one line. (Done)
2. Hyperlinks not working. (Done)
3. Bottom aurora missing. (Done)
4. News page design need updates to match spacers and horizontal separators. (Done)
5. Left side-bar design >> year filter needs matching. (Done)
6. Yellow quotes design needs adjustment.  (Done)
https://yukon-new-d10.w3creatives.com/docroot/en/news/statement-premier-pillai-passing-michael-prochazka-0.  
7. D10 has the full container width. News pages on D7 have content in a smaller container (lesser width).  (Done)  
https://yukon-new-d10.w3creatives.com/docroot/en/news/statement-premier-pillai-passing-michael-prochazka-0. 
8. En Bref (French version) has double bullets.  (Done)
    - This was previously reported in https://github.com/ytgov/yukon-ca/issues/188#issuecomment-2079940442
9. Listing page filter not collapsing working on mobile screens. (Done)     
https://dev-yukon-drupal-10.pantheonsite.io/en/news
10. Listing page pagination not fitting on mobile screens. (Done)

**Content & Migration:**

11. News pages >> Quick Facts >> Only the first item is imported. (Done)
   - This was previously reported as https://github.com/ytgov/yukon-ca/issues/186

**Translation:**

12. Text is missing under Quick facts/En Bree (French Version). (Done)

**Reference Links:**

https://yukon.ca/en/news/new-temporary-public-health-measures-now-force
https://dev-yukon-drupal-10.pantheonsite.io/fr/news/nouvelles-mesures-sanitaires-temporaires-maintenant-en-vigueur
https://yukon-new-d10.w3creatives.com/docroot/en/news/new-temporary-public-health-measures-now-force

**Need eServices Feedback:**

13. Container width can be optimized to match with other pages.
14. On production, news listing page filters are shown at the bottom of the page as compared to other listing pages. Should we fix this issue?

**Comment by leeomara** [comment]
RE 13, yes, news width should match other full-width layouts.

RE 14, yes please fix the filter position

**Comment by w3creatives** [comment]
Please check on UAT.

**Comment by leeomara** [comment]
Looks good on W3

**Comment by leeomara** [comment]
- ✅ RE bottom aurora - fixed
- ✅ RE year filter fixed
- ✅ RE Hyperlinks fixed

**Comment by leeomara** [comment]
✅ all fixed except ..
❌ for mobile - filter not collapsing

**Comment by w3creatives** [comment]
Checked on both Chrome and Firefox and found it working:

https://yukon-new-d10.w3creatives.com/docroot/en/news/

**Comment by leeomara** [comment]
This looks good on UAT.
