### ISSUE TITLE
Multi-Step Pages

### ISSUE THREAD

**Issue by w3creatives** [ytgov/yukon-ca#569]
**Design and Functionality:**

1. Sidebar missing. (Done)
2. Bottom aurora missing. (Done)

**Content & Migration:**

3. Multistep pages missing meta description, numbering and current content. (Done)

**Translation:**

4. French version not working. (Done)

**Reference Links:**

https://yukon-new-d10.w3creatives.com/docroot/en/science-and-natural-resources/outreach-and-collaboration/use-seed-library#nav-borrow-seeds

**Comment by leeomara** [comment]
This looks good on https://yukon-new-d10.w3creatives.com
