### ISSUE TITLE
Landing Page Level 2

### ISSUE THREAD

**Issue by w3creatives** [ytgov/yukon-ca#570]
**Design and Functionality:**

1. The page title opposite top aurora is in 2 lines and the leaf icon is more towards left. (Done)

**Content & Migration:**

**Translation:**

2. In D10 French page the title again is in 3 lines and icon size smaller and more towards left of the aurora. (Done)
3. Under Rubriques the text is in English. (Done)

**Reference Links:**

https://yukon.ca/en/immigration/yukon-business-nominee-program
https://dev-yukon-drupal-10.pantheonsite.io/en/immigration/yukon-business-nominee-program
https://yukon-new-d10.w3creatives.com/docroot/en/immigration/yukon-business-nominee-program

**Need eServices Feedback:**

4. Top links box heights are variable dependant on the text length. Should we make them all same height? (Approved and Done)

**Comment by w3creatives** [comment]
Please check on UAT.

**Comment by leeomara** [comment]
This looks good on UAT.
