### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by w3creatives** [ytgov/yukon-ca#571]
**Design and Functionality:**

**Content & Migration:**

2. See more in Building and renovating (Done)
https://yukon.ca/en/housing-and-property
https://dev-yukon-drupal-10.pantheonsite.io/en/housing-and-property
https://yukon-new-d10.w3creatives.com/docroot/en/housing-and-property

**Translation:**

3. In French version of D10 Top boxes text is in English and Headings are in English. (Done)

**Reference Links:**

https://yukon-new-d10.w3creatives.com/docroot/en/housing-and-property
https://yukon.ca/en/housing-and-property
https://yukon-new-d10.w3creatives.com/docroot/fr/habitation-et-biens-immobiliers

**Comment by leeomara** [comment]
RE 2: 🟠 Overall looks good on W3 Creatives test site, and also YG UAT. Minor nit: "See More in.... " at the bottom of each subcategory, "More" needs to be lower case.

RE 3: ✅ Looks good on W3 Creatives test site.

**Comment by leeomara** [comment]
- RE 2: ✅ looks good on UAT.
- RE 3: ✅ headers and link lists look good in UAT.
- RE 4 (new): ❌ "See more in ..." is English on French page.
  - e.g. under "Construction et rénovation" on https://yukon-new-d10.w3creatives.com/docroot/fr/habitation-et-biens-immobiliers
  - the "see more" reads "See more in Building and renovating ›" it should instead read "En savoir plus : Remises écoénergétiques pour les habitations ›"

**Comment by w3creatives** [comment]
Please review:

https://yukon-new-d10.w3creatives.com/docroot/fr/habitation-et-biens-immobiliers

**Comment by leeomara** [comment]
Looks good in UAT.
