### ISSUE TITLE
In-Page Alerts

### ISSUE THREAD

**Issue by w3creatives** [ytgov/yukon-ca#572]
**Design and Functionality:**

1. In D10 => in page alert links do not work. (Done)
2. In D10 the text font weight is heavier as compared to D7. (Done)
3. Aurora top banner needs to be removed. (Done)
4. Missing one of the breadcrumb data. (Done)
![Image](https://github.com/user-attachments/assets/aa5b0594-559d-430d-ada2-d2c3e8190cf4)

**Content & Migration:**

4. Missing content and pages.  (Done)

**Translation:**

5. French translation not done.  (Done)
6. But in above page French translation is complete, though padding above the heading is more as compared to D7. (Done)

**Reference Links:**

https://yukon.ca/node/24286
https://yukon.ca/fr/fermeture-de-sentier-lapie-canyon
https://yukon-new-d10.w3creatives.com/docroot/node/24286
https://yukon-new-d10.w3creatives.com/docroot/fr/node/24286
https://yukon-new-d10.w3creatives.com/docroot/fr/fermeture-de-sentier-lapie-canyon

**Comment by leeomara** [comment]
In-page alerts looks good on their own. Is it a concern that the in-page alert doesn't appear to be placed on all the pages?

e.g. comparing:
- D7: ✅ https://yukon.ca/en/outdoor-recreation-and-wildlife/camping/site/lapie-canyon
- W3C test site: ❌ https://yukon-new-d10.w3creatives.com/docroot/en/outdoor-recreation-and-wildlife/camping/site/lapie-canyon

The in-page alert is missing, meanwhile, checking another page, it is present.

- D7: ✅ https://yukon.ca/en/waste-and-recycling/contaminates-sites
- W3C test site: ✅ https://yukon-new-d10.w3creatives.com/docroot/en/waste-and-recycling/contaminated-sites

**Comment by w3creatives** [comment]
Now In-page alerts showing on all pages.

https://yukon-new-d10.w3creatives.com/docroot/en/outdoor-recreation-and-wildlife/camping/site/lapie-canyon

Please pull the latest code to deploy UAT env.

**Comment by leeomara** [comment]
Now looks good on UAT.
