### ISSUE TITLE
Homepage

### ISSUE THREAD

**Issue by w3creatives** [ytgov/yukon-ca#573]
**Design and Functionality:**

1. Outdoor recreation and wildlife block should be on right side and Health and Wellness block on left. (Settings based. Done)
2. Set base/homepage URL to >> /en. (Done)

**Content & Migration:**

**Translation:**

3. In French version - The Nouvelle’s recent block is missing. (Done)

**Reference Links:**

https://yukon.ca/
https://dev-yukon-drupal-10.pantheonsite.io/en/home
https://yukon-new-d10.w3creatives.com/docroot/en

**New Feature Request:**

4. Remove on hover slide left from homepage tiles (example: Your Government). (Done) 
    - See https://github.com/ytgov/yukon-ca/issues/581

**Comment by leeomara** [comment]
RE 1: I see "Outdoor recreation and wildlife" on the left (incorrect) on the W3 Creatives test site.

RE 2: looks good.

RE 3: Looks good.

**Comment by w3creatives** [comment]
> RE 1: ❌ I see "Outdoor recreation and wildlife" on the left (incorrect) on the W3 Creatives test site.
> 
> RE 2: ✅ looks good.
> 
> RE 3: ✅ Looks good.

RE 1: It is setting on the admin side. We have included the steps in the read me file.

**Comment by leeomara** [comment]
RE 4:  ✅ Looks good.

**Comment by w3creatives** [comment]
Please check the readme document for homepage settings.

**Comment by leeomara** [comment]
This looks good on UAT.
