### ISSUE TITLE
Places

### ISSUE THREAD

**Issue by w3creatives** [ytgov/yukon-ca#574]
**Design and Functionality:**

1. Design broken on right side. It looks like Contact heading is missing. (Done)
2. [Energy, Mines and Resources Library](https://yukon-new-d10.w3creatives.com/docroot/node/4136). Bottom links not working. (Removing 'docroot' will make them work. Done) 
3. Listing page filter not collapsing working on mobile screens. (Done)
    https://dev-yukon-drupal-10.pantheonsite.io/en/places 
5. Listing page pagination not fitting on mobile screens. (Done)
6. Remove apply button: (Done)
https://yukon-new-d10.w3creatives.com/docroot/en/places
7. Labels names and order needs matching: (Done)
https://yukon.ca/en/places/whitehorse-mining-recorders-office
https://dev-yukon-drupal-10.pantheonsite.io/en/places/whitehorse-mining-recorders-office
https://yukon-new-d10.w3creatives.com/docroot/en/places/whitehorse-mining-recorders-office

**Content & Migration:**

8. Contact information missing phone number: (Done)
https://yukon.ca/en/places/professional-licensing-and-regulatory-affairs-hours-and-location
https://yukon-new-d10.w3creatives.com/docroot/en/places/professional-licensing-and-regulatory-affairs-hours-and-location
9. Attendance area list link not working: (Removing docroot from URL fixed the issue. Done)
https://yukon-new-d10.w3creatives.com/docroot/en/places/del-van-gorder-school

**Translation:**

10. French translation not complete and links also not working. (Done)

**New Issue:**

11. Places in breadcrumbs is not working on D10. It is an issue on D7 where the URL /places is not translated into French
https://yukon.ca/fr/places/direction-de-la-reglementation-professionnelle-adresse-et-heures-douverture
https://dev-yukon-drupal-10.pantheonsite.io/fr/places/direction-de-la-reglementation-professionnelle-adresse-et-heures-douverture
https://yukon-new-d10.w3creatives.com/docroot/fr/places/direction-de-la-reglementation-professionnelle-adresse-et-heures-douverture

**Reference Links:**

https://yukon.ca/en/places/del-van-gorder-school
https://yukon-new-d10.w3creatives.com/docroot/en/places/womens-directorate
https://yukon-new-d10.w3creatives.com/docroot/en/places/marsh-lake-solid-waste-facility
https://yukon-new-d10.w3creatives.com/docroot/en/places/residential-tenancies-office

**Comment by leeomara** [comment]
Earlier issue about Places contact formatting issue #240.

**Comment by leeomara** [comment]
- RE 1: ✅ Looks good on UAT
- RE 2: 
   - ❌ On W3, the link for "Search the library catalogue" is a broken UUID link (migration: yukon_migrate_places UUID: ce4d4d46-010f-4ff1-ab14-17c2fe81b458 RowNid: 4136 RowType: directory_records_places  SourceNid: 9774 DestNid not found)
   - 🟠 On UAT, the two bottom links, "Learn more about visiting the library" and "Search the library catalogue" have `node/123` links, which work, but do not use the nice path aliases.
- RE 3:
    - ✅ On W3 test server this works
    - ❌ On UAT, this shows the same problem we had with Documents and forms. See https://github.com/ytgov/yukon-ca/issues/564#issuecomment-2377638474
        > Documents listing page filter does now collapse on mobile, but after it collapses it's not accessible. Clicking on it does not expand. Reloading the page at the smaller size seems to resolve the issue.  
- RE 4: ✅ Looks good on UAT
- RE 5: ✅ Looks good on UAT
- RE 6
    - ✅ Looks good on W3 server. e.g. https://yukon-new-d10.w3creatives.com/docroot/en/places/whitehorse-mining-recorders-office
    - ❌ On UAT missing "Services", and "Transactional facility type" sections. @lgontard is "Transactional facility type" something we want? https://yukond10.cms-uat.yukon.ca/en/places/whitehorse-mining-recorders-office
- RE 8: ✅ Looks good on UAT
- RE 9: 👍 Okay
- RE 10:
    - ✅ Looks good on W3 server. e.g. https://yukon-new-d10.w3creatives.com/docroot/fr/places/registraire-minier-de-whitehorse
    - ❌ On UAT some translations are missing. E.g. https://yukond10.cms-uat.yukon.ca/fr/places/registraire-minier-de-whitehorse
- RE 11: ✅ Looks good on UAT

**Comment by lgontard** [comment]
RE 6
✅ Looks good on W3 server. e.g. https://yukon-new-d10.w3creatives.com/docroot/en/places/whitehorse-mining-recorders-office
❌ On UAT missing "Services", and "Transactional facility type" sections. @lgontard is "Transactional facility type" something we want? https://yukond10.cms-uat.yukon.ca/en/places/whitehorse-mining-recorders-office
@leeomara Yes, we need transactional facility type

**Comment by w3creatives** [comment]
Please confirm if the issue still exists on YG UAT.
