### ISSUE TITLE
Site-Wide Alert

### ISSUE THREAD

**Issue by w3creatives** [ytgov/yukon-ca#575]
**Design and Functionality:**

1. Breadcrumbs has an empty element. (Done)
https://yukon-new-d10.w3creatives.com/docroot/en/node/13413

**Content & Migration:**

2. French alias not working. (Done)
https://yukon-new-d10.w3creatives.com/docroot/en/node/13413

**Translation:**

**Reference Links:**
https://yukon-new-d10.w3creatives.com/docroot/en/node/13413

**Need eServices Feedback**

Alerts are not centralized on yukon.ca.  We have centralized it on the D10 version.

**Comment by w3creatives** [comment]
This is fixed.

**Comment by leeomara** [comment]
This looks fine on W3 Creatives test site.

**Comment by leeomara** [comment]
This looks good on UAT.
