### ISSUE TITLE
Topics Page

### ISSUE THREAD

**Issue by w3creatives** [ytgov/yukon-ca#576]
**Design and Functionality:**

1. Top Page description is not full-width. (Done)
https://yukon-new-d10.w3creatives.com/docroot/en/guide-hunting-yukon
2. Bottom aurora missing. (Done)
https://dev-yukon-drupal-10.pantheonsite.io/en/outdoor-recreation-and-wildlife/hunting-and-trapping/guide-hunting-yukon
https://yukon-new-d10.w3creatives.com/docroot/en/guide-hunting-yukon

**Content & Migration:**

**Translation:**

**Reference Links:**

**Comment by leeomara** [comment]
RE 1: ✅ Looks good on w3creatives test site.

RE 2: ✅ Looks good on w3creatives test site.

**Comment by leeomara** [comment]
These look good on UAT.
