### ISSUE TITLE
Global - Things need checking after completion or migration re-run

### ISSUE THREAD

**Issue by w3creatives** [ytgov/yukon-ca#578]
1. Basic Page >> Alias is incorrect:

https://yukon-new-d10.w3creatives.com/docroot/en/node/11914 (Done)

The above showed an incorrect alias or breadcrumbs. This eventually got fixed in the second migration re-run.   
 
2. Incorrect breadcrumbs translation:![Image](https://github.com/user-attachments/assets/8124bf6c-ac96-4604-beae-001283ef3102)https://yukon.ca/fr/sante-et-mieux-etre/services-de-soins/couverture-de-votre-regime-dassurance-sante
https://yukon-new-d10.w3creatives.com/docroot/fr/sante-et-mieux-etre/services-de-soins/couverture-de-votre-regime-dassurance-sante

3. Some alias seems to be corrupted. (Site wide and in page alerts)
4. Some breadcrumbs are partially empty. (Site wide and in page alerts)

**Comment by w3creatives** [comment]
We applied a different approach for migrating aliases and that fixed the issue.  (Importing aliases in the end by running migration_complete.sh)

**Comment by leeomara** [comment]
Other than the issue already reported to @w3creatives (about migration_complete not really running -- alegedly related to a missing query in d10-queries.sql), this worked fine in UAT (after running the migrate_update script)
