### ISSUE TITLE
Events

### ISSUE THREAD

**Issue by w3creatives** [ytgov/yukon-ca#580]
**Design and Functionality:**

1. Side filters needs to be fixed for filters. (Done)
https://yukon.ca/en/node/7534/ 
https://yukon.ca/en/events
https://dev-yukon-drupal-pantheonsite.io/en/arts-and-culture/events
https://yukon-new-d10.w3creatives.com/docroot/en/arts-and-culture/events

2. Events should not display past events. (Done)
https://dev-yukon-drupal-10.pantheonsite.io/en/arts-and-culture/events

3. Page content should be left aligned: (Done)
https://yukon.ca/en/events/getting-know-glucagon. 
https://dev-yukon-drupal-10.pantheonsite.io/en/events/getting-know-glucagon
https://yukon-new-d10.w3creatives.com/docroot/en/events/getting-know-glucagon

**Content & Migration:**

**Translation:**

**Reference Links:** 

**Need eServices Feedback:**

4. Date/year dropdown should not show past year. (Approved and Done)
https://yukon.ca/en/events
5. Description font size is smaller as compared to regular font size on the website. Should we make it uniform? 
https://yukon.ca/en/events/gathering-over-food-knowledge-sharing-event?date=2024-11-04

**Comment by leeomara** [comment]
> Date/year dropdown should not show past year.

Correct. The filter on the events page should only show the current and future years, not past years.

**Comment by w3creatives** [comment]
Its all done.

**Comment by leeomara** [comment]
This looks good on UAT.

Did find this new issue:
- https://github.com/ytgov/yukon-ca/issues/634
