### ISSUE TITLE
Homepage remove hover effect from square boxes

### ISSUE THREAD

**Issue by leeomara** [ytgov/yukon-ca#581]
The square boxes in the first few rows on the homepage (currently "Your government" and "Health an wellness" at large sizes) should not respond on hover to show a list of links. Instead they should remain as links to those pages (e.g. "Your government" and "Health and wellness").

In the Homepage content type, these first two rows are "Primary item blocks".

At smaller sizes, all of the Primary item blocks collapse down to squares. None of them should change on hover.

![yukon-ca-homepage-hover-square-2](https://github.com/user-attachments/assets/c63dd717-1606-485d-b140-ac023cf48b4a)

**Comment by w3creatives** [comment]
This is done:

https://yukon-new-d10.w3creatives.com/docroot/

**Comment by leeomara** [comment]
Looks great!

**Comment by leeomara** [comment]
This is working well on YG UAT, on the `w3_staging_yukon` branch
