### ISSUE TITLE
Links in blogs body copy sized incorrectly

### ISSUE THREAD

**Issue by leeomara** [ytgov/yukon-ca#590]
On a blogs top-level page, https://yukon-new-d10.w3creatives.com/docroot/en/blogs/ links in body are enlarged

![Screenshot 2024-10-02 at 3 05 28 PM](https://github.com/user-attachments/assets/955cf446-2fbc-4d27-b985-ba0d4eedf009)

**Comment by w3creatives** [comment]
We have fixed this issue.

**Comment by leeomara** [comment]
@w3creatives Please clarify In what branch or commit was this fixed?

I can see that it's fixed on the w3creatives test site, which is good, but I can't tell how I can get this fix to YG UAT. Should I wait for another MR, or what?

**Comment by w3creatives** [comment]
Currently they are on our [dev server](https://yukon-new-d10.w3creatives.com/docroot/en/blogs/). We will push the changes to w3_yukon_staging by tomorrow. We are trying to finish all the reported issues by then.

**Comment by leeomara** [comment]
✅ Looks good on W3 Creatives test site

**Comment by leeomara** [comment]
Looks good on UAT.
