### ISSUE TITLE
Blog filters mismatch

### ISSUE THREAD

**Issue by leeomara** [ytgov/yukon-ca#591]
On blog listings page
e.g. https://yukon-new-d10.w3creatives.com/docroot/en/blogs/digital-information-and-services

Category filter lists more options in D10 than D7

Subcategory filter shows French on English page (maybe same as Category issue?).
![Screenshot 2024-10-02 at 11 53 30 AM](https://github.com/user-attachments/assets/33215e6e-b19a-4d82-b893-9da9152652b6)

**Comment by w3creatives** [comment]
It looks like on the production D7 there is a theme change made after W3 D7 staging server was created.  Previously, filter was showing the options for which no relevant data was existing on the website. We have now changed it to show values for which data exists on the site.

https://yukon-new-d10.w3creatives.com/docroot/en/blogs/digital-information-and-services

**Comment by leeomara** [comment]
✅ This looks perfect on the W3 Creatives test site.

**Comment by leeomara** [comment]
This looks good on UAT.
