### ISSUE TITLE
News quotes missing

### ISSUE THREAD

**Issue by leeomara** [ytgov/yukon-ca#595]
On News content type, the quotes are missing.

Comparing the news release on the test site and the live site. On live (D7) there are three quotes.

- D10 https://yukon-new-d10.w3creatives.com/docroot/en/node/24402
- D7 https://yukon.ca/en/news/yukon-firefighters-meet-in-dawson-for-training-conference

**Comment by w3creatives** [comment]
This is fixed.

**Comment by leeomara** [comment]
✅ This looks good on the W3 Creatives test site

@w3creatives  I expect that I'll need to re-run a migration to see this on YG UAT?

**Comment by w3creatives** [comment]
Yes. Because the quoted text missed the migration.

**Comment by leeomara** [comment]
This looks good on UAT.
