### ISSUE TITLE
W3C test site missing files

### ISSUE THREAD

**Issue by leeomara** [ytgov/yukon-ca#596]
Across the site, there are a number of missing files.

**Slider**

Missing image slider does not show any images 
https://yukon-new-d10.w3creatives.com/docroot/en/emergencies-and-safety/home-fire-safety/get-involved-fire-prevention-week

**Document download**

File fails to load. Download from https://yukon-new-d10.w3creatives.com/docroot/en/takhini-river-fire-xy019-report
(many other documents work fine)

**Blogs top-level page** 

https://yukon-new-d10.w3creatives.com/docroot/en/blogs/
Missing graphic (wildfire)

**Blog listings page**

e.g. https://yukon-new-d10.w3creatives.com/docroot/en/blogs/digital-information-and-services
- Broken graphic above title
- missing graphics

**Comment by w3creatives** [comment]
Ok. We downloaded the files zip from Pantheon again this morning but its not having the latest files.

**Comment by leeomara** [comment]
I've reviewed the W3 Creatives test site with mixed results:

- ❌ **Slider** Missing image slider shows 1 of 2 image (1 image still missing) https://yukon-new-d10.w3creatives.com/docroot/en/emergencies-and-safety/home-fire-safety/get-involved-fire-prevention-week
- ✅ **Document download** Download from https://yukon-new-d10.w3creatives.com/docroot/en/takhini-river-fire-xy019-report
- ❌ **Blogs top-level page**. Missing graphic (wildfire) on https://yukon-new-d10.w3creatives.com/docroot/en/blogs/
- ❌ **Blog listings page** Broken graphic above page title, on https://yukon-new-d10.w3creatives.com/docroot/en/blogs/digital-information-and-services
- ✅ **Blog listings page** missing graphics (beside posts)

**Comment by w3creatives** [comment]
1. For slider, we only see one picture on both D7 and D10.  Please provide more details regarding this.
2. Blogs top level already has the picture for wildfire.
3. Blogs listing page has been fixed and PR[ has been delivered regarding that on October 7, 2024](https://github.com/ytgov/yukon-ca/pull/614).

**Comment by leeomara** [comment]
1. 🤦‍♂️ You are right. Sorry for the noise.
2. ✅ Blogs top-level page. Missing graphic (wildfire) is there now.
3. ❌ Blog listings page Broken graphic above page title. Looks like it's `/themes/custom/yukonca_glider/logo.svg`?

<img width="346" alt="Screen Shot 2024-10-08 at 9 57 18 PM" src="https://github.com/user-attachments/assets/4ebae441-5e86-4b3e-b4c3-9cff9f80f4c2">

**Comment by w3creatives** [comment]
Point-3 is a docroot issue. It will work on Yukon UAT.

**Comment by leeomara** [comment]
This looks good on UAT.
