### ISSUE TITLE
Broken node-ID links

### ISSUE THREAD

**Issue by leeomara** [ytgov/yukon-ca#598]
Many broken links (not docroot related)

Link on the page https://yukon-new-d10.w3creatives.com/docroot/en/emergencies-and-safety/floods/find-out-what-do-after-flood#nav-returning-home

links for 8, 9, 10, 100 are all to 404.

e.g. https://yukon-new-d10.w3creatives.com/docroot/en/emergencies-and-safety/floods/node/21633

**Comment by w3creatives** [comment]
This is because of the recent change in FID and it forward slash in the code. The correct link will be:

https://yukon-new-d10.w3creatives.com/docroot/node/18933

**Comment by leeomara** [comment]
@w3creatives does your reply mean that the original content needs to be edited, or that the migration process will need to be updated/changed to account for content that works like this? Or something else?

**Comment by w3creatives** [comment]
If you check this link:

https://yukon-new-d10.w3creatives.com/docroot/en/emergencies-and-safety/floods/find-out-what-do-after-flood#nav-returning-home

The links for 8, 9, 10, 100 to 404....they all will work if you remove /docroot from URL. Sample below:


https://yukon-new-d10.w3creatives.com/docroot/en/what-do-when-your-private-water-well-has-flooded

**Comment by leeomara** [comment]
Okay, so those links now only have a `/docroot` problem. When I reported this issue, those links all pointed to `node/NNN` URLs (which I suspect relates to your comment about FID?)

**Comment by w3creatives** [comment]
Yes.

**Comment by leeomara** [comment]
For what it's worth:

- ✅ looks good on W3 Creatives test site
- ❌ links are `node/nnnn` on YG UAT from https://yukond10.cms-uat.yukon.ca/en/emergencies-and-safety/floods/find-out-what-do-after-flood#nav-returning-home, one link (no. 8) is https://node/21633

**Comment by w3creatives** [comment]
Please try clearing cache and test again.
