### ISSUE TITLE
Missing redirect leads to error message

### ISSUE THREAD

**Issue by leeomara** [ytgov/yukon-ca#599]
from https://yukon-new-d10.w3creatives.com/docroot/en/covid-19-vaccine, the "Book your vaccine appointment" link points to https://yukon-new-d10.w3creatives.com/docroot/en/sleeves-yukon-future-looking-bright, which reports:

> Access denied 

I suspect this is a missing redirect issue, as on D7 the link gets redirected to `/appointments`

**Comment by leeomara** [comment]
Probably related to
- https://github.com/ytgov/yukon-ca/issues/365

**Comment by w3creatives** [comment]
We are getting the same access denied error on staging D7 which has the latest database:

https://yukon-new-d7.w3creatives.com/en/sleeves-yukon-future-looking-bright

**Comment by w3creatives** [comment]
This should work on the production server by itself.

**Comment by leeomara** [comment]
This will need to wait for production infrastructure to test.

**Comment by leeomara** [comment]
Pre-production (D10) now has yukon.ca (D7) redirects, as of Nov 26.

**Comment by leeomara** [comment]
UAT D10 also has D7 server-side redirects.
