### ISSUE TITLE
General design

### ISSUE THREAD

**Issue by leeomara** [ytgov/yukon-ca#600]
1. Breadcrumbs wrap before needed
    - e.g. https://yukon-new-d10.w3creatives.com/docroot/en/education-and-schools/financial-support-students/apply-scholarship-trade-or-technical-studies

2. Linked text in News "carousel" bottom of home page is not bolded 
    - <img width="906" alt="homepage-news-not-bold" src="https://github.com/user-attachments/assets/b22395f3-6bd4-4b60-853f-fbd5b816cf65">
 
3. Links to subcategories (covid19) not styled consistently  
    - Most are bold, some are not.
    - e.g. https://yukon-new-d10.w3creatives.com/docroot/en/health-and-wellness
    - Also reported as: The first link is not bolded, the title should be the same colour as the others even though it differs by not being clickable. 
    - e.g. https://yukon-new-d10.w3creatives.com/docroot/en/outdoor-recreation-and-wildlife
    - ![links-not-same-weight](https://github.com/user-attachments/assets/551cea98-eda5-4563-91ce-58c5f662282d)

4. Asterisk in Feedback section is red when it should be black
    - <img width="277" alt="feedback required asterisk" src="https://github.com/user-attachments/assets/3112edcf-8190-4020-8b29-d088aded6cce">

5. Excess whitespace
    - Too much white space between in-page alert and bread crumbs https://yukon-new-d10.w3creatives.com/docroot/en/immigration/employers/hire-foreign-worker
    - ![whitespace-1](https://github.com/user-attachments/assets/240f23a2-f06a-421d-af6a-d14712133b9b)
    - White space between title and body copy 
    - ![whitespace-2](https://github.com/user-attachments/assets/65643852-00ff-4929-ac7a-ea8a8ba632c5)

# Not wrong but different

6. Font size issue. Font size for "normal" content slightly larger compared to D7
   - e.g. https://yukon-new-d10.w3creatives.com/docroot/en/health-and-wellness/mental-wellness/get-support-services-during-coroners-inquest

**Comment by w3creatives** [comment]
Issues 1 to 5 are done.
Issue 6: Its a little different if we test it on Mac devices.

**Comment by leeomara** [comment]
- RE 1: 👍 okay
- RE 2: ✅ Looks good on UAT
- RE 3: 
  - ✅ now all bold
  - ❌ making the non-link header the same colour as links was incorrect. 
    - E.g. "ATVs and off-road vehicles" should be black, as it is on D7. https://yukon.ca/en/outdoor-recreation-and-wildlife
- RE 4: ✅ Looks good on UAT
- RE 5: ✅ Looks good on UAT
- RE 6: 👍 okay

**Comment by w3creatives** [comment]
You can review Point-3 again:

https://yukon.ca/en/health-and-wellness
https://yukon-new-d10.w3creatives.com/docroot/en/health-and-wellness

**Comment by leeomara** [comment]
- RE 3: ❌ the non-link header should be black. On W3 test server it is green.
    - E.g. "COVID-19 information" hader should be black, as it is on D7. https://yukon.ca/en/health-and-wellness

![Screenshot 2024-10-18 at 3 00 15 PM](https://github.com/user-attachments/assets/2ca600f0-31b9-4112-b885-f6d6c5d97ed3)

**Comment by w3creatives** [comment]
Please review:

https://yukon-new-d10.w3creatives.com/docroot/en/health-and-wellness

**Comment by leeomara** [comment]
- ✅ Looks good on W3C server.
- ❌ Doesn't (yet?) look right on UAT.

**Comment by leeomara** [comment]
Looks good on UAT.
