### ISSUE TITLE
Basic Page - Related tasks Section

### ISSUE THREAD

**Issue by w3creatives** [ytgov/yukon-ca#603]
Related tasks missing on some Basic Pages:

https://yukon.ca/en/apply-arts-fund
https://dev-yukon-drupal-10.pantheonsite.io/en/arts-and-events/apply-arts-fund
https://yukon-new-d10.w3creatives.com/docroot/en/arts-and-events/apply-arts-fund

**Comment by w3creatives** [comment]
This is fixed and PR[ has been delivered regarding that on October 7, 2024](https://github.com/ytgov/yukon-ca/pull/614).

**Comment by leeomara** [comment]
Look good in UAT.
