### ISSUE TITLE
Places Listing Order 

### ISSUE THREAD

**Issue by w3creatives** [ytgov/yukon-ca#605]
Places listing page order should alphabetical.

https://yukon.ca/en/places
https://dev-yukon-drupal-10.pantheonsite.io/en/places
https://yukon-new-d10.w3creatives.com/docroot/en/places

**Comment by w3creatives** [comment]
This is fixed and PR[ has been delivered regarding that on October 7, 2024](https://github.com/ytgov/yukon-ca/pull/614).

**Comment by leeomara** [comment]
Looks good on UAT
