### ISSUE TITLE
Forms and documents design issues

### ISSUE THREAD

**Issue by w3creatives** [ytgov/yukon-ca#606]
1. More >> link missing for some forms and documents.

https://yukon.ca/en/forms
http://dev-yukon-drupal-10.pantheonsite.io/en/forms
https://yukon-new-d10.w3creatives.com/docroot/en/forms

**Comment by w3creatives** [comment]
This is fixed and PR[ has been delivered regarding that on October 7, 2024](https://github.com/ytgov/yukon-ca/pull/614).

On D7, the "More" link only take the user to homepage. On D10, we have redirected the user to the relevant content instead.

**Comment by leeomara** [comment]
Looks good on UAT.
