### ISSUE TITLE
News - Quick facts

### ISSUE THREAD

**Issue by w3creatives** [ytgov/yukon-ca#607]
1. Quick facts missing on the new page

https://yukon.ca/en/news/government-yukon-signs-letter-intent-work-permits-foreign-nationals-yukon
https://27.yukon-w3-d10.w3creatives.com/en/news/government-yukon-signs-letter-intent-work-permits-foreign-nationals-yukon
https://dev-yukon-drupal-10.pantheonsite.io/en/news/government-yukon-signs-letter-intent-work-permits-foreign-nationals-yukon

**Comment by w3creatives** [comment]
This is fixed and PR[ has been delivered regarding that on October 7, 2024](https://github.com/ytgov/yukon-ca/pull/614).

**Comment by leeomara** [comment]
- On [W3 Creatives test site](https://yukon-new-d10.w3creatives.com/docroot/en/news/government-yukon-signs-letter-intent-work-permits-foreign-nationals-yukon), quotes are missing
- On [UAT](https://yukond10.cms-uat.yukon.ca/en/news/government-yukon-signs-letter-intent-work-permits-foreign-nationals-yukon), quick facts are French on English page

**Comment by leeomara** [comment]
Given that the French-on-the-English page is another issue, I'll close this issue, as the rest of it works on UAT.
