### ISSUE TITLE
URL issue

### ISSUE THREAD

**Issue by w3creatives** [ytgov/yukon-ca#609]
1. Node ID not working but corresponding alias works.

https://yukon.ca/en/node/372
https://dev-yukon-drupal-10.pantheonsite.io/en/node/372
https://yukon-new-d10.w3creatives.com/docroot/en/node/372

**Comment by w3creatives** [comment]
Fixed. It was a migration alias issue. Should be fixed automatically on fresh migration.

**Comment by leeomara** [comment]
On UAT, node 372 resolves as `/news` after the full migration + update (x3)
