### ISSUE TITLE
Unable to save some landing pages due to Primary Content configuration

### ISSUE THREAD

**Issue by leeomara** [ytgov/yukon-ca#612]
Primary Content (paragraph type) Popular links do not allow linking to Basic page (but they should).

Despite migrating okay, links to Basic pages cause validation error when trying to update a landing page.

**Steps to reproduce**

Edit the Employments Landing page, make a trivial change.

**Expected results**

The change is saved.

**Actual results**

Unable to save due to validation error on the Top task links.

# Notes

Example landing page: `/en/employment`

This paragraph type is used for "Top tasks" in Landing Pages. The admin for this field is `/en/admin/structure/paragraphs_type/primary_content/fields/paragraph.primary_content.field_popular_links`

Comparing to D7, the following content types are not allowed in D10:
- Basic Page
- Public engagements

**Comment by w3creatives** [comment]
This is fixed and will be included in the next PR.

**Comment by leeomara** [comment]
Looks good on UAT.
