### ISSUE TITLE
Places times are shifted (timezone issue?)

### ISSUE THREAD

**Issue by leeomara** [ytgov/yukon-ca#613]
The opening times of places records appear shifted by about 15 hours (or maybe back by 7 hours? -- lines up with Whitehorse being -7 UTC).

On D7: "9 a.m. to 12 p.m." https://yukon.ca/en/places/whitehorse-walk-clinic 

On D10: "11:59 pm to 2:59 am" https://yukond10.cms-uat.yukon.ca/en/node/22764

See also https://yukond10.cms-uat.yukon.ca/en/places/sheriffs-office vs https://yukon.ca/en/sheriff-office

![opening-times-shift-display 2024-10-07 at 9 49 09 AM](https://github.com/user-attachments/assets/15eb1e69-16c6-47ab-b202-e877f9bbea00)

This appears to not be simply a display issue. In the admin, the times are as they display (shifted)

![opening-times-shift-admin 2024-10-07 at 9 49 45 AM](https://github.com/user-attachments/assets/182510d8-5828-4e9b-850a-68f93db695f8)

**Comment by leeomara** [comment]
This came up while testing #465.

**Comment by w3creatives** [comment]
Please check if this date format is okay:

https://yukon-new-d10.w3creatives.com/docroot/en/places/whitehorse-walk-clinic

**Comment by leeomara** [comment]
- ✅ The time-shift is gone
- 🟠 but since you asked about the date format, it's not quite right (happy to address these in other issues)
  - In English there shouldn't be a leading zero on times.
      - Not: 01:00 pm to 04:00 pm
      - Rather: 1:00 pm to 4:00 pm  
  - In French, the format should use a 24-hour clock
      - Not:  01:00 pm à 04:00 pm
      - Rather: 13 h à 16 h
  - See also: 
      - https://github.com/ytgov/yukon-ca/issues/465
      - https://github.com/ytgov/yukon-ca/issues/237

**Comment by w3creatives** [comment]
Please review:

https://yukon-new-d10.w3creatives.com/docroot/en/places/whitehorse-walk-clinic
https://yukon-new-d10.w3creatives.com/docroot/fr/places/clinique-medicale-sans-rendez-vous-de-whitehorse

**Comment by leeomara** [comment]
-  ✅ Formatting and time-shift look correct on W3 server, in both English and French
- On UAT
  - ❌ Time-shift looks like it's back. E.g. "Monday to Friday 12:30 am to 12:35 am, 12:36 am to 12:01 am"
  -  ✅ Formatting

**Comment by w3creatives** [comment]
Please review:

https://yukon-new-d10.w3creatives.com/docroot/en/places/whitehorse-walk-clinic

**Comment by leeomara** [comment]
- ✅ Formatting looks good on W3 and UAT
- ❌ Time-shift on both W3 and UAT. 
  - "12:30 am to 12:35 am, 12:36 am to 12:01 am" instead of
  -  "9:00 am to 12:00 pm, 1:00 pm to 4:00 pm"

**Comment by w3creatives** [comment]
Please run https://custom-domain/time URL to resolve this issue.

**Comment by leeomara** [comment]
That was the key!

Looks good on UAT.
