### ISSUE TITLE
Published vs Access Denied Errors

### ISSUE THREAD

**Issue by w3creatives** [ytgov/yukon-ca#616]
Certain private (not published) pages on D7 are in published state on D10. This require additional evaluation.

https://yukon.ca/en/department/tourism-and-culture
https://yukon-new-d10.w3creatives.com/docroot/en/department/tourism-and-culture

**Comment by leeomara** [comment]
(Adding a short note, from #624)

Content that has the Workflow state "Archived" on D7 is migrated as "Published" on D10.

Compare the menus between D7 and D10

- D7: https://yukon.ca/en/archival-reproductions
- D10: https://yukond10.cms-uat.yukon.ca/en/archival-reproductions

On D7 those events appear Archived. During migration those should be migrated as "Archived"

**Comment by leeomara** [comment]
This is another version of
- https://github.com/ytgov/yukon-ca/issues/228

**Comment by leeomara** [comment]
This now looks good on UAT.

Archived content is imported with the (single/last) revision as Archived (unpublished).
