### ISSUE TITLE
Basic page design and formatting

### ISSUE THREAD

**Issue by w3creatives** [ytgov/yukon-ca#617]
1. Page title are bigger on D10 version
2. Page title margins/spacing needs to be increased (D10)
3. Number and bullet lists needs little more spacing (D10)
4. One of the bullet list needs solid bullets (disk) on D10

https://yukon.ca/node/287
https://dev-yukon-drupal-10.pantheonsite.io/node/287
https://yukon-new-d10.w3creatives.com/docroot/en/node/287

**Comment by w3creatives** [comment]
This is done.

**Comment by leeomara** [comment]
Looks good on UAT.
