### ISSUE TITLE
Campaign page email not formated as link

### ISSUE THREAD

**Issue by leeomara** [ytgov/yukon-ca#618]
Email addresses in body copy should automatically be formatted as mailto links.

- D7: https://yukon.ca/fox-lake-local-area-planning
- D10 (UAT): https://yukond10.cms-uat.yukon.ca/fox-lake-local-area-planning

Similar issues for other content types/scenarios:
- https://github.com/ytgov/yukon-ca/issues/168
- https://github.com/ytgov/yukon-ca/issues/185

**Comment by w3creatives** [comment]
This is fixed. Please check on W3 server.

**Comment by leeomara** [comment]
Looks good on the W3 server.

**Comment by leeomara** [comment]
@w3creatives I see this issue is now assigned to me and tagged with UAT-Pending. I don't however see any new code changes in the w3_staging_yukon branch. How can I test these on my UAT if code for these changes hasn't shipped? Am I missing something?

https://github.com/ytgov/yukon-ca/commits/w3_staging_yukon/

**Comment by leeomara** [comment]
Looks good on UAT.
