### ISSUE TITLE
Users Editorial Team values are not migrated

### ISSUE THREAD

**Issue by leeomara** [ytgov/yukon-ca#623]
Moves from a User term field in D7 to something else in Workbench Access (Teams > Assigned sections) in D10.

In D7, there is a Term reference field (Yukon Editorial Team) on the user (`field_yukon_editorial_team`). This then fed into Workbench Access (`/en/admin/config/workbench/access`)

**Comment by leeomara** [comment]
Relates to:
- https://github.com/ytgov/yukon-ca/issues/509

Not to be confused with 
- https://github.com/ytgov/yukon-ca/issues/312

**Comment by leeomara** [comment]
- ❌ Re-tested this in UAT (based on 382143c0, from Oct 25 with pull request #651), no users were in any of the Workbench Access teams. All three teams listed 0 editors.

**Comment by w3creatives** [comment]
We have matched the user IDs as well and migration re-run will assign the editorial departments as well.

**Comment by leeomara** [comment]
❌ Re-tested this in UAT (based on 84da124c, from Nov 5 with pull request W3 - Nov-04-2024-v2#670), no users were in any of the Workbench Access teams. All three teams listed 0 editors.

**Comment by w3creatives** [comment]
This issue is linked with - #362

**Comment by w3creatives** [comment]
Please test it again after running the >> root-domain/custom_migrate.

**Comment by leeomara** [comment]
This looks good on UAT.
