### ISSUE TITLE
Blog posts listed out of order

### ISSUE THREAD

**Issue by leeomara** [ytgov/yukon-ca#625]
D7 is strictly chronological. D10 is not.

- D7 https://yukon.ca/en/blogs/digital-information-and-services
- D10 
	- UAT: https://yukond10.cms-uat.yukon.ca/en/blogs/digital-information-and-services
	- W3 C: https://yukon-new-d10.w3creatives.com/docroot/en/blogs/digital-information-and-services

D7 starts with:

1. Better to Know website relaunches (September 23, 2024)
2. Better to Know website relaunch sees continued UX improvements (September 11, 2024)
3. What usability testing taught us about how people use the Sexualized Assault Response Team (SART) website (August 6, 2024)
4. What we're working on - summer 2024 (July 25, 2024)
5. Getting ready for the next stage of the Yukon open government portal (July 11, 2024)

UAT starts with:

1.  Migration milestone reached (February 7, 2019)
2.  Better to Know website relaunches (September 23, 2024)
3.  Better to Know website relaunch sees continued UX improvements (September 11, 2024)
4.  Getting ready for the next stage of the Yukon open government portal (July 11, 2024)
5.  What usability testing taught us about how people use the Sexualized Assault Response Team (SART) website (August 6, 2024)

W3 C starts with:

1. Migration milestone reached (February 7, 2019)
2. What happens when you submit a comment on Yukon.ca? (March 26, 2024) 
3. Getting ready for the next stage of the Yukon open government portal (July 11, 2024)
4. Looking for user research (UX) participants for upcoming studies (January 23, 2024)
5. What we're working on: summer and fall 2023 (November 15, 2023)

**Comment by w3creatives** [comment]
Now Blog posts listed in order

https://yukon-new-d10.w3creatives.com/docroot/en/blogs/digital-information-and-services

Please pull the latest code to deploy UAT env.

**Comment by leeomara** [comment]
Looks good on UAT.
