### ISSUE TITLE
Blog sidebar review

### ISSUE THREAD

**Issue by leeomara** [ytgov/yukon-ca#626]
What is supposed to be in the sidebar? Currently D7 is inconsistent between English and French.

e.g. https://yukon.ca/fr/blogue-renseignements-et-services-en-ligne/traitement-des-commentaires-recus-sur-yukonca

| D7 English has | D7 French has |
|----|---|
| About this blog | A propos de ce blog  (About this blog) |
| - | Information connexes (Related information) |
| Recent blog posts | Dernieres entree de blog (Recent blog posts) |
| Share on social media | Partager sur les media sociaux (Share on social media)  |

What should be there?

**Comment by lgontard** [comment]
The Eng post side should have the same filters as on the Fre side: About this blog; Related information; Recent blog posts; and Share on social media. I removed the Comments/Commentaires section because it was text put into the Related tasks section and not on any other blogs.

**Comment by leeomara** [comment]
We're not going to worry about this.
