### ISSUE TITLE
Blog social share has Twitter name and logo

### ISSUE THREAD

**Issue by leeomara** [ytgov/yukon-ca#627]
Should be X (ugh) -- or removed?

**Comment by leeomara** [comment]
This was added in 72f42405, as part of work EW did. It's been integrated into the master branch, but until w3_staging_yukon lands in master, we won't see this change on UAT.

- EW work 
  - https://github.com/ytgov/yukon-ca/pull/561
- w3_staging_yukon to master 
  - https://github.com/ytgov/yukon-ca/pull/653

**Comment by w3creatives** [comment]
This is done. Please check.

https://yukon-new-d10.w3creatives.com/docroot/en/digital-blog/what-happens-when-you-submit-comment-yukonca

**Comment by leeomara** [comment]
Looks good on W3 server

**Comment by leeomara** [comment]
Looks good in UAT.
