### ISSUE TITLE
English news has French Quick facts

### ISSUE THREAD

**Issue by leeomara** [ytgov/yukon-ca#628]
Nearly all of the content is English, except Quick facts, which are French.

The French page seems entirely French.

e.g. https://yukon-new-d10.w3creatives.com/docroot/en/news/residential-lot-lotteries-open-faro-carmacks-and-lone-tree-subdivision

**Comment by w3creatives** [comment]
Please check the above URL.

**Comment by leeomara** [comment]
- ✅ This works on W3 test server
- ❌ This is still a problem on UAT, with the most recent codebase.

**Comment by w3creatives** [comment]
We tested it again and its working on W3 test server.  We will wait for the next deployment on YG UAT.

**Comment by leeomara** [comment]
Looks good on UAT.
