### ISSUE TITLE
Peak times block on Find a campground page broken

### ISSUE THREAD

**Issue by leeomara** [ytgov/yukon-ca#633]
On the D7 page (https://yukond10.cms-uat.yukon.ca/en/outdoor-recreation-and-wildlife/camping/find-campground-or-recreation-site) under the header "Will you find a campsite when you get there?" there should be a Peak times chart.

On D10 instead we have:

> **Peak times**
> This block is broken or missing. You may be missing content or you might need to install the original module. 

On W3, the text content is present, but there is no chart or formatting.

> Popular location on weekends. Arrive early afternoon if possible. Good availability Sun. - Thurs. night. Busy weekends and holiday weekends. Very good availability weekdays and weekends.

![Screenshot 2024-10-16 at 2 28 27 PM](https://github.com/user-attachments/assets/2e94b696-8c00-4a65-9c15-2d1217d179fa)

**Comment by leeomara** [comment]
Relates to
- https://github.com/ytgov/yukon-ca/issues/516

**Comment by leeomara** [comment]
Missing graph legend for peak times

**Comment by w3creatives** [comment]
Link to review:

https://yukon-new-d10.w3creatives.com/docroot/en/outdoor-recreation-and-wildlife/camping/find-campground-or-recreation-site

**Comment by leeomara** [comment]
- ✅ This looks good on the W3 test server
- ❌ This remains broken (This block is broken or missing...) on UAT

On UAT, I see no "Campground availability legend" block under `/admin/structure/block`. Are there any particular step in the migration that's related to blocks? 

Tested on UAT at 382143c0, from Oct 25 with pull request #651

**Comment by w3creatives** [comment]
Please review:

https://yukon-new-d10.w3creatives.com/docroot/en/outdoor-recreation-and-wildlife/camping/find-campground-or-recreation-site

This is a new custom block that we have build for this task

**Comment by leeomara** [comment]
Looks great on W3 server.

**Comment by leeomara** [comment]
Looks good on UAT.
