### ISSUE TITLE
Arrivals and departures

### ISSUE THREAD

**Issue by leeomara** [ytgov/yukon-ca#637]
On D7, there is a page that lists airport arrivals and departures for YXY

https://yukon.ca/en/airport-arrivals-departures

This is done with a custom module that provides two blocks, one for arrivals, another for departures. The code for the D7 module is at `sites/all/modules/custom/goy_yxy_flight_schedule` in the D7 repo.

We'd originally anticipated that this module would not be needed in D10, but those plans have not progressed.

**Comment by w3creatives** [comment]
Review link:

https://yukon-new-d10.w3creatives.com/docroot/en/airport-arrivals-departures

**Comment by leeomara** [comment]
Overall this looks great on the W3 server.

I note that "Delayed" arrival status is coloured in D7.

![Screenshot 2024-11-04 at 3 09 45 PM](https://github.com/user-attachments/assets/e8bfd821-2486-45d3-a5ae-d56966accf1b)

**Comment by leeomara** [comment]
This looks pretty good on UAT, however I noticed that the "Arrived" label is not visible in D10.

![Screenshot 2024-11-05 at 12 52 29 PM](https://github.com/user-attachments/assets/80236c0e-181d-4712-83c3-61b2b080ce66)

**Comment by w3creatives** [comment]
Review link:

https://yukon-new-d10.w3creatives.com/docroot/en/airport-arrivals-departures

**Comment by leeomara** [comment]
It's now missing "Early".

<img width="718" alt="Screen Shot 2024-11-07 at 8 27 32 PM" src="https://github.com/user-attachments/assets/786b657b-c223-40fe-a164-eb4e221bae3c">


Instead of hard-coding each distinct value for status (which we don't know or control), how about we instead sanitize and translate what we get from the remote feed?

Instead of an approach like...
https://github.com/ytgov/yukon-ca/blob/w3_staging_yukon/docroot/modules/custom/goy_yxy_flight_schedule/src/Plugin/Block/ArrivalsBlock.php#L196

```php
$status = (string) $xml_flight->Status;
if ($status == "On Time") {
    $status_new = $this->t('On Time');
}
elseif ($status == "Departed") {
    $status_new = $this->t('Departed');
}
// Repeat for code block each value we've ever seen...
```

More something like this?

```php
$status = (string) $xml_flight->Status;
$status_new = $this->t($status);
```

**Comment by leeomara** [comment]
This looks great on UAT.
