### ISSUE TITLE
text-only wildfire updates

### ISSUE THREAD

**Issue by leeomara** [ytgov/yukon-ca#638]
D7 has a custom module that provides text-only wildfire updates, based on data from an external service.

e.g. https://yukon.ca/en/get-yukon-wildfire-updates/dawson-fire-district

In the D7 repo, this module is at `sites/all/modules/custom/goy_wildfire_low_bandwidth`

In D7, this module provides a custom block for each district, which is then placed on each districts page.

**Comment by w3creatives** [comment]
Please review:

https://yukon-new-d10.w3creatives.com/docroot/en/emergencies-and-safety/wildfires/current-wildfires-dawson-fire-district

This is a custom module.

**Comment by leeomara** [comment]
✅ This looks great!

🟠 Only minor point is that the labels (Size of fire, How we're responding, Report date) should be bold/heavy.

**Comment by w3creatives** [comment]
Please review:

https://yukon-new-d10.w3creatives.com/docroot/en/emergencies-and-safety/wildfires/current-wildfires-dawson-fire-district
https://yukon.ca/en/emergencies-and-safety/wildfires/current-wildfires-dawson-fire-district

**Comment by leeomara** [comment]
Looks great on W3 server.
