### ISSUE TITLE
Get text-only wildfire updates page layout

### ISSUE THREAD

**Issue by leeomara** [ytgov/yukon-ca#639]
The layout of this page, with heavy use of CSS and specific widths, does not migrate well.

- D7: https://yukon.ca/en/emergencies-and-safety/wildfires/get-text-only-wildfire-updates
- D10: https://yukond10.cms-uat.yukon.ca/en/node/23571

![Screenshot 2024-10-17 at 11 54 05 AM](https://github.com/user-attachments/assets/f1826e89-b6cb-45f1-807d-0cfa3efe4af2)

**Comment by leeomara** [comment]
Maybe we can fix the inline CSS in D7 with something that's not quite so brittle?

Or revise it once the migration is done.

**Comment by w3creatives** [comment]
Page layout have been done.

https://yukon-new-d10.w3creatives.com/docroot/en/emergencies-and-safety/wildfires/get-text-only-wildfire-updates

Please pull the latest code to deploy UAT env.

**Comment by leeomara** [comment]
Looks good on UAT.
