### ISSUE TITLE
Unable to add audio media

### ISSUE THREAD

**Issue by leeomara** [ytgov/yukon-ca#642]
One many different types of content types we need to allow audio (MP3) media to be added.

Currently in D10, we are unable to upload MP3 files.

![image (3)](https://github.com/user-attachments/assets/c1239e39-3af4-41e9-990d-235f8d8cbffa)

This was tested with a basic page, but may apply elsewhere.

D7 page showing an embedded MP3: https://yukon.ca/en/grizzly-bear

**Comment by w3creatives** [comment]
Please edit the page to review the fix applied. Screenshot attached.

![Screenshot-by-Lightshot-10-25-2024_11_56_AM](https://github.com/user-attachments/assets/86ce4b6c-5552-4a31-8ae6-1fc13b141154)

**Comment by leeomara** [comment]
Looks good on UAT.
