### ISSUE TITLE
Tweak rich text editor toolbar

### ISSUE THREAD

**Issue by leeomara** [ytgov/yukon-ca#644]
Increase and decrease indent and remove formatting icons are grayed out and cannot be applied.

We do not use indent and decrease indent, and on D10 will not need remove formatting. 

Relates to:
- https://github.com/ytgov/yukon-ca/issues/371

**Comment by leeomara** [comment]
This is managed at `en/admin/config/content/formats/manage/full_html`

**Comment by w3creatives** [comment]
We have removed 'indent', 'decrease indent' and 'formatting' from the options. Please review and confirm.

**Comment by leeomara** [comment]
Looks good on UAT.
