### ISSUE TITLE
Month French translation

### ISSUE THREAD

**Issue by leeomara** [ytgov/yukon-ca#645]
Some are translated, others are not.

This shows up in Events, Document, and other places.

e.g. https://yukon-new-d10.w3creatives.com/docroot/fr/annexe-des-salaires-equitables-2024

Previously reported as

> these are translated: Mai, Juin, Juillet, Août. These are not: February, March, April, September, October, November, December

Also the first letter of month in French is capitalized when it shouldn't be. E.g. https://yukon-new-d10.w3creatives.com/docroot/fr/communiques-de-presse

Based on these other reports:
- https://github.com/ytgov/yukon-ca/issues/178#issuecomment-2415001535
- https://github.com/ytgov/yukon-ca/issues/465

**Comment by w3creatives** [comment]
Month translations have been done. 

Please pull the latest code to deploy UAT env.

**Comment by leeomara** [comment]
Feel like we're most of the way there on month names

| Month | Result |
|-------|------|
| janvier | ✅  |
| février | ✅ |
| mars | ✅ |
| avril | ✅ |
| mai  | ✅ |
| juin  | ✅ |
| juillet | ✅ |
| août | ✅ |
| septembre | ✅ |
| octob**er** | ❌ |
| novemb**er** | ❌ |
| décembre | ✅  |

🟠 Using CSS to achieve the lower case seems like maybe not the correct way to handle this.

**Comment by w3creatives** [comment]
Please review: https://yukon-new-d10.w3creatives.com/docroot/fr/communiques-de-presse

**Comment by leeomara** [comment]
Looks good on UAT.
