### ISSUE TITLE
English strings on French blog pages

### ISSUE THREAD

**Issue by leeomara** [ytgov/yukon-ca#657]
On the French blog post the text "This post is older than 6 months." appears in English. I know it was translated and approved in D7 UAT, but I can't find it. The translation is "Ce billet date de plus de 6 mois."

E.g. https://yukon-new-d10.w3creatives.com/docroot/fr/digital-blog/developpement-des-capacites-et-des-competences-numeriques-dans-la-fonction-publique

English content includes:
- This post is older than 6 months.
- Your government
- By {authorname}

**Comment by w3creatives** [comment]
Please review:

https://yukon-new-d10.w3creatives.com/docroot/fr/digital-blog/developpement-des-capacites-et-des-competences-numeriques-dans-la-fonction-publique

**Comment by leeomara** [comment]
Looks good on W3 server.

On UAT
- ✅ Votre gouvernement
- ✅ Par ...
- ❌ This post is older than 6 months.

**Comment by w3creatives** [comment]
Please review:

https://yukon-new-d10.w3creatives.com/docroot/fr/digital-blog/developpement-des-capacites-et-des-competences-numeriques-dans-la-fonction-publique

**Comment by w3creatives** [comment]
We missed the fr.po file.

**Comment by leeomara** [comment]
Looks good on UAT.
