### ISSUE TITLE
Editing nodes as certain roles causes access error

### ISSUE THREAD

**Issue by leeomara** [ytgov/yukon-ca#659]
Reported by HG

> Trying to test #184 and when I went to test uploading an image to a news release, I hit 'save' I got a 'access denied' message...but

![image(1)](https://github.com/user-attachments/assets/60a9b518-cda3-499b-afd6-a5599a9db2d3)

Watchdog reports this error:

> Path: /en/node/24790/latest. Drupal\Core\Http\Exception\CacheableAccessDeniedHttpException: The following permissions are required: 'view latest version' AND 'view any unpublished content'. in Drupal\Core\Routing\AccessAwareRouter->checkAccess() (line 115 of /var/www/yukon-ca-d10/docroot/core/lib/Drupal/Core/Routing/AccessAwareRouter.php).

The user this happened to has the following Drupal roles:
- Editor
- Publisher
- Site Administrator

These roles have the _Content Moderation > View any unpublished_ content permission:
- Writer
- Editor
- Publisher
- Translator
- Site Administrator

No role other than administrator (different than Site Administrator) has the permission _Content Moderation > View the latest version
Requires the "View any unpublished content" or "View own unpublished content" permission_

**Comment by w3creatives** [comment]
We added the permission and changes were deployed. Please check on UAT and confirm.

**Comment by leeomara** [comment]
Looks good on UAT.
