### ISSUE TITLE
News related info link title HTML encoded

### ISSUE THREAD

**Issue by leeomara** [ytgov/yukon-ca#660]
Some News related information titles include content that can be HTML encoded.

![image(2)](https://github.com/user-attachments/assets/75813320-4e7f-4f1b-ae2b-3db83355741c)

| Expected | Actual results |
|---------|----------|
| `S&P` | `S&amp;P` |

D7: https://yukon.ca/en/news/government-of-yukon-introduces-2023-24-public-accounts-to-the-legislative-assembly

Link title in D7: 
> S&P Global Ratings reaffirms ‘AA Stable’ credit rating for 15th consecutive year

In D10, the same title comes out as
> S\&amp;P Global Ratings reaffirms ‘AA Stable’ credit rating for 15th consecutive year

**Comment by w3creatives** [comment]
Please review:

https://yukon-new-d10.w3creatives.com/docroot/en/news/government-yukon-introduces-2023-24-public-accounts-legislative-assembly

**Comment by leeomara** [comment]
Looks good in UAT.
