### ISSUE TITLE
Inconsistent colons

### ISSUE THREAD

**Issue by leeomara** [ytgov/yukon-ca#665]
In general, labels in English should be followed by a colon

> News release #:

While in French, the label should be followed by a space and then a colon

> Numéro du communiqué :

This inconsistency is particularly noticeable with French News releases.

> Numéro du communiqué: :
> ...
> Articles connexes::

Notice the double colons, and missing space between the label and the colon.

This was identified as part of testing
- https://github.com/ytgov/yukon-ca/issues/188

The current state is possibly related to: 
- https://github.com/ytgov/yukon-ca/issues/183
- https://github.com/ytgov/yukon-ca/issues/182

**Comment by w3creatives** [comment]
Please review:

https://yukon-new-d10.w3creatives.com/docroot/en/news/family-mediation-pilot-project-granted-extension

**Comment by leeomara** [comment]
- ✅ The double colon on French is now removed
- ❌ Missing a space between the label and the colon in French. E.g. "connexes:" should be "connexes :"

![Screenshot 2024-11-04 at 3 03 56 PM](https://github.com/user-attachments/assets/68a4e8dd-c2f9-4b41-a4ad-c50f592843a0)

**Comment by w3creatives** [comment]
Please review:

https://yukon-new-d10.w3creatives.com/docroot/en/news/family-mediation-pilot-project-granted-extension

**Comment by leeomara** [comment]
Looks good on UAT.
