### ISSUE TITLE
PHP error showing certain Events

### ISSUE THREAD

**Issue by leeomara** [ytgov/yukon-ca#668]
Some events (like `/fr/events/quest-ce-que-le-prediabete`), result in a server error/site crash.

> The website encountered an unexpected error. Try again later.

Looking at watchdog, I see 
- A number (3) of "Deprecated function: strtotime(): Passing null to parameter # 1 ($datetime) of type string is deprecated in yukonca_glider_preprocess_node__event() (line 279 of /var/www/yukon-ca-d10/docroot/themes/custom/yukonca_glider/yukonca_glider.theme) " for lines 279, 280 and 281
- "Warning: Array to string conversion in Twig\Extension\CoreExtension->convertDate() (line 514 of /var/www/yukon-ca-d10/vendor/twig/twig/src/Extension/CoreExtension.php)"
- "TypeError: DateTime::__construct(): Argument # 1 ($datetime) must be of type string, array given in DateTime->__construct() (line \518 of /var/www/yukon-ca-d10/vendor/twig/twig/src/Extension/CoreExtension.php)."

Of the French Events imported, roughly half show this problem. None of the English Events seem to have this problem.

**Comment by w3creatives** [comment]
We have added a condition that can possibly stop this error. YG can confirm this on next deployment.
