### ISSUE TITLE
French backcountry campground filters have English labels

### ISSUE THREAD

**Issue by leeomara** [ytgov/yukon-ca#671]
On D7: https://yukon.ca/fr/plein-air-faune-et-flore/camping/backcountry-campgrounds

Many of the filter labels are English

- At least one wheelchair accessible campsite
- At least one wheelchair accessible outhouse
- Boat launch
- Hiking trails
- Playground
- Swimming area or dock - no lifeguard

These are probably worth reviewing anyway. Do any backcountry sites have playgrounds or boat launches?

**Comment by w3creatives** [comment]
These translations do not exit on D7 as well.  Please advise us about the preferred approach.

**Comment by lgontard** [comment]
@w3creatives @leeomara These labels are correct in [D7 UAT ](https://yukon.cms-uat.yukon.ca/fr/trouver-un-terrain-de-camping-ou-un-lieu-de-loisirs)

Here are the translations:

At least one wheelchair accessible campsite / Au moins un emplacement de camping accessible aux personnes à mobilité réduite
At least one wheelchair accessible outhouse / Au moins une toilette extérieure accessible en fauteuil roulant
Boat launch / Rampe de mise à l’eau
Hiking trails / Sentiers de randonnée
Playground / Terrain de jeux
Swimming area or dock - no lifeguard / Quai ou aire de baignade. Aucun sauveteur sur les lieux

**Comment by w3creatives** [comment]
If these value are updated on production, only then we will have it migrated correctly.

**Comment by leeomara** [comment]
I was able to do this on pre-prod by editing the translation of the view.

Still need to capture this translation in code, so it's not wiped on the next config:import.
