### ISSUE TITLE
Campaign videos missing caption

### ISSUE THREAD

**Issue by leeomara** [ytgov/yukon-ca#676]
Caption missing beneath video

- D10 has none: https://yukond10.cms-uat.yukon.ca/en/school-curriculum
- D7 has one: https://yukon.ca/en/school-curriculum

D7 shows:

> Yukon's curriculum

This appears to be the case on all videos.

**Comment by w3creatives** [comment]
Please review: 

https://yukon-new-d10.w3creatives.com/docroot/en/school-curriculum

**Comment by leeomara** [comment]
Looks good in UAT.
