### ISSUE TITLE
Campaign page header wrong layout when no hero image

### ISSUE THREAD

**Issue by leeomara** [ytgov/yukon-ca#678]
Some campaign pages do not have a hero image. For those pages, the header layout should be compressed.

As seen here:
- https://yukond10.cms-uat.yukon.ca/sartyukon/support-youth-who-experienced-sexualized-assault
- https://yukond10.cms-uat.yukon.ca/sartyukon/report-to-rcmp
- https://yukond10.cms-uat.yukon.ca/fr/signalement-la-grc
- https://sart-d10.cms-uat.yukon.ca/en/support-hospital-rcmp 

Also seen on W3 server.

D7
<img width="890" alt="image (13)" src="https://github.com/user-attachments/assets/52923cab-7a89-4baf-8d3a-ab49a8990fbd">

D10
<img width="937" alt="image (12)" src="https://github.com/user-attachments/assets/5bb72593-23ab-4636-82cd-50eb4e6d0a68">

**Comment by w3creatives** [comment]
This issue is not clear as there are no hero images on the production website as well.

**Comment by leeomara** [comment]
@lgontard What do you think? Is it an error that some D7 campaign pages don't have a hero image?

e.g. https://yukon.ca/en/sartyukon/support-hospital-rcmp

**Comment by leeomara** [comment]
> @leeomara On the SART site it looks like a design choice. The parent and level one child pages have the hero image, but the level 2 child pages don't. I don't think this is an error because the hero image is not mandatory.

I see that in D7, when no hero image is provided, that the header is much more vertically compressed. There isn't a large empty space like we currently have in D10.

I'd like to see the layout for pages that don't use a hero image tightened up.

**Comment by w3creatives** [comment]
Please review:

https://yukon-new-d10.w3creatives.com/docroot/sartyukon/report-to-rcmp

**Comment by lgontard** [comment]
@w3creatives @leeomara This looks good, resolved.
