### ISSUE TITLE
Campaign hero needs to be translatable

### ISSUE THREAD

**Issue by leeomara** [ytgov/yukon-ca#679]
While not always used, the Hero image is sometimes translated. Currently in D10 it appears not translated.

Only on D10, English page is using the French hero image. French is using the French hero image.

That field needs to be translatable.

- D10
	- English: https://yukond10.cms-uat.yukon.ca/en/support-here-you
	- French: https://yukond10.cms-uat.yukon.ca/fr/des-services-de-soutien-pour-vous
- D7
	- English: https://yukon.ca/en/support-here-you
	- French: https://yukon.ca/fr/soutien-pour-vous

Note "Prévention" in the graphic. English should have large "care" and "understanding"

**Comment by w3creatives** [comment]
Please review:

https://yukon-new-d10.w3creatives.com/docroot/en/support-here-you
https://yukon-new-d10.w3creatives.com/docroot/fr/des-services-de-soutien-pour-vous

**Comment by leeomara** [comment]
Looks good in UAT.
