### ISSUE TITLE
Campaign images have wrong alt text

### ISSUE THREAD

**Issue by leeomara** [ytgov/yukon-ca#680]
In D7, the images in the text-and-image paragraphs each have distinct and relevant alt-text. In D10, the alt-text seems to be derived from the section title. E.g. the first few are all "Counselling" in D10

- D10 https://yukond10.cms-uat.yukon.ca/en/support-here-you
- D7 https://yukon.ca/en/support-here-you

**Comment by w3creatives** [comment]
Please review:

https://yukon-new-d10.w3creatives.com/docroot/en/support-here-you

**Comment by leeomara** [comment]
The `alt` text is correct. I am, however, still seeing a tooltip that doesn't correspond to the image. I think this is coming from the `title` attribute. e.g.

```html
<img src="/sites/default/files/hss-logo-womens-circle.jpg.png" 
  width="359" height="208" 
  alt="Logo for Whitehorse Aboriginal Women's Circle"
  title="Counselling">
```

![Screenshot 2024-11-12 at 1 39 47 PM](https://github.com/user-attachments/assets/ccc9e158-53b5-41bc-a001-1022c3fcc8bf)

**Comment by w3creatives** [comment]
Please review: 

https://yukon-new-d10.w3creatives.com/docroot/en/support-here-you

**Comment by leeomara** [comment]
This looks good on the W3 server site.

**Comment by lgontard** [comment]
@leeomara @w3creatives On This page https://yukon-new-d10.w3creatives.com/docroot/en/support-here-you the alt text appears correctly and the "title" field for the image is gone 
![image](https://github.com/user-attachments/assets/789a281d-9cb5-40f5-8808-7b545243fe5d)
However, the images do not appear.

**Comment by lgontard** [comment]
@leeomara @w3creatives This is resolved on YG UAT
