### ISSUE TITLE
Campaign page body links use node ID

### ISSUE THREAD

**Issue by leeomara** [ytgov/yukon-ca#681]
The links work, but they do not use the alias/path.

Government of Yukon’s Early Learning and Child Care Unit link is to node ID

  https://yukond10.cms-uat.yukon.ca/node/16478

Also on Yukon Police Council
  https://yukond10.cms-uat.yukon.ca/en/yukon-police-council-0

21-22 and 22-23 reports don't go to nodes, but everything else seems to 

"Sharing Common Ground" links are all to node IDs. e.g.
- https://yukond10.cms-uat.yukon.ca/node/10082
- https://yukond10.cms-uat.yukon.ca/node/10082
- https://yukond10.cms-uat.yukon.ca/node/17773

Seems similar to:
- https://github.com/ytgov/yukon-ca/issues/598
- https://github.com/ytgov/yukon-ca/issues/609

**Comment by w3creatives** [comment]
Please review:

https://yukon-new-d10.w3creatives.com/docroot/en/yukon-police-council-0

**Comment by leeomara** [comment]
Looks good on W3 test server.

**Comment by leeomara** [comment]
Looks good on UAT (SG)
