### ISSUE TITLE
Site feedback sometimes fails on campaign pages

### ISSUE THREAD

**Issue by leeomara** [ytgov/yukon-ca#682]
Clicking on thumbs up/down should open a text field and show a submit button.

Works:
- Yukon Police Council

Doesn't work:
- See the future
- School curriculum, https://yukond10.cms-uat.yukon.ca/en/school-curriculum also in French https://yukond10.cms-uat.yukon.ca/fr/programmes-etudes

**Comment by w3creatives** [comment]
Please review:

https://yukon-new-d10.w3creatives.com/docroot/en/school-curriculum

**Comment by leeomara** [comment]
Looks good in UAT.
