### ISSUE TITLE
Awkward interface to select campaign page parent

### ISSUE THREAD

**Issue by leeomara** [ytgov/yukon-ca#683]
The parent page selection is not in alphabetical order, and it doesn't appear I can start typing to auto populate/autocomplete.

Improvements:
- Sort the list
- Support autocomplete

![image (6)](https://github.com/user-attachments/assets/b51c5bb1-80e8-46be-ae85-0d7e2d626f1e)

**Comment by w3creatives** [comment]
Please review:

https://yukon-new-d10.w3creatives.com/docroot/en/node/7672/edit

**Comment by leeomara** [comment]
This looks good on UAT. I now see an auto-complete interface.
