### ISSUE TITLE
Campaign body links are 404 when not campaign sub-pages

### ISSUE THREAD

**Issue by leeomara** [ytgov/yukon-ca#684]
From Support Youth page, https://sart-d10.cms-uat.yukon.ca/en/support-youth-who-experienced-sexualized-assault

Under "Are you under 19 years old and...", links 
- Victim Services https://sart-d10.cms-uat.yukon.ca/en/legal-and-social-supports/supports-victims-crime/find-out-about-victim-services
- Mental Wellness and Substance Use https://sart-d10.cms-uat.yukon.ca/en/health-and-wellness/mental-wellness/get-counselling-and-support-families-youth-and-children)

Same on Service Providers page, https://sart-d10.cms-uat.yukon.ca/en/service-providers

Looks like those are links to Yukon.ca that shouldn't be rendered as/server on the custom domain.

When testing without custom domain, those links work.

This is likely a server/load balancer configuration issue, for @leeomara to deal with.

Related to:
- #629

**Comment by lgontard** [comment]
@leeomara @w3creatives This is resolved on YG UAT
