### ISSUE TITLE
Admin content interface department filter woes

### ISSUE THREAD

**Issue by leeomara** [ytgov/yukon-ca#686]
On Admin / content page, department filter autocomplete doesn't complete.

Triggers (after long delay) a server error.

Could maybe replace autocomplete with drop-down?

One user (HG) reported:

> When using the search dept field in UAT here: I cannot easily filter by department. I tried ‘ECO’, ‘Executive’, ‘executive’ and none of them worked. I had to type in the full name of the department which was not ideal, but that finally worked.

Suggestion: replace this autocomplete with a drop-down menu.

Relates to
- https://github.com/ytgov/yukon-ca/issues/292

**Comment by w3creatives** [comment]
Please review:

https://yukon-new-d10.w3creatives.com/docroot/en/admin/content

**Comment by leeomara** [comment]
Looks great on W3 test server.

**Comment by leeomara** [comment]
Looks good on UAT.
