### ISSUE TITLE
Campaign site navigation links broken (missing language)

### ISSUE THREAD

**Issue by leeomara** [ytgov/yukon-ca#690]
The links don't have `/en` or `/fr`. This leads to 404s.

As it is, clicking on all menu titles for child pages like "get support" leads to 404.

> none of the menu items seem to work, I get 404 error

Clicking on 'Francais' also goes to page not found

E.g. https://yukond10.cms-uat.yukon.ca/fr/commissaire-du-yukon or https://yukon-new-d10.w3creatives.com/docroot/fr/commissaire-du-yukon

All of the navigation in the header are missing `/en/` or `/fr`.

**Comment by leeomara** [comment]
Looking a https://commissionerofyukon.ca/ and https://commissaireduyukon.ca/, a site with language-specific domain names, that we sometimes handle the navigation differently.

**Comment by w3creatives** [comment]
Please review:

https://yukon-new-d10.w3creatives.com/docroot/fr/commissaire-du-yukon

**Comment by leeomara** [comment]
- ✅ On French page, top level links now include language. E.g. "À propos" links to `/fr/commissaireduyukon/propos`
- ❌ On French page, submenu links still do not include language. E.g. Programmes > Programme de financement.. links to `/commissaireduyukon/programme-financement-journee-francophonie-yukonnaise`
- ❌ On English page, none of the links include language in the path.

**Comment by w3creatives** [comment]
Please review:

https://yukon-new-d10.w3creatives.com/docroot/fr/commissaire-du-yukon

**Comment by lgontard** [comment]
@leeomara @w3creatives The French child pages include "fr" in the URL. Not sure if this is an issue, but "docroot/" is missing from the URLs for child pages
On the English pages, the URL includes "en" in child pages. Also missing "docroot/" from child pages
