### ISSUE TITLE
Site feedback sometimes fails on campaign pages on custom domain

### ISSUE THREAD

**Issue by leeomara** [ytgov/yukon-ca#692]
Campaign pages that are on custom domain names cannot submit feedback. An error is reported.

![image](https://github.com/user-attachments/assets/6405b157-1ec9-43ac-bba5-c8f939144422)

E.g. https://commissioner-d10.cms-uat.yukon.ca/en/

Related to:
- #682
- #629

**Comment by leeomara** [comment]
I suspect this is either a content security policy, or maybe something at the load balancer layer.

**Comment by lgontard** [comment]
@leeomara @wc3 The feedback form appears at the bottom of campaign pages. Resolved.

**Comment by lgontard** [comment]
This is probably not resolved on custom domains.

**Comment by leeomara** [comment]
Part of the fix: Need to include `'self'` in the `connect-src` Content Security Policy for each custom domain.

**Comment by leeomara** [comment]
Now the problem is the submission POST to `?ajax_form...` returns a 404 (not found) error.

E.g. `https://commissioner-d10.cms-uat.yukon.ca/en/commissioner-yukon?ajax_form=1&_wrapper_format=drupal_ajax`
