### ISSUE TITLE
Images in campaign text paragraph formatted poorly

### ISSUE THREAD

**Issue by leeomara** [ytgov/yukon-ca#696]
Drop shadows shouldn't apply to all images in body copy.

Images problem with the images problem in text paragraphs on campaign pages

- D7: https://yukon.ca/en/policy-benefits
- D10: https://yukond10.cms-uat.yukon.ca/policy-benefits
 
It looks like this is on all pages of the Yukon First Nations Procurement Policy website:  Policy benefits Learn about YFNPP. Benefits of policy. Industry. First Nations governments. First Nations citizens. First Nations businesses. Development corporation
 
![Screenshot 2024-11-14 at 1 29 11 PM](https://github.com/user-attachments/assets/5039284b-56bf-4a46-9769-b6a5df43db63)

**Comment by w3creatives** [comment]
Please review: 

https://yukon-new-d10.w3creatives.com/docroot/en/policy-benefits

**Comment by lgontard** [comment]
@leeomara @w3creatives This is resolved. The drop shadow has been removed from images in text only blocks.
