### ISSUE TITLE
Campaign named anchors sometimes broken

### ISSUE THREAD

**Issue by leeomara** [ytgov/yukon-ca#697]
A number of campaign pages use internal/named anchors. Some of these (but not all) are broken in D10.

- D7: https://yukon.ca/en/know-medications-impair-your-driving#know-your-medication
- D10: https://yukond10.cms-uat.yukon.ca/en/know-medications-impair-your-driving#know-your-medication

Yukon Grown D10 (these all work in D7, https://yukon.ca/en/yukon-grown)
- ✅ https://yukond10.cms-uat.yukon.ca/en/yukon-grown#About-Yukon-Grown
- ❌ https://yukond10.cms-uat.yukon.ca/en/yukon-grown#Find-a-provider-for-Yukon-Grown-products
- ✅ https://yukond10.cms-uat.yukon.ca/en/yukon-grown#Get-listed-as-a-provider-of-Yukon-Grown-products 

Spring littler clean (some work, some don't):
- D10, FR: https://yukond10.cms-uat.yukon.ca/fr/nettoyage-printanier
- D7, FR: https://yukon.ca/fr/spring-litter-clean-campaign

French "Driving on permafrost", (none of the 3 work) https://yukond10.cms-uat.yukon.ca/fr/conduite-sur-les-routes-affaiblies-par-la-fonte-du-pergelisol
- ❌ L’effet du pergélisol sur les routes
- ❌ Conduire prudemment sur les routes affaiblies par la fonte du pergélisol
- ❌ Conduite sur les routes de gravier

**Comment by leeomara** [comment]
Also, some are broken in D7 as well, but we're not focusing on those for now.

**Comment by w3creatives** [comment]
Please review:

https://yukon-new-d10.w3creatives.com/docroot/fr/conduite-sur-les-routes-affaiblies-par-la-fonte-du-pergelisol

**Comment by lgontard** [comment]
@leeomara @w3creatives This is resolved. The jump points (internal anchors) are working
