### ISSUE TITLE
Links in French campaign page go to English content

### ISSUE THREAD

**Issue by leeomara** [ytgov/yukon-ca#698]
The links within the body on this French campaign page all link to English content. In D7, those same links connect to French pages.

- D10 https://yukond10.cms-uat.yukon.ca/fr/energie-renouvelable
- D7: https://yukon.ca/fr/energie-renouvelable

More examples
- D10: https://yukond10.cms-uat.yukon.ca/fr/conference-lagriculture-au-nord-du-60e-parallele

Vente de parcelles. Example: "En Savoir Plus" links
- D10: https://yukond10.cms-uat.yukon.ca/fr/vente-de-parcelles-par-tirage-au-sort-ou-par-appel-doffres
- D7: https://yukon.ca/fr/vente-de-parcelles-par-tirage-au-sort-ou-par-appel-doffres

Note that some links *do* work the way we expect. E.g. the second and last link.

This French page in D10 has a link that links to an English page. However, the D7 page has a normal node link.

- D7: https://yukon.ca/fr/essor-commun/evaluation-politique
- D10: https://yukond10.cms-uat.yukon.ca/fr/essor-commun/evaluation-politique
 
Link in question on D10 (near the bottom of the page):
![image (16)](https://github.com/user-attachments/assets/b80392af-6a3f-454b-a01d-d4188988b3a3)

Spring littler clean up

- D7: https://yukon.ca/fr/spring-litter-clean-campaign
- D10: https://yukond10.cms-uat.yukon.ca/fr/nettoyage-printanier

These links both go to English doc download pages, even though French versions of the pages exist.

![image (17)](https://github.com/user-attachments/assets/9f573d27-5b2f-4543-8a2d-90de0607e806)

**Comment by w3creatives** [comment]
Please review:

https://yukon-new-d10.w3creatives.com/docroot/fr/essor-commun/evaluation-politique

**Comment by lgontard** [comment]
@leeomara @w3creatives 
**Resolved on these pages**
 https://yukon-new-d10.w3creatives.com/docroot/fr/essor-commun/evaluation-politique
https://yukon-new-d10.w3creatives.com/docroot/fr/vente-de-parcelles-par-tirage-au-sort-ou-par-appel-doffres
**Unresolved on these pages**
https://yukon-new-d10.w3creatives.com/docroot/fr/energie-renouvelable 
https://yukon-new-d10.w3creatives.com/docroot/fr/conference-lagriculture-au-nord-du-60e-parallele

**Comment by lgontard** [comment]
@leeomara @w3creatives 
Resolved in https://yukon-new-d10.w3creatives.com/docroot/fr/energie-renouvelable
https://yukon-new-d10.w3creatives.com/docroot/fr/conference-lagriculture-au-nord-du-60e-parallele

**Unresolved** in the YG UAT
https://yukond10.cms-uat.yukon.ca/fr/energie-renouvelable
https://yukond10.cms-uat.yukon.ca/fr/conference-lagriculture-au-nord-du-60e-parallele

**Comment by w3creatives** [comment]
Please review:

https://yukon-new-d10.w3creatives.com/docroot/fr/energie-renouvelable

**Comment by lgontard** [comment]
@leeomara @w3creatives This is resolved in the W3C environment

**Comment by leeomara** [comment]
Looks good in YG dev.
