### ISSUE TITLE
Campaign internal: link broken

### ISSUE THREAD

**Issue by leeomara** [ytgov/yukon-ca#699]
A link in D7 that uses a node link turns into a broken link in D10. 

- ✅ D7 link is `node/24788`, which resolves to `https://yukon.ca/en/monitor-and-review-committee-2023-24-annual-report`
- ❌ D10 link is `internal:/node/24788`, which is broken, does not work.

Location: Call to action block ("Monitor and Review Committee annual report")

- D7: https://yukon.ca/en/evaluating-policy
- D10: https://yukond10.cms-uat.yukon.ca/evaluating-policy

Location Call to action block "View the Yukon Grown list")
- ✅ D7: https://yukon.ca/en/yukon-grown link is to https://yukon.ca/en/doing-business/support-agriculture/find-provider-yukon-grown-products
- ❌ D10: https://yukond10.cms-uat.yukon.ca/en/yukon-grown, link is to `internal:/node/17934`

Possibly related to: 
- #681

**Comment by w3creatives** [comment]
Please review:

https://yukon-new-d10.w3creatives.com/docroot/en/evaluating-policy

**Comment by lgontard** [comment]
@leeomara @w3creatives This is resolved.
