### ISSUE TITLE
PHP error accessing campaign page

### ISSUE THREAD

**Issue by leeomara** [ytgov/yukon-ca#700]
From Policy Benefits, clicking on "Home" (in the header) leads to this error

> The website encountered an unexpected error. Try again later.

D10 UAT
- From https://yukond10.cms-uat.yukon.ca/policy-benefits 
- the "home" link is https://yukond10.cms-uat.yukon.ca/growing-together

Similar page on W3, https://yukon-new-d10.w3creatives.com/docroot/growing-together also reports the same error 

Watchdog reports an error like:

```
TypeError: strtr(): Argument #1 ($string) must be of type string, array given in strtr()
 (line 542 of /var/www/yukon-ca-d10/vendor/twig/twig/src/Extension/CoreExtension.php).
```

**Comment by w3creatives** [comment]
Please review: 

https://yukon-new-d10.w3creatives.com/docroot/growing-together

**Comment by lgontard** [comment]
@leeomara @w3creatives This is resolved when you add "docroot" to the URL.
