### ISSUE TITLE
Many staff do not have access to rich text editor (Full HTML)

### ISSUE THREAD

**Issue by leeomara** [ytgov/yukon-ca#708]
Many Drupal roles do not have access to the now-commonly-used "Full HTML" text format.

Work around: manually change which roles have access to the "Full HTML" text format, at `/en/admin/config/content/formats`

**Comment by w3creatives** [comment]
As we checked, we see the same permissions on both the versions.  An example will be helpful.

**Comment by leeomara** [comment]
I think the problem is that in D7, there were many input formats that many roles had access to. Now in D10, most content is Full HTML, which is only available to the "administrator" role (not most users).

![Screenshot 2024-11-27 at 3 09 46 PM](https://github.com/user-attachments/assets/cdf173a0-c47a-4d2d-8e4b-2ed556cdf44c)

**Comment by w3creatives** [comment]
Can we do this manually by performing the following steps?

1) Go into this URL /admin/config/content/formats/manage/full_html
2) Select the roles for which we need to give permission to access of the Full HTML format.

**Comment by leeomara** [comment]
I've done this in the 3 YG environments. We'll need to capture the config in code, otherwise this change will be lost on the next `config:import`

**Comment by leeomara** [comment]
As predicted, this change was reverted as part of our last wave of migrations, as a result, many users were not able to edit content.

I'll re-open this until the configuration is captured in code.

**Comment by leeomara** [comment]
UAT and prod have been reset to the configuration in code, which was also updated in a few places.
