### ISSUE TITLE
Some campaign video content sized incorrectly

### ISSUE THREAD

**Issue by leeomara** [ytgov/yukon-ca#710]
The player is really small in comparison to prod D10

D10
<img width="443" alt="image" src="https://github.com/user-attachments/assets/9a1f1be4-35a4-4c3e-b8c5-81a0f0fbaee4">

D7
<img width="564" alt="image" src="https://github.com/user-attachments/assets/473afaad-caed-4218-a1a9-40e3784b2b71">

I believe this is different than the video sizing issue identified as part of 
- #675

(First identified by LG here: https://github.com/ytgov/yukon-ca/issues/694#issuecomment-2492375252)

**Comment by w3creatives** [comment]
Please review:

https://yukon-new-d10.w3creatives.com/docroot/en/commissionerofyukon/awards

**Comment by leeomara** [comment]
This looks good on W3 server

**Comment by leeomara** [comment]
Looks good on pre-prod.
