### ISSUE TITLE
French campaign page: add a block dropdown menu missing

### ISSUE THREAD

**Issue by lgontard** [ytgov/yukon-ca#715]
@leeomara @w3creatives On a French campaign page, on the back end under the list of blocks (Campaign site) there is no dropdown menu to add another type of block
<img width="309" alt="image" src="https://github.com/user-attachments/assets/a2249807-a70e-4878-89c0-6cc863b45d52">
<img width="442" alt="image" src="https://github.com/user-attachments/assets/79185755-2d58-45ba-a0a8-6d0f984a2f37">

<img width="527" alt="image" src="https://github.com/user-attachments/assets/79f13d2a-7800-45ab-b521-f4f89730f36f">

**Comment by w3creatives** [comment]
Please review and let us know.

**Comment by lgontard** [comment]
@w3creatives @leeomara This is fixed in W3C environment

**Comment by leeomara** [comment]
Looks good in pre-prod.
