### ISSUE TITLE
Site crash on My Workbench

### ISSUE THREAD

**Issue by leeomara** [ytgov/yukon-ca#726]
On back end, My Workbench, My edits, All recent content lead to error “The website encountered an unexpected error. Try again later.

> PHP error reported is: TypeError: Cannot access offset of type string on string in Drupal\views\Plugin\views\area\Text->preQuery() (line 50 of core/modules/views/src/Plugin/views/area/Text.php).

https://yukon.ca/en/admin/workbench

<img width="383" alt="image" src="https://github.com/user-attachments/assets/ffa27cfc-753a-4d09-ae51-b417ed1479ef">

Possibly relate to this known issue: https://www.drupal.org/project/workbench/issues/3484630

**Comment by w3creatives** [comment]
composer.json has the patch for it in the latest PR #751

**Comment by leeomara** [comment]
Fix from #751 looks good in my dev environment.
