### ISSUE TITLE
Broken blocks

### ISSUE THREAD

**Issue by leeomara** [ytgov/yukon-ca#728]
At the bottom of the News page below the page numbers, there’s this notice: 

> This block is broken or missing. You may be missing content or you might need to install the original module.

<img width="468" alt="image" src="https://github.com/user-attachments/assets/95c88769-a6b5-48b0-bd80-df4fee7cf5c8">

**Comment by w3creatives** [comment]
You can safely remove this block:

https://yukon.ca/admin/structure/block/manage/views_block__news_listing_block_1

**Comment by leeomara** [comment]
I made this change in UAT and in prod. I'll leave this issue open until the configuration is captured in code.

**Comment by leeomara** [comment]
This change has been captured in code and deployed.
