### ISSUE TITLE
Review modules and code for removal post migration

### ISSUE THREAD

**Issue by leeomara** [ytgov/yukon-ca#740]
Modules to consider removing:
- PHP Authentication shield
- Module Missing Message Fixer
- Admin Toolbar Links Access Filter 
- Single Content Sync
- Feeds
- Feeds Tamper
- Page Manager
- Mail Safety
- All Migration-related modules
- Link checker
- Tamper
- Search 404
- Responsive Preview

Migration-specific code:
- migration bash scripts
- yukon_migrate
- yukon_w3_migrate

**Comment by leeomara** [comment]
Worth considering that we may want things like Mail Safety in dev and UAT, but not prod.

**Comment by w3creatives** [comment]
As we tested you can manually disable the following modules:

1. PHP Authentication shield - keep it for now
2. Module Missing Message Fixer - (Disable)
3. Admin Toolbar Links Access Filter  - (Disable)
4. Single Content Sync - Yukon base module has a dependency with this module.
5. Feeds  - (Disable)
6. Feeds Tamper - (Disable)
7. Page Manager  - (Disable)
8. Mail Safety - Keep it for now
9. Link checker - Keep it for now
10. Search 404 - (Disable)
11. Responsive Preview - We need it

All Migration-related modules - 

1) Migrate Scanner - (Disable)
2) Yukon Migrate - (Disable)
3) Migrate Drupal - (Disable)
4) Migrate Plus - (Disable)
5) Migrate Tools - (Disable)
6) yukon w3 migrate - (Disable)
7) Migrate - (Disable)
