### ISSUE TITLE
French blogs page does not show images

### ISSUE THREAD

**Issue by leeomara** [ytgov/yukon-ca#758]
French side of blogs landing page does not show the image for each blog

URL: https://yukon.ca/fr/blogs

| French | English |
|--------|---------|
| <img width="137" alt="screenshot of French blogs listing page" src="https://github.com/user-attachments/assets/7965a705-42f6-4e01-afeb-ef75fda14115" />  | <img width="177" alt="screenshot of English blogs listing page" src="https://github.com/user-attachments/assets/f0abeb85-5ae9-4f26-866c-867c7c754df7" /> |

Reported by @lgontard

**Comment by w3creatives** [comment]
Is it possible to add these 4 images manually?

**Comment by lgontard** [comment]
I added the images manually.
