### ISSUE TITLE
Cannot upload Excel file to document download page

### ISSUE THREAD

**Issue by lgontard** [ytgov/yukon-ca#767]
Amelie at Liquor Corp cannot upload Excel spreadsheet. @leeomara This is urgent it has to do with the GST holiday that starts tomorrow.
<img width="598" alt="image" src="https://github.com/user-attachments/assets/8f1d9448-0fe6-4905-8bf8-3ef4cb0c42ce" />

**Comment by leeomara** [comment]
I changed the "Allowed file extensions" for Document (node) _File_ field, to "txt, doc, docx, pdf, xls, xlsx, mp3" (matching D7).

**Comment by leeomara** [comment]
I see this Document page with a linked Excel spreadsheet, so I guess that change is sufficient.

https://yukon.ca/en/yukon-liquor-corporation-maximum-sales-price-list-december-2024

**Comment by lgontard** [comment]
Yes, resolved.

**Comment by leeomara** [comment]
I'd like to leave this open until the changes are captured in code, otherwise this change will get reverted on the next deploy.
