### ISSUE TITLE
Error when trying to log in to UAT

### ISSUE THREAD

**Issue by lgontard** [ytgov/yukon-ca#774]
@leeomara Trying to log in to D10UAT since 12:20 pm. Got this error. On Edge. Do not get this error in prod.
<img width="875" alt="image" src="https://github.com/user-attachments/assets/c2bed740-6669-4956-a54c-b668b6f42bcb" />

**Comment by leeomara** [comment]
I just tested UAT, at https://yukon.cms-uat.yukon.ca/en/user/login

The "Log in with MyYukon" brought me to the MyYukon (UAT) login system.

![Screenshot 2024-12-16 at 1 16 36 PM](https://github.com/user-attachments/assets/f69c1595-c20d-4a86-8684-574548570b28)

**Comment by lgontard** [comment]
Working now for me, too.
