### ISSUE TITLE
English field names appear on the French Places page (community facility, government office)

### ISSUE THREAD

**Issue by lgontard** [ytgov/yukon-ca#783]
On the French Places record, the manager and assistant manager field titles appear in English

<img width="347" alt="image" src="https://github.com/user-attachments/assets/2d266549-0a48-41cf-bc3f-0fe701b5429a" />

https://yukon.ca/fr/places/services-aux-victimes-de-whitehorse

**Comment by leeomara** [comment]
The [relevant template](https://github.com/ytgov/yukon-ca/blob/main/docroot/themes/custom/yukonca_glider/templates/paragraphs/paragraph--community-facilities.html.twig) looks like its doing the right thing.

Have we checked to see if "Manager" and "Assistant manager" have translations entered in Drupal? I.E. under 
 Admin >  Configuration > Region and Language > User Interface Translation

**Comment by lgontard** [comment]
@leeomara This is resolved.
