### ISSUE TITLE
Yukon editorial team field missing from French side

### ISSUE THREAD

**Issue by lgontard** [ytgov/yukon-ca#809]
On these pages, on the French side the Yukon editorial team field is missing.  On site-wide alert. This may be connected to #808 https://github.com/ytgov/yukon-ca/issues/808
https://yukon.ca/fr/emploi/trouvez-un-emploi-dans-la-fonction-publique/offres-demplois-etudiants-programme-step
https://yukon.ca/fr/places/securite-des-batiments-et-normes-de-construction
https://yukon.ca/fr/node/24114

**Comment by w3creatives** [comment]
https://yukon.ca/en/admin/structure/types/manage/basic_page/fields/node.basic_page.field_yukon_editorial_team

Users may translate this field https://prnt.sc/boNFMnZN07Mc

https://yukon.ca/en/admin/structure/types/manage/site_wide_alert/fields/node.site_wide_alert.field_yukon_editorial_team 

https://prnt.sc/cswXjjLxXJH2

https://yukon.ca/en/admin/structure/types/manage/site_wide_alert/fields/node.site_wide_alert.field_department_term 

https://prnt.sc/DBeY8fpZgGco

**Comment by lgontard** [comment]
Done.

**Comment by leeomara** [comment]
Is Editorial Team really a translatable field? Should it be? Don't we want the same value regardless of language?

**Comment by lgontard** [comment]
By following the steps outlined, the editorial team and department fields appear in Eng on the Fre side of pages (these boxes were checked on other content types). Not sure if the fields are really "translatable", maybe more like appearing on the French side?
